### PR TITLE
Merged ESIL parsing for ARM str instructions of all sizes.

### PR DESCRIPTION
**Pull request by qwuau06**
Also fixed remaining ARM str post-indexing problems w/ register offsets in https://github.com/radareorg/radare2/pull/15298 Forgot to fix it last time.

### CODE REVIEW

**Comment by radare** [comment]
please rebase your commits on top of master and put only the commits that matter, not merge conflicts  and unrelated commits

**Comment by qwuau06** [comment]
> please rebase your commits on top of master and put only the commits that matter, not merge conflicts and unrelated commits

Sorry for the confusion. Just rebased.

**Comment by radare** [comment]
please rebase again, master is green

**Comment by qwuau06** [comment]
> please rebase again, master is green

rebased. Is it correct now?

**Comment by radare** [comment]
Screenshot 2019-10-23 at 14 40 56

**Comment by radare** [comment]
please take a look at those regressions , there are 4 failing tests

**Comment by radare** [comment]
nope

**Comment by qwuau06** [comment]
@radare that's weird. I haven't touched the ldr instructions yet. But on the other hand I did send another pr on r2r fixing the str addressing issue for 4 test cases.

**Comment by qwuau06** [comment]
I'll double check when I get back.

**Comment by radare** [comment]
Maybe your r2r branch is not in sync with master?

**Comment by qwuau06** [comment]
@radare think I know where the problem might be. Will post an update asap.

**Comment by qwuau06** [comment]
> Maybe your r2r branch is not in sync with master?
> […](#)
> On 23 Oct 2019, at 23:39, Qian ***@***.***> wrote: ﻿ I'll double check when I get back. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

should be fixed now.

**Comment by radare** [comment]
its not green because you didnt rebased. but this one is weird. please rebase
Screenshot 2019-10-24 at 15 23 52

**Comment by radare** [comment]
your r2r branch wasnt rebased. ill just blind merge and hope its grin . thx!

**Comment by qwuau06** [comment]
@radare thank you for that. Btw may I ask what should i do next time? I've rebased both repos several times so if it still turns out not I guess I might have done something wrong.

What I did was git fetch upstream followed by git rebase -i upstream/master, and force push it into the remote branch. The last two pushes I did yesterday didn't cause any changes in files so I must have been missing something.

**Comment by radare** [comment]
yeah you did right, maybe it was an issue in travis or the script that fetches the branch

**Pull request merged**
