### PR TITLE
WIP: Fix build in directories with spaces ##build

### PR DESCRIPTION
**Pull request by radare**

### CODE REVIEW

**Comment by ret2libc** [comment]
@radare this seems it was working (or at least it didn't break travis). Did you test it on build dirs with spaces? Can we merge it?

**Comment by radare** [comment]
Didnt tested probably requires this change in many other places. This pr is just a reminder

**Comment by radare** [comment]
maybe we can modify the travis script to build r2 in a directory with spaces, this way we can test it properly in CI

**Comment by ret2libc** [comment]
what was wrong with it? can we either fix or close it?

**Comment by radare** [comment]
its fixing some of the cases, but not all of them, the pr is incomplete, but the whole concept of having r2 in a directory containing spaces cringes me a bit.

**Comment by ret2libc** [comment]
Closing. This had no review, no changes, no nothing for a long time. I'm closing the PR as there is no benefit in keeping this open. The branch will still be active, so if @trufae wants he can continue working on this when he has time. No need to keep it in the backlog.

**Pull request closed without merging**
