### PR TITLE
[5.8.0] Fix memory leak in r_str_list_join()

### PR DESCRIPTION
**Pull request by richardpl**
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

### CODE REVIEW

**Comment by trufae** [comment]
I think we should break abi and make this function iterate over the list instead of poping it to the end. So i would keep that change for 5.8

**Comment by trufae** [comment]
i think i fixed the bug you were trying to chase on windows builds :D anyway, i still prefer to fix this memleak by making this api iterate instead of destroy the list

**Comment by richardpl** [comment]
Should i rename commit message?

**Comment by richardpl** [comment]
The leak still happens in master, so this merge will wait for 5.8.0.

**Comment by trufae** [comment]
Yep

**Comment by trufae** [comment]
can you finish this pr now that we can break apis? :D

**Comment by richardpl** [comment]
What is needed? Does it still apply? The CL stuff is green ignoring random unrelated problem(s).

**Comment by trufae** [comment]
Right! i though the callers should be updated, but its not the case :) merged!

**Pull request merged**
