### PR TITLE
WIP: Create more GitHub action jobs for meson and gcc/clang

### PR DESCRIPTION
**Pull request by ret2libc**
**Detailed description**

Let's try to move some jobs from Travis to GHActions. In theory, this should add GH actions to test meson, acr, gcc, clang, osx, linux in various combinations. Maybe it's worth doing something like what I've done in https://github.com/radareorg/radare2/pull/16439, where the full tests are run only one for each OS.

### CODE REVIEW

**Comment by XVilka** [comment]
I suggest to move also Debian packaging here:
- https://github.com/radareorg/radare2-release/issues/35
- https://github.com/radareorg/radare2-release/issues/34
- https://github.com/radareorg/radare2/issues/16329

**Comment by ret2libc** [comment]
Please assign those issues to me, I will do in separate PRs.

**Comment by ret2libc** [comment]
@radare @XVilka ok I think this is a good set of GH actions for PR (see the actions in this PR). If this works well, I think we can remove Travis from PR completely.

For commits on master branch, instead, I will add later another workflow file that runs all the tests on all builds and also have Coverage. Travis will still be needed in this case to test ARM64, ppc64 and s390x archs.

**Comment by ret2libc** [comment]
Much faster!

**Comment by radare** [comment]
Maybe we can keep travis for the non-x86 platforms? or we can do everything in gh-actions?

**Comment by XVilka** [comment]
Yes, we can keep Travis only for non-x86 platforms

**Pull request merged**
