### PR TITLE
Update alloc.c

### PR DESCRIPTION
**Pull request by Princess-Sunset-Shimmer**
- [x] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

### CODE REVIEW

**Comment by trufae** [comment]
?

**Comment by Princess-Sunset-Shimmer** [comment]
sorry for my buggy update;
now have new changes trying to fix;

**Comment by trufae** [comment]
Can you explain whats the bug?

**Comment by Princess-Sunset-Shimmer** [comment]
yes, (i not confirm yet) i first translate this block of codes:
```c
while (heap_end > ( (char *)p_mcb + elem_size + sz)) {
		if (p_mcb->is_available == 0) {
			if (p_mcb->size == 0) {
				flag = NEW_MCB;
				break;
			}
			if (p_mcb->size >= (elem_size + sz) ) {
				flag = REUSE_MCB;
				break;
			}
		}
		p_mcb = (MCB_P) ((char *)p_mcb + p_mcb->size);
	}
```
into equivalent format of this:
```c
LOOP:
    	if (heap_end > ( (char *)p_mcb + elem_size + sz)) goto BREAK;
    	if (p_mcb->is_available != 0) goto L0;
    	if (p_mcb->size != 0) goto L1;
    	flag = NEW_MCB;
    	goto BREAK;
L1:
    	if (p_mcb->size < elem_size + sz) goto L0;
    	flag = REUSE_MCB;
    	goto BREAK;
L0:
    	p_mcb = (MCB_P) ((char *)p_mcb + p_mcb->size);
    	goto LOOP;
BREAK:
```

**Comment by Princess-Sunset-Shimmer** [comment]
then i compress 3 conditions of 3 if statements(not loop's if statement) by making a inputs/outputs relation list (i name (p_mcb->is_available != 0) as condition 'A', (p_mcb->size != 0) as 'B', (p_mcb->size < elem_size + sz) as 'C')
| A, B, C | keep flag as 0x1 | change flag to |
| ------- | ---------------- | -------------- |
| 1, 1, 1 | YES              |                |
| 1, 0, 0 | YES              |                |
| 1, 1, 0 | YES              |                |
| 0, 1, 1 | YES              |                |
| 1, 0, 1 | YES              |                |
| 0, 0, 0 | NO               | 0              |
| 0, 0, 1 | NO               | 0              |
| 0, 1, 0 | NO               | 0x2            |

        so 3 conditions between flag keeping as 0x1 is: A | B & C
        if flag needs to be changed then the flag got changed to 0x2 relates to condition B to be 0x1 otherwise the flag keeps to be 0; the "flag = B << 0x1;" can take this.
        so the codes got written into third phase:
```c
LOOP:
	if (heap_end > ( (char *)p_mcb + elem_size + sz)) goto BREAK;
	if (flag = p_mcb->is_available != 0 | p_mcb->size != 0 & p_mcb->size < elem_size + sz) goto L0;
	falg = (p_mcb->size != 0) << 0x1;
	goto BREAK;
L0:
	p_mcb = (MCB_P) ((char *)p_mcb + p_mcb->size);
	goto LOOP;
BREAK:
```

**Comment by Princess-Sunset-Shimmer** [comment]
then i translate the while loop statement back to while loop statement:
```c
while (heap_end > ( (char *)p_mcb + elem_size + sz)) {
	if (flag = p_mcb->is_available != 0 | p_mcb->size != 0 & p_mcb->size < elem_size + sz) goto L0;
	falg = (p_mcb->size != 0) << 0x1;
	break;
L0:
	p_mcb = (MCB_P) ((char *)p_mcb + p_mcb->size);
	}
```

**Comment by Princess-Sunset-Shimmer** [comment]
then you can find you can move the statement that make sure if condition B are true then flag must be 0x2 out to the while loop statement and get rip of break statement:
```c
while (heap_end > ( (char *)p_mcb + elem_size + sz)) {
	if (flag = p_mcb->is_available != 0 | p_mcb->size != 0 & p_mcb->size < elem_size + sz)
		p_mcb = (MCB_P) ((char *)p_mcb + p_mcb->size);
	}
	falg = (p_mcb->size != 0) << 0x1;
```

**Comment by Princess-Sunset-Shimmer** [comment]
compress if statement's condition in to while loop's condition express, bust must update flag check;
        if flag is 0x1 then keep it to be 0x1, else if condition B is true then set flag 0x2 otherwise the flag is 0:

| flag, B | change flag to |
| ------- | -------------- |
| 1, 0    | 0x1            |
| 0, 1    | 0x2            |
| 1, 1    | 0x1            |
| 0, 0    | 0              |
        flag = (flag ^ B) + B

```c
while (heap_end > ( (char *)p_mcb + elem_size + sz)) & (flag = p_mcb->is_available != 0 | p_mcb->size != 0 & p_mcb->size < elem_size + sz) {
	p_mcb = (MCB_P) ((char *)p_mcb + p_mcb->size);
	}
	falg = (p_mcb->size != 0 ^ flag) + (p_mcb->size != 0);
```

**Comment by Princess-Sunset-Shimmer** [comment]
then we get a high compressed, more readable and maintainable codes that rip off if then, if then, if then... and break statements. But i don't confirm its correctness yet, i didn't compile, debug and test it yet

**Comment by radare** [comment]
Is this an ellaborated joke?

**Pull request closed without merging**
