### PR TITLE
WIP: Fix #22576 - Honor asm.emu in pdfj ##disasm

### LINKED ISSUE #22576: Include refs on rcall and ucall on pdfj command
## Description

* the whole story is described in this long (sorry) issue: https://github.com/radareorg/radare2/issues/22571#issuecomment-1933797133

* basically, including refs on `rcall` / `ucall` would save us form implementing a memory/register tracer

* is it planned?

### PR DESCRIPTION
**Pull request by trufae**
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

### CODE REVIEW

**Comment by trufae** [comment]
This is actually what we have in pdJ, isnt?  cc @attilamester

**Comment by attilamester** [comment]
Not exactly. Since `pdJ` returns what pd but in json, even with `e asm.emu=true`, the instruction in question (https://github.com/radareorg/radare2/issues/22576#issuecomment-1938634219) looks like this in pdJ:
```
{"offset":4219569,"text":"│           0x004062b1      ffd7           call edi                    ; esp=0xffffffe8 ; eip=0x3020c reloc.KERNEL32.dll_HeapAlloc"}
```

which actually does contain the dynamic address, but not in the way pdf contains at `refs` section with simple hex address.

**Comment by trufae** [comment]
Ok so the text is there but not the ref. This can be improved i think to extend the current json with that info. So we dont make pdj more complicated. Sgty?

**Comment by trufae** [comment]
I think that works like you want  now :) but i pushed the code in another pr

Screenshot 2024-03-30 at 20 46 59

**Comment by attilamester** [comment]
Thanks! Super!

**Pull request closed without merging**
