### PR TITLE
Mark fixed tests as such

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

Some tests were fixed since. Mark them properly.

### CODE REVIEW

**Comment by XVilka** [comment]
Hmm, only at OpenBSD:
```
[XX] db/tools/rasm2 rasm2 #1167 3
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '!rasm2 -s att -a x86.as -b 64 "test %rbx, %rax" ' -
-- stdout
@@ -1 +1 @@
-4885d8
+4885c3

[XX] db/tools/rasm2 rasm2 #1167 4
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '!rasm2 -s intel -a x86.as -b 64 "test rax, rbx" ' -
-- stdout
@@ -1 +1 @@
-4885d8
+4885c3
```
looks like some memory initialization or something like that.

**Comment by XVilka** [comment]
Curiously, also Swift demangling behaves differently on MacOS:
```

[XX] db/formats/mangling/swift elf swift demangle (requires swift-demangle program)
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc isq~0x004009e0 bins/elf/analysis/hello-swift
-- stdout
@@ -1 +1 @@
-0x004009e0 16 Swift.String.init (_builtinStringLiteral(Builtin.RawPointer byteSize__Builtin.Word isASCII__Builtin.Int1 _) -> String
+0x004009e0 16 Swift.String.init(_builtinStringLiteral: Builtin.RawPointer, byteSize: Builtin.Word, isASCII: Builtin.Int1) -> Swift.String

[XX] db/tools/rabin2 rabin2 -D swift
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '!rabin2 -D swift  _TFSSCfT21_builtinStringLiteralBp8byteSizeBw7isASCIIBi1__SS' bins/elf/libc.so.0
-- stdout
@@ -1 +1 @@
-Swift.String.init (_builtinStringLiteral(Builtin.RawPointer byteSize__Builtin.Word isASCII__Builtin.Int1 _) -> String
+Swift.String.init(_builtinStringLiteral: Builtin.RawPointer, byteSize: Builtin.Word, isASCII: Builtin.Int1) -> Swift.String

-- stderr
Warning: run r2 with -e io.cache=true to fix relocations in disassembly

[XX] db/cmd/cmd_i iD
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'iD swift _TFSSCfT21_builtinStringLiteralBp8byteSizeBw7isASCIIBi1__SS' bins/elf/libmagic.so
-- stdout

-- stderr
Cannot determine entrypoint, using 0x00005fa8.
Warning: run r2 with -e io.cache=true to fix relocations in disassembly
```

cc @trufae

**Comment by XVilka** [comment]
And rafind2 fails only with Windows:
```
[XX] C:\projects\radare2\test\db\tools\rafind2 rafind2 -m
ANSICON=1 R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '!!rafind2 -m bins/elf/ioli/crackme0x00' -
-- stdout
@@ -1 +0,0 @@
-0x00000000 1 ELF 32-bit LSB executable, Intel 80386, version 1
[XX] C:\projects\radare2\test\db\tools\rafind2 rafind2 -i
ANSICON=1 R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '!!rafind2 -i bins/elf/ioli/crackme0x00' -
-- stdout
@@ -1 +0,0 @@
-0x00000000 1 ELF 32-bit LSB executable, Intel 80386, version 1
```

**Comment by XVilka** [comment]
Also this one looks interesting - apart from TIMEOUT, looks like a logical bug in handling Windows console?
```
[XX] TIMEOUT C:\projects\radare2\test\db\tools\rabin2 rabin2 -S, -SS, -rS and -rSS file elf
ANSICON=1 R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '!rabin2 -S %R2_FILE%|wc -l|awk "{print $1}"
!rabin2 -SS %R2_FILE%|wc -l|awk "{print $1}"
!env RABIN2_PREFIX=prixfixe rabin2 -S %R2_FILE%
!env RABIN2_PREFIX=prixfixe rabin2 -SS %R2_FILE%
' bins/elf/analysis/x86-helloworld-gcc
-- stdout
@@ -1,51 +1,3 @@
 35
 14
-[Sections]
-
-nth paddr        size vaddr       vsize perm name
--------------------------------------------------
-0   0x00000000    0x0 0x00000000    0x0 ---- prixfixe.
-1   0x00000134   0x13 0x08048134   0x13 -r-- prixfixe..interp
-2   0x00000148   0x20 0x08048148   0x20 -r-- prixfixe..note.ABI_tag
-3   0x00000168   0x24 0x08048168   0x24 -r-- prixfixe..note.gnu.build_id
-4   0x0000018c   0x20 0x0804818c   0x20 -r-- prixfixe..gnu.hash
-5   0x000001ac   0x50 0x080481ac   0x50 -r-- prixfixe..dynsym
-6   0x000001fc   0x4a 0x080481fc   0x4a -r-- prixfixe..dynstr
-7   0x00000246    0xa 0x08048246    0xa -r-- prixfixe..gnu.version
-8   0x00000250   0x20 0x08048250   0x20 -r-- prixfixe..gnu.version_r
-9   0x00000270    0x8 0x08048270    0x8 -r-- prixfixe..rel.dyn
-10  0x00000278   0x18 0x08048278   0x18 -r-- prixfixe..rel.plt
-11  0x00000290   0x23 0x08048290   0x23 -r-x prixfixe..init
-12  0x000002c0   0x40 0x080482c0   0x40 -r-x prixfixe..plt
-13  0x00000300  0x194 0x08048300  0x194 -r-x prixfixe..text
-14  0x00000494   0x14 0x08048494   0x14 -r-x prixfixe..fini
-15  0x000004a8   0x15 0x080484a8   0x15 -r-- prixfixe..rodata
-16  0x000004c0   0x2c 0x080484c0   0x2c -r-- prixfixe..eh_frame_hdr
-17  0x000004ec   0xb0 0x080484ec   0xb0 -r-- prixfixe..eh_frame
-18  0x0000059c    0x4 0x0804959c    0x4 -rw- prixfixe..init_array
-19  0x000005a0    0x4 0x080495a0    0x4 -rw- prixfixe..fini_array
-20  0x000005a4    0x4 0x080495a4    0x4 -rw- prixfixe..jcr
-21  0x000005a8   0xe8 0x080495a8   0xe8 -rw- prixfixe..dynamic
-22  0x00000690    0x4 0x08049690    0x4 -rw- prixfixe..got
-23  0x00000694   0x18 0x08049694   0x18 -rw- prixfixe..got.plt
-24  0x000006ac    0x8 0x080496ac    0x8 -rw- prixfixe..data
-25  0x000006b4    0x0 0x080496b4    0x4 -rw- prixfixe..bss
-26  0x000006b4   0x11 0x00000000   0x11 ---- prixfixe..comment
-27  0x000006c5  0x106 0x00000000  0x106 ---- prixfixe..shstrtab
-28  0x00000c7c  0x450 0x00000000  0x450 ---- prixfixe..symtab
-29  0x000010cc  0x257 0x00000000  0x257 ---- prixfixe..strtab
-
-[Segments]
-
-nth paddr        size vaddr       vsize perm name
--------------------------------------------------
-0   0x00000034  0x100 0x08048034  0x100 -r-x prixfixe.PHDR
-1   0x00000134   0x13 0x08048134   0x13 -r-- prixfixe.INTERP
-2   0x00000000  0x59c 0x08048000  0x59c -r-x prixfixe.LOAD0
-3   0x0000059c  0x118 0x0804959c  0x11c -rw- prixfixe.LOAD1
-4   0x000005a8   0xe8 0x080495a8   0xe8 -rw- prixfixe.DYNAMIC
-5   0x00000148   0x44 0x08048148   0x44 -r-- prixfixe.NOTE
-6   0x000004c0   0x2c 0x080484c0   0x2c -r-- prixfixe.GNU_EH_FRAME
-7   0x00000000    0x0 0x00000000    0x0 -rw- prixfixe.GNU_STACK
-8   0x00000000   0x34 0x08048000   0x34 -rw- prixfixe.ehdr
-
+[s
\ No newline at end of file
-- stderr
stty: 'standard input': Inappropriate ioctl for device
-- exit status: -1
```

**Comment by XVilka** [comment]
Ah, it's because we use Swift demangler if presented. But the demangling results should be uniform, moreover this behavior change should not be in tests. Can we disable this? @trufae @ret2libc

**Comment by XVilka** [comment]
Now it's a new problem in Windows:
```
[XX] C:\projects\radare2\test\db\tools\radiff2 radiff2 gnu unified string comparison
ANSICON=1 R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '!!radiff2 -Uz bins/elf/elf_one_symbol_shdr bins/elf/elf_one_symbol_shdr1 | tail -n 2' -
-- stdout
@@ -1,2 +1,2 @@
--Hello world!
-+AAAAo world!
+-     je 0x4013a0
++     je 0x40139d
```

**Comment by trufae** [comment]
i would prefer not to disable the swift test. its important. you can set an env var to avoid using the system demangler, that may do a consistent behaviour

**Comment by XVilka** [comment]
Hmm, FreeBSD:
```
[XX] db/cmd/cmd_project Custom types in project file
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'tk char **=type
tk type.char **=**z
tk type.char **.size=64
Ps custom_types > /dev/null
Pc custom_types~?char **
"td struct Foo { int bar; int x; int y; };"
Ps custom_types > /dev/null
Pc custom_types~?char **
Pc custom_types~?Foo
Pd custom_types > /dev/null
' bins/elf/analysis/main
-- stdout
@@ -1,3 +1,3 @@
 9
 9
-8
+0
```

**Review by trufae — APPROVED** [review]

**Comment by trufae** [comment]
Seems like there are some broken tests in BSD, can you rebase maybe they are just false positives. Thanks!

Screenshot 2020-12-06 at 22 55 59

**Comment by trufae** [comment]
There's no GNU diff in BSD... this is the only failing test, can you mark it as broken again? fixing the issue could imply using gdiff instead of diff if available, which would be desirable, but its out of the scope of this PR imho.


```
[XX] db/tools/radiff2 radiff2 gnu unified string comparison
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '!!radiff2 -Uz bins/elf/elf_one_symbol_shdr bins/elf/elf_one_symbol_shdr1 | tail -n 2' -
-- stdout

```

**Comment by XVilka** [comment]
I rebased and marked this radiff2 test as broken. This should be fine for you now. @trufae

**Pull request merged**
