### PR TITLE
Fix ARM assembler for blt, ble, cmn, tst, and teq instructions ##asm

### PR DESCRIPTION
**Pull request by kyufie**
- [x] Mark this if you consider it ready to merge
- [x] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

### CODE REVIEW

**Comment by trufae** [comment]
Can you add tests to proove what your patch is fixing?

**Comment by trufae** [comment]
See the test/db/asm/arm* files to add the tests. you can run them with `r2r -i path/to/file`

**Comment by trufae** [comment]
Dont do merge commits as they use to mess the history line. Just rebase

**Comment by trufae** [comment]
Thank you!

**Comment by kyufie** [comment]
You're welcome.

**Pull request merged**
