### PR TITLE
Use Inno Setup 6.0 for Windows builds

### PR DESCRIPTION
**Pull request by XVilka**
It was updated from the Inno Setup 5.0 in https://github.com/appveyor/ci/issues/2948

Lets check if it works.

### CODE REVIEW

**Comment by XVilka** [comment]
WTF:
```
Parsing [Languages] section, line 41
   File: C:\Program Files (x86)\Inno Setup 6\Languages\Greek.isl
Error on line 41 in C:\projects\radare2\radare2-win-installer\radare2.iss: Couldn't open include file "C:\Program Files (x86)\Inno Setup 6\Languages\Greek.isl": The system cannot find the file specified.
Compile aborted.
Command exited with code 2
```

**Comment by XVilka** [comment]
@Maijin @pelijah @GustavoLCR @a1ext any advice? Should we drop the unsupported languages? Or change the script instead?

**Comment by Maijin** [comment]
They are in https://github.com/jrsoftware/issrc/tree/master/Files/Languages/Unofficial

**Comment by a1ext** [comment]
> @Maijin @pelijah @GustavoLCR @a1ext any advice? Should we drop the unsupported languages? Or change the script instead?

I think we should go with languages what are being supported by ISS that we use. Abandoned translations won't be updated in the future (so pessimistic :) ) and can cause errors, like errors in formatting the messages like the following:
`LastErrorMessage=%1.%n%nViga %2: %3`

**Comment by Maijin** [comment]
I'm also fine dropping unsupported language

**Comment by XVilka** [comment]
https://github.com/radare/radare2-win-installer/pull/17 please merge then this, then we rebase.

**Comment by Maijin** [comment]
I merged the other one

**Pull request merged**
