### PR TITLE
WIP: Run full tests on fewer jobs during PR

### PR DESCRIPTION
**Pull request by ret2libc**
**Detailed description**

In PRs:
- only OS X and Linux-CLANG-build will run full tests, the other will just check the compilation
- on master branch all tests as of right now are run.

**Test plan**

Unfortunately some things can be tested only once this will be merged in master.

### CODE REVIEW

**Comment by ret2libc** [comment]
I also removed ASAN from each master commit... I don't think we are looking at those "unchecked" jobs often enough to make it worth having that (long) extra time to each commit. 

ASAN will still be run when you create a branch with the name `release-XXXX` or `prerelease-XXXXXX`. Those branches names are useful to have better testing before releases.

**Comment by ret2libc** [comment]
Not ready yet, wait.

**Comment by thestr4ng3r** [comment]
Tests on Linux-meson are important since that job does the coverage. But it will probably be faster on github actions anyway.

**Comment by ret2libc** [comment]
> Tests on Linux-meson are important since that job does the coverage. But it will probably be faster on github actions anyway.

I know, I just disabled them on the PR, but it will still run on master branch on every commit. I just think we don't really need to check the difference in coverage for each PR, WDYT?

**Comment by kazarmy** [comment]
> I just think we don't really need to check the difference in coverage for each PR, WDYT?

Emm the coverage check is only done on PRs afaik. No point in doing them on master right?

**Comment by ret2libc** [comment]
> > I just think we don't really need to check the difference in coverage for each PR, WDYT?
> 
> Emm the coverage check is only done on PRs afaik. No point in doing them on master right?

What? Why? I'm pretty sure it runs on every master commit as I had configured it time ago (see https://codecov.io/gh/radareorg/radare2/branch/master ). It should still work on every commit AFAIK. Why would you want the coverage only on PRs and not on master? I think the purpose of coverage is for us to see which part of the code are not well tested and, in theory, improve the testing for those parts.

**Comment by kazarmy** [comment]
Oh ok then. Are we still going to get those Codecov reports (e.g. https://github.com/radareorg/radare2/pull/16417#issuecomment-609379506)?

**Comment by ret2libc** [comment]
If we don't run on PR, no, but... did we ever use them? :/ If there is any requests for them, we can keep the meson build as the one that runs all tests, but only if we really care. Otherwise let's run them only on master.

**Comment by kazarmy** [comment]
> If we don't run on PR, no, but... did we ever use them?

We should care about them but I don't think anybody did. Don't think anybody cares about https://codecov.io/gh/radareorg/radare2/branch/master as well, at least for now.

**Comment by kazarmy** [comment]
Though if we then did care about it, it would be rather tricky to fix coverage since we wouldn't know whether our fixes worked until they are already in master, and if they didn't actually work...?

But like you said, enable on request.

**Comment by ret2libc** [comment]
> Though if we then did care about it, it would be rather tricky to fix coverage since we wouldn't know whether our fixes worked until they are already in master, and if they didn't actually work...?
> 
> But like you said, enable on request.

Yeah, when someone will want to go into this direction, we can easily have travis builds (or GH actions) that are run when specific branch names are used in PR, for example. For the moment I think we don't really need them on every PR as nobody is caring about those.

**Comment by kazarmy** [comment]
Ok

**Comment by ret2libc** [comment]
Actually since I'm already working on https://github.com/radareorg/radare2/pull/16442 I think this can be almost be closed/changed.

**Pull request closed without merging**
