### PR TITLE
Dont do assumptions on syscall search, esil emulation is fast enough …

### PR DESCRIPTION
**Pull request by trufae**
…##search

- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

### CODE REVIEW

**Comment by alessandrocarminati** [comment]
The original purpose for this patch, where the "exit" and "exit group" syscalls weren't present on a search on the gilibc x86_64 build, has been resolved.
Testing the same on the aarch64 architecture revealed that it appears to have created a bug that prevents it from producing any output.
```
$ r2 glibc-2.34-39.el9.aarch64_libc.so.6
Warning: run r2 with -e bin.cache=true to fix relocations in disassembly
 -- If you want to open the file in read-write mode, invoke r2 with '-w'
[0x0002c980]> aei
[0x0002c980]> /as
0x00027408 io_setup
[0x0002c980]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze all functions arguments/locals
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Finding and parsing C++ vtables (avrr)
[x] Finding function preludes
[x] Finding xrefs in noncode section (e anal.in=io.maps.x)
[x] Analyze value pointers (aav)
[x] aav: 0x00000000-0x00188018 in 0x0-0x188018
[x] Emulate functions to find computed references (aaef)
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information (aanr)
[x] Use -AA or aaaa to perform additional experimental analysis.
[0x0002c980]> aei
[0x0002c980]> /as
[0x0002c980]>
```

**Comment by trufae** [comment]
Its not even passing the tests when running on x86. So its not yet mergeable. I run this thing on arm64 and worked fine. So there must be something that is not configured properly in the esil initialization. Will chk again

**Comment by alessandrocarminati** [comment]
Although my original issue was solved, the ESIL emulation introduced by the patch, I noticed only this morning that it also removes a few good results with respect to the previous version w/o ESIL.
Here is an extract from the comparison between the two results.
|old impl. w/o ESIL             | this patch w ESIL             |
|-------------------------------|-------------------------------|
|0x00040179 shutdown            |0x00040179 shutdown            |
|0x000401a9 socket              |0x000401a9 socket              |
|0x000401dc socketpair          |0x000401dc socketpair          |
|0x0004030d sigaltstack         |0x0004030d sigaltstack         |
|**0x00040464 exit**            |**0x00040464 read**            |
|                               |0x00055327 rt_sigreturn        |
|0x000553f1 rt_sigaction        |0x000553f1 rt_sigaction        |
|0x0005555e rt_sigpending       |0x0005555e rt_sigpending       |
|0x000555aa rt_sigsuspend       |0x000555aa rt_sigsuspend       |
|0x000555d8 rt_sigsuspend       |0x000555d8 rt_sigsuspend       |
|0x00055fd6 rt_sigtimedwait     |0x00055fd6 rt_sigtimedwait     |
|                               |0x00056038 rt_sigtimedwait     |
|0x00056129 rt_sigqueueinfo     |0x00056129 rt_sigqueueinfo     |
|0x00059005 getrandom           |0x00059005 getrandom           |
|0x0005903d getrandom           |0x0005903d getrandom           |
|                               |0x000590c0 read                |
|0x00061f39 kill                |0x00061f39 kill                |
|0x00070b89 rename              |0x00070b89 rename              |
|0x00070bbc renameat            |0x00070bbc renameat            |
|0x00070c01 renameat2           |0x00070c01 renameat2           |
|**0x00095a3e writev**          |**0x00095a3e read**            |
|0x0009c8a7 futex               |0x0009c8a7 futex               |
|0x0009c928 futex               |0x0009c928 futex               |
|0x0009ca89 futex               |0x0009ca89 futex               |

The entries in bold are the welcome results that this patch introduced, but you can also see empty cells representing lost results.
Looking at the 0x00055327 rt_sigreturn, for example,
```
0x00055320      48c7c00f0000.  mov rax, 0xf
0x00055327      0f05           syscall
0x00055329      0f1f80000000.  nop dword [rax]
```
I can see it is a legitimate result, to be fair, an easy one.

**Comment by trufae** [comment]
Thanks for the details, i will take some time after cutting a patch release to understand better the code constructions that lead to those regressions after the patch. maybe worth adding separate commands for esil and static findings, but ideally it should find them all by default.

**Comment by trufae** [comment]
@alessandrocarminati can you test again this PR? :) i think it should be good now

**Comment by richardpl** [comment]
I just want to mention that on meson builds the syscalls are not resolving at all for some reason (in disassembly view, it only show numbers). sorry if this is unrelated.

**Comment by trufae** [comment]
merged!

**Comment by trufae** [comment]
thanks for reporting that @ricardoapl maybe worth running the testsuite against meson builds too. its semi-related to this issue, but not blocker

**Pull request closed without merging**
