### PR TITLE
Update quickjs and fix tests ##build ##lang ##test

### PR DESCRIPTION
**Pull request by satk0**
- [x] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

### CODE REVIEW

**Comment by satk0** [comment]
msvuckingc plz compile

**Comment by trufae** [comment]
D:\a\radare2\radare2\shlr\qjs\src\quickjs-c-atomics.h(53): fatal error C1083: Cannot open include file: 'stdatomic.h': No such file or directory
[1226/1571] Compiling C object libr/lang/r_lang.dll.p/.._.._shlr_ 😭

**Comment by trufae** [comment]
for wasm:
```
/shlr/qjs/src/cutils.h:54:10: fatal error: 'pthread.h' file not found
   54 | #include <pthread.h>
      |          ^~~~~~~~~~~
```

for msvc

```
diff --git a/quickjs.c b/quickjs.c
index 989855f..67f50e4 100644
--- a/quickjs.c
+++ b/quickjs.c
@@ -62,7 +62,7 @@
 #define NO_TM_GMTOFF
 #endif

-#if !defined(EMSCRIPTEN) && !defined(__wasi__)
+#if !defined(EMSCRIPTEN) && !defined(__wasi__) && (!defined(_MSC_VER) || _MSC_VER > 1920)
 #include "quickjs-c-atomics.h"
 #define CONFIG_ATOMICS
 #endif
```

**Comment by satk0** [comment]
lol

image

**Comment by satk0** [comment]
feels like a problem with `libbf` linking

**Comment by trufae** [comment]
maybe we need to link to the libbf.c when using qjsng

**Comment by satk0** [comment]
Ok I will try linking it, thanks for the advice

**Comment by satk0** [comment]
there is `QJSFILES+=libbf.c` in `shlr/qjs/deps.mk` already, idk if that is the linking thing

**Pull request merged**
