### PR TITLE
Fix #16281 - Do not load system-wide plugins twice ##core

### LINKED ISSUE #16281: radare2 double-loads plugin libraries
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Archlinux on x86-64
| File format of the file you reverse (mandatory)      | all
| Architecture/bits of the file (mandatory)            | all
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.4.0-git 24044 @ linux-x86-64 git.4.3.1-95-g537a811f0 commit: 537a811f0fa6d39303cf91d729ef7868ced56a43 build: 2020-03-22__15:20:58

### Behavior

After installing both radare2 and r2ghidra-dec from Archlinux repositories, I found this:

```
$ r2 /bin/ls
Not loading library because it has already been loaded from somewhere else: '/usr/lib/radare2/4.3.1/core_ghidra.so'
```

Seems like that path is trying to be loaded twice:

```
$ R_DEBUG=1 r2 /bin/ls       
Cannot open directory '/usr/lib/radare2/4.3.1'
Cannot open directory '/usr/lib/radare2/4.3.1'
Cannot open directory '/usr/lib/radare2-extras/4.3.1'
Cannot open directory '/usr/lib/radare2-bindings/4.3.1'
USER CONFIG loaded from /home/imyxh/.config/radare2/radare2rc
```

Also, confirmed on a build straight from git, installed with sys/user.sh—but this time, because of a redundant symlink:

```
$ R_DEBUG=1 ~/bin/radare2 /bin/ls
Cannot open /home/imyxh/bin/prefix/radare2/lib/radare2/last
Cannot open /home/imyxh/bin/prefix/radare2/lib/radare2/4.4.0-git
Cannot open directory '/home/imyxh/bin/prefix/radare2/lib/radare2-extras/4.4.0-git'
Cannot open directory '/home/imyxh/bin/prefix/radare2/lib/radare2-bindings/4.4.0-git'
USER CONFIG loaded from /home/imyxh/.config/radare2/radare2rc

$ file ~/bin/prefix/radare2/lib/radare2/last 
/home/imyxh/bin/prefix/radare2/lib/radare2/last: symbolic link to 4.4.0-git
```

Not exactly sure why this is occurring. One relevant source file seems to be [libr/core/libs.c](https://github.com/radareorg/radare2/blob/master/libr/core/libs.c).

### PR DESCRIPTION
**Pull request by radare**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

see the issue

**Test plan**

complicated and boring to test in the CI

**Closing issues**

yes

### CODE REVIEW

**Comment by ret2libc** [comment]
@imyxh could you test this PR with regard to the issue you opened 2 weeks ago? I also get:
```
Cannot open directory '/usr/local/lib64/radare2/4.4.0-git'
Cannot open directory '/usr/local/lib64/radare2/4.4.0-git'
```
but I do not receive the message `Not loading library because it has already been loaded from somewhere else`, so I cannot reproduce. @radare if you can reproduce please share steps to reproduce.

**Comment by imyxh** [comment]
Works for me. It still complains about not being able to open directories that exist, but as far as I can tell, the plugin is functional and there's no error message without R_DEBUG.

```
$ R_DEBUG=1 ~/bin/radare2 /bin/ls
Cannot open /home/imyxh/bin/prefix/radare2/lib/radare2/last
Cannot open /home/imyxh/bin/prefix/radare2/lib/radare2/4.4.0-git
Cannot open /home/imyxh/.local/share/radare2/plugins/r2ghidra_sleigh
Loading /home/imyxh/.local/share/radare2/plugins/core_ghidra.so
PLUGIN LOADED 0x561d5bb48850 fcn 0x7fd45cb82bbb
Cannot open directory '/home/imyxh/bin/prefix/radare2/lib/radare2-extras/4.4.0-git'
Cannot open directory '/home/imyxh/bin/prefix/radare2/lib/radare2-bindings/4.4.0-git'
USER CONFIG loaded from /home/imyxh/.config/radare2/radare2rc
 -- Please register your copy of r2 today! Only £29.90!
[0x00005b20]> s entry0; aa; pdg
[x] Analyze all flags starting with sym. and entry0 (aa)

// WARNING: [r2ghidra] Failed to match type int for variable argc to Decompiler type: Unknown type identifier int

void entry0(undefined8 placeholder_0, undefined8 placeholder_1, int64_t arg3)
{
        undefined8 in_stack_00000000;
        undefined auStack8 [8];
        
        (*_reloc.__libc_start_main)(main, in_stack_00000000, &stack0x00000008, 0x17330, 0x173a0, arg3, auStack8);
        do {
        // WARNING: Do nothing block with infinite loop
        } while( true );
}
[0x00005b20]> 
```
Perhaps it is saying the "cannot open" message because it's looping through files in R2_LIBDIR and trying to open them as plugins, but failing on the directories? Just a guess. Note that "cannot open x" is the weird message, "cannot open directory x" is correct because they don't exist.

**Comment by ret2libc** [comment]
Thanks @imyxh for the quick reply! @radare I think we can merge!

**Comment by radare** [comment]
Strstr was a hack i wanted to find a better solution before being merged. Maybe check if it ends with r_str_endswith

**Pull request merged**
