### PR TITLE
Fix UB in cannotated_code

### PR DESCRIPTION
**Pull request by trufae**
```
cannotated_code.c: In function 'r_core_annotated_code_print_json':
cannotated_code.c:80:4: warning: 'type_str' may be used uninitialized in this function [-Wmaybe-uninitialized]
    pj_ks (pj, "syntax_highlight", type_str);
```
 

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Review by ret2libc — COMMENTED** [review]
What system/compiler are you using for this? I think the code is actually fine and the only case where type_str is not initialize is if you are missing a value in the switch, but in that case the compiler should provide another warning about a missing enum value. I think this is definitely a false positive.

**Comment by trufae** [comment]
Did you answered using a mail client? Because the html response was fuckedup.

Refering your question. Its ubuntu20

**Comment by ret2libc** [comment]
> Did you answered using a mail client? Because the html response was fuckedup.

No, I did not. I replied as always.

> Refering your question. Its ubuntu20

Do these warnings appear by default or did you enable any particular cflag?

**Comment by trufae** [comment]
by default i didnt applied any special flag

**Comment by ret2libc** [comment]
@trufae could you tell me exactly how you did that? I've just tried on a ubuntu:groovy container by doing `./sys/install.sh` and also `./configure;make` but none of these reported this warning (nor the others).

**Comment by trufae** [comment]
It's ubuntu:focal in gitlab's CI, didnt tried in local, but those are real warnings. Do youw ant the full log?

the one for this issue is:

```
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cannotated_code.c: In function 'r_core_annotated_code_print_json':
cannotated_code.c:80:4: warning: 'type_str' may be used uninitialized in this function [-Wmaybe-uninitialized]
    pj_ks (pj, "syntax_highlight", type_str);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Review by wargio — COMMENTED** [review]
What about adding default to that switch that initialize the `type_str` to `NULL` ?

**Comment by ret2libc** [comment]
> What about adding default to that switch that initialize the `type_str` to `NULL` ?

I personally prefer to not do that, and I think this is a false positive (as explained above). Given all values are handled in the switch, `type_str` should never be null. The reason why I personally prefer to not add a default value is that if you add a new value in the enum, the compiler will warn you that there is a value not handled in the switch. If you provide the default case, the compiler will not provide such a warning and you will probably end up forgetting about it.

Said that, I'm okish with this fix if it makes some compiler happier, but it is not a real bug IMO so no "Fix UB in cannotated code".

**Comment by trufae** [comment]
I think it's safer this way in case that more cases are added and not handled, it wont be printing trash. But yeah, i agree that it's not a real bug. this patch just make the code safer. Feel free to decide what to do. I'm also happy to remove compiler warnings even if those are bugs in their side

**Comment by ret2libc** [comment]
In any case I think you could use type_str ="" instead of null, so you don't have to put a useless if.

**Comment by trufae** [comment]
The if is on purpose to not add this field in case the highlight type info is not available. Just to try to avoid cluttering the output. im fine for doing the change.

**Review by wargio — APPROVED** [review]

**Pull request merged**
