### PR TITLE
Fix #17062 - segfault analyzing gameboy rom

### LINKED ISSUE #17062: Analyzing a Gameboy ROM results in segfault
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 20.04 64 bit
| File format of the file you reverse (mandatory)      |  .gb (Game Boy ROM)
| Architecture/bits of the file (mandatory)            | Gameboy
| r2 -v full output, **not truncated** (mandatory)     |  radare2 4.5.0-git 24830 @ linux-x86-64 git.4.4.0-274-g77cc18ba0 commit: 77cc18ba046bc1966704df759f37833a063f9e01 build: 2020-06-13__10:54:02

### Expected behavior
To be able to analyze the file

### Actual behavior
Results in a segmentation fault.

### Steps to reproduce the behavior 
```
$ r2 -A file.gb 
[Segmentation fault (core dumped)th sym. and entry0 (aa)
```

### Additional files
The file : [file.zip](https://github.com/radareorg/radare2/files/4774161/file.zip)

Backtrace:

```
#0  __strcmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:101
#1  0x00007ffff627fb26 in extract_arg (anal=0x555555575810, fcn=0x55555565e860, op=0x7fffffffc6b0, reg=0x0, 
    sign=0x7ffff6483826 "+", type=98 'b') at var.c:592
#2  0x00007ffff6281d25 in r_anal_extract_vars (anal=0x555555575810, fcn=0x55555565e860, op=0x7fffffffc6b0) at var.c:1006
#3  0x00007ffff627ab88 in fcn_recurse (anal=0x555555575810, fcn=0x55555565e860, addr=336, len=524288, depth=62) at fcn.c:1196
#4  0x00007ffff627adfb in r_anal_fcn_bb (anal=0x555555575810, fcn=0x55555565e860, addr=336, depth=63) at fcn.c:1230
#5  0x00007ffff6279902 in fcn_recurse (anal=0x555555575810, fcn=0x55555565e860, addr=257, len=524288, depth=63) at fcn.c:909
#6  0x00007ffff627adfb in r_anal_fcn_bb (anal=0x555555575810, fcn=0x55555565e860, addr=256, depth=64) at fcn.c:1230
#7  0x00007ffff627b43e in r_anal_fcn (anal=0x555555575810, fcn=0x55555565e860, addr=256, len=524288, reftype=0) at fcn.c:1342
#8  0x00007ffff6cd7ecb in __core_anal_fcn (core=0x7ffff5d22010, at=256, from=18446744073709551615, reftype=0, depth=62)
    at canal.c:796
#9  0x00007ffff6cdc963 in r_core_anal_fcn (core=0x7ffff5d22010, at=256, from=18446744073709551615, reftype=0, depth=63)
    at canal.c:2004
#10 0x00007ffff6ce4105 in r_core_anal_all (core=0x7ffff5d22010) at canal.c:4077
#11 0x00007ffff6c17590 in cmd_anal_all (core=0x7ffff5d22010, input=0x555555675de2 "a") at cmd_anal.c:9128
#12 0x00007ffff6c1a805 in cmd_anal (data=0x7ffff5d22010, input=0x555555675de1 "aa") at cmd_anal.c:10099
#13 0x00007ffff6cd20f8 in r_cmd_call (cmd=0x5555555bdff0, input=0x555555675de0 "aaa") at cmd_api.c:291
#14 0x00007ffff6c6df25 in r_core_cmd_subst_i (core=0x7ffff5d22010, cmd=0x555555675de0 "aaa", colon=0x0, 
    tmpseek=0x7fffffffd9aa) at cmd.c:3772
#15 0x00007ffff6c69fa9 in r_core_cmd_subst (core=0x7ffff5d22010, cmd=0x555555675de0 "aaa") at cmd.c:2690
#16 0x00007ffff6c7c217 in run_cmd_depth (core=0x7ffff5d22010, cmd=0x555555674db0 "aaa") at cmd.c:6669
#17 0x00007ffff6c7c5c3 in r_core_cmd (core=0x7ffff5d22010, cstr=0x55555565e840 "aaa", log=1) at cmd.c:6745
#18 0x00007ffff6bb7a45 in r_core_prompt_exec (r=0x7ffff5d22010) at core.c:2995
#19 0x00007ffff6bb70c4 in r_core_prompt_loop (r=0x7ffff5d22010) at core.c:2846
#20 0x00007ffff7e46fcb in r_main_radare2 (argc=2, argv=0x7fffffffdf18) at radare2.c:1365
#21 0x00005555555554d2 in main (argc=2, argv=0x7fffffffdf18) at radare2.c:96
```

### PR DESCRIPTION
**Pull request by condret**
\

...

**Test plan**

* Get the file.gb from #17062 and commit it into testbins /fuzzed

**Closing issues**

https://github.com/radareorg/radare2/issues/17062

### CODE REVIEW

**Comment by trufae** [comment]
Can you add a test? can we distribuet that file.gb ? also. your fix will not crash, but will spit out warnings/assert. The issue must be handled somewhere else before reaching this point

**Comment by condret** [comment]
"If so, the right solution is to just put an if (BP) in r_anal_extract_vars for those extract_arg call that involve BP." - I disagree on that, the right point to check if bp exists, is in extract_arg, where it also checks if the AnalOp exists. The problem is in extract_arg and this solution fixes extract_arg

**Comment by ret2libc** [comment]
No, as @trufae said this is just going to spit out a lot of warning messages. It may be part of the solution, to avoid future segmentation faults, but it is not *the* solution. 

Also, `extract_arg` does not "checks if the AnalOp exists". It *assumes* `anal && fcn && op` is always true. If you are passing some NULL there, you are doing something wrong. But the code should not rely on those checks to avoid the NULL dereference. Those `r_return_if_fail`  are like `assert`.

**Comment by condret** [comment]
I'd still prefere adding a check in extract_arg, mostly to prevent future segfault as the codebase grows... I think we can have 2 checks here

**Comment by condret** [comment]
added another check, that doesn't use r_return_if_fail

**Comment by condret** [comment]
This still produces a bunch of warnings, but that's probably more related to the fact that in many gb-roms there is no calling convention as they're often hand-written asm afaik

**Comment by ret2libc** [comment]
I guess you are referring to:
```
WARNING: r_anal_cc_arg: assertion 'anal && convention' failed (line 103)                                                                                      
WARNING: r_anal_cc_arg: assertion 'anal && convention' failed (line 103)                                                                                      
WARNING: r_anal_cc_arg: assertion 'anal && convention' failed (line 103)                                                                                      
WARNING: r_anal_cc_arg: assertion 'anal && convention' failed (line 103)                                                                                      
WARNING: r_anal_cc_arg: assertion 'anal && convention' failed (line 103)                                                                                      
WARNING: r_anal_cc_arg: assertion 'anal && convention' failed (line 103)                                                                                      
WARNING: r_anal_cc_arg: assertion 'anal && convention' failed (line 103)                                                                                      
WARNING: r_anal_cc_arg: assertion 'anal && convention' failed (line 103)                                                                                      
WARNING: r_anal_cc_arg: assertion 'anal && convention' failed (line 103)                                                                                      
WARNING: r_anal_cc_arg: assertion 'anal && convention' failed (line 103)                                                                                      
WARNING: r_anal_cc_arg: assertion 'anal && convention' failed (line 103)                                                                                      
WARNING: r_anal_cc_arg: assertion 'anal && convention' failed (line 103)                                                                                      
[x] Analyze function calls (aac)                                               
```

BTW, with ASAN on that bin I see (with your fix, though it isn't the culprit):
```
[=================================================================                                                                                            
==1320272==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6250002a00a0 at pc 0x7fdbeace9c93 bp 0x7ffeea7d4db0 sp 0x7ffeea7d4da0                                                                                                                                                                                  
READ of size 1 at 0x6250002a00a0 thread T0                                     
    #0 0x7fdbeace9c92 in gb_anop ../libr/anal/p/anal_gb.c:821                                                                                                 
    #1 0x7fdbeac50dbb in r_anal_op ../libr/anal/op.c:107                                                                                                      
    #2 0x7fdbebabed43 in r_core_anal_search_xrefs ../libr/core/canal.c:3967                                                                                   
    #3 0x7fdbebbd46fe in r_core_anal_refs ../libr/core/cmd_anal.c:8617                                                                                        
    #4 0x7fdbebbd8bc0 in cmd_anal_all ../libr/core/cmd_anal.c:9194                                                                                            
    #5 0x7fdbebbde8a1 in cmd_anal ../libr/core/cmd_anal.c:10102                                                                                               
    #6 0x7fdbebcacd15 in r_cmd_call_parsed_args ../libr/core/cmd_api.c:347                                                                                    
    #7 0x7fdbebc8e93c in handle_ts_arged_command_internal ../libr/core/cmd.c:5000                                                                             
    #8 0x7fdbebc8e0c8 in handle_ts_arged_command ../libr/core/cmd.c:4959                                                                                      
    #9 0x7fdbebca3d69 in handle_ts_command ../libr/core/cmd.c:6496                                                                                            
    #10 0x7fdbebca47ec in handle_ts_commands_internal ../libr/core/cmd.c:6551                                                                                 
    #11 0x7fdbebca40b3 in handle_ts_commands ../libr/core/cmd.c:6516                                                                                          
    #12 0x7fdbebca5317 in core_cmd_tsr2cmd ../libr/core/cmd.c:6642                                                                                            
    #13 0x7fdbebca57da in r_core_cmd ../libr/core/cmd.c:6685                                                                                                  
    #14 0x7fdbebca6731 in r_core_cmd0 ../libr/core/cmd.c:6892                                                                                                 
    #15 0x7fdbede75f55 in r_main_radare2 ../libr/main/radare2.c:1297                                                                                          
    #16 0x401522 in main ../binr/radare2/radare2.c:96                                                                                                         
    #17 0x7fdbedcaa1a2 in __libc_start_main (/lib64/libc.so.6+0x271a2)                                                                                        
    #18 0x40115d in _start (/home/rschiron/.local/bin/radare2+0x40115d)                                                                                       

0x6250002a00a0 is located 0 bytes to the right of 8096-byte region [0x62500029e100,0x6250002a00a0)                                                                                                                                                                                                                           
allocated by thread T0 here:                                                   
    #0 0x7fdbee2c3d18 in __interceptor_malloc (/lib64/libasan.so.5+0x10dd18)                                                                                  
    #1 0x7fdbebabea03 in r_core_anal_search_xrefs ../libr/core/canal.c:3934                                                                                   
    #2 0x7fdbebbd46fe in r_core_anal_refs ../libr/core/cmd_anal.c:8617                                                                                        
    #3 0x7fdbebbd8bc0 in cmd_anal_all ../libr/core/cmd_anal.c:9194                                                                                            
    #4 0x7fdbebbde8a1 in cmd_anal ../libr/core/cmd_anal.c:10102                                                                                               
    #5 0x7fdbebcacd15 in r_cmd_call_parsed_args ../libr/core/cmd_api.c:347                                                                                    
    #6 0x7fdbebc8e93c in handle_ts_arged_command_internal ../libr/core/cmd.c:5000                                                                             
    #7 0x7fdbebc8e0c8 in handle_ts_arged_command ../libr/core/cmd.c:4959                                                                                      
    #8 0x7fdbebca3d69 in handle_ts_command ../libr/core/cmd.c:6496                                                                                            
    #9 0x7fdbebca47ec in handle_ts_commands_internal ../libr/core/cmd.c:6551                                                                                  
    #10 0x7fdbebca40b3 in handle_ts_commands ../libr/core/cmd.c:6516                                                                                          
    #11 0x7fdbebca5317 in core_cmd_tsr2cmd ../libr/core/cmd.c:6642                                                                                            
    #12 0x7fdbebca57da in r_core_cmd ../libr/core/cmd.c:6685                                                                                                  
    #13 0x7fdbebca6731 in r_core_cmd0 ../libr/core/cmd.c:6892                                                                                                 
    #14 0x7fdbede75f55 in r_main_radare2 ../libr/main/radare2.c:1297                                                                                          
    #15 0x401522 in main ../binr/radare2/radare2.c:96                                                                                                         
    #16 0x7fdbedcaa1a2 in __libc_start_main (/lib64/libc.so.6+0x271a2)                                                                                        
```

**Comment by condret** [comment]
wat, wait

**Comment by condret** [comment]
ok, I looked into this. ... It's a different bug, unrelated to this one. I will fix in a different pr, after merging this one

**Pull request merged**
