### PR TITLE
WIP: Add jumptable support for main() in bins/elf/ls.odd

### PR DESCRIPTION
**Pull request by kazarmy**
https://github.com/radareorg/radare2-regressions/commit/ff5127a694eaf21ca382612d4155c9008db27eca
For https://github.com/radareorg/radare2/pull/15208#issuecomment-539059124.

### CODE REVIEW

**Comment by radare** [comment]
```
[35m-0x1000011b5 switch table (72 cases) at 0x10000192c[39m
[35m[39m[32m+0x1000011b5 switch table (2 cases) at 0x10000192c[39m
```

**Comment by radare** [comment]
Touching this anal loop for adding support for more jumptables is a bit tricky. let me know if you want me to have a look or you are blocked

**Comment by kazarmy** [comment]
Haven't had a chance to look into this in the past 2 days ... the weekend is coming up though.

**Comment by radare** [comment]
yay

**Comment by kazarmy** [comment]
> ```
> [35m-0x1000011b5 switch table (72 cases) at 0x10000192c[39m
> [35m[39m[32m+0x1000011b5 switch table (2 cases) at 0x10000192c[39m
> ```
> 

```
> afb
...
0x1000011a2 0x1000011b7 00:0000 21 s 0x1000011b7 s 0x10000116e s 0x1000011d6 s 0x1000013c4 s 0x1000011e5 s 0x1000011fe s 0x100001217 s 0x100001233 s 0x100001253 s 0x100001284 s 0x100001494 s 0x1000012b6 s 0x1000012c9 s 0x1000012d8 s 0x1000012ea s 0x1000012fc s 0x100001315 s 0x1000013c0 s 0x100001327 s 0x10000134d s 0x100001373 s 0x100001389 s 0x10000139b s 0x1000013d3 s 0x1000013fd s 0x10000140f s 0x100001176 s 0x10000147b s 0x100001421 s 0x100001430 s 0x10000145a s 0x1000014a6 s 0x1000014c2 s 0x1000014ce s 0x1000014e0 s 0x1000014f2 s 0x100001504 s 0x10000152a s 0x10000153c s 0x100001562
...
```

seems to be just a comment problem

**Comment by kazarmy** [comment]
ok to merge?

i suppose one day will need to properly walk the bb graph to get the correct cmp

**Comment by kazarmy** [comment]
the risk of getting a wrong cmp seems pretty darn high at the moment

**Comment by radare** [comment]
That is going yo be fixed in my anal-block pr

**Comment by kazarmy** [comment]
> the risk of getting a wrong cmp seems pretty darn high at the moment

... but after rechecking, this might be misplaced pessimism

**Pull request merged**
