### PR TITLE
Fix #15604: Convert all tests from <<KEYWORD to <<EOF

### LINKED ISSUE #15604: Kill all the <<RUN
```
$ git grep '<<RUN'|wc -l
     796
```

### PR DESCRIPTION
**Pull request by kazarmy**
Done using `--to-eof` by radare/node-r2r#12 with some custom modifications needed for the `notworking_db/` tests.

### CODE REVIEW

**Comment by XVilka** [comment]
Please rebase.

**Comment by radare** [comment]
Check also the ones containing =‘

**Comment by kazarmy** [comment]
> Please rebase.

Done.

> Check also the ones containing =‘

Better merge this one first and soon, since I don't think fixing merge conflicts while half asleep is a good idea.

**Comment by radare** [comment]
yep. for another pr

**Pull request merged**
