### PR TITLE
Fix #15004: Make meta.min rbtree more robust

### LINKED ISSUE #15004: Hang in aac
Via @Zurich1994

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | OSX/linux
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.8.0 23022 @ darwin-x86-64 git.3.8.0-40-g2ad9a6bdc / commit: 2ad9a6bdcc5f887df4075d914962c8dbbc0c6699 build: 2019-09-10__09:46:30

### Expected behavior

Analysis goes on. (864K binary)

### Actual behavior

Analysis stall.

### Steps to reproduce the behavior 
- Please share the binary if it is shareable by drag and dropping it here in a zip archive [32c5ab8d02636e2316fa6fc04d492a8678f00d628ae7544a634ff8956727ff5c.zip](https://github.com/radare/radare2/files/3594387/32c5ab8d02636e2316fa6fc04d492a8678f00d628ae7544a634ff8956727ff5c.zip)

### PR DESCRIPTION
**Pull request by kazarmy**

### CODE REVIEW

**Comment by radare** [comment]
analysis differs in 2 tests, can you confirm its a regression or update the tests in case new results are better?

**Comment by kazarmy** [comment]
the xx for the "aav find xrefs" test appears to be a regression

**Comment by kazarmy** [comment]
Regarding the `bins/elf/ls.odd` binary used in the "x86_64 getenv this maybe" test, this pr doesn't fix the `aaa` analysis quality of `main` (in which analysis apparently thinks that `fcn.00015960` will not return, ever), but a `pdr` at `0x4901` shows fcnlines consistently so I'm going to consider this pr an improvement.

**Comment by radare** [comment]
awesome

**Pull request merged**
