### PR TITLE
meson install: Create shortcut/symlink to radare2

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [X] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

This pr recreates r2.bat on Windows under Meson that went missing, probably after #17424. Also enables the r2 tests, and creates a symlink to radare2 on non-Windows Meson.

**Test plan**

All builds should be green.

**Closing issues**

...

### CODE REVIEW

**Comment by XVilka** [comment]
[Breaks linux-meson-newshell](https://github.com/radareorg/radare2/pull/17463/checks?check_run_id=981158583#step:13:66):
```
[XX] db/tools/r2 r2 -L
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'e cfg.newshell=false
?q `!!r2 -L~default?`
?+ ?vi $?
?! ?e `!!r2.bat -L~default?`
' -
-- stdout
@@ -1 +1 @@
-1
+0

-- stderr
sh: 1: r2: not found
sh: 1: r2.bat: not found
```

**Comment by trufae** [comment]
sh: 1: r2.bat.covid19: not found

**Comment by kazarmy** [comment]
> Breaks linux-meson-newshell:

I think the reason is that meson's r2 shell script went missing as well

**Comment by kazarmy** [comment]
... or was never there in the first place

**Comment by kazarmy** [comment]
Description updated. The newshell incompatibility should be fixed in a later pr (things become strange at the edges of r2land).

**Comment by ret2libc** [comment]
@kazarmy you can use log.level=1 to get some more info if something is wrong with cfg.newshell

**Comment by ret2libc** [comment]
If you won't work on that in the short time, please file an issue and assign that to me so I can have a look next week

**Comment by karliss** [comment]
Assuming the purpose of most of those tests is testing r2 command line flags not the r2 symlink or r2.bat couldn't they use the long executable name `radare2`?  Wouldn't that solve the naming difference between Windows and other platforms?

**Comment by kazarmy** [comment]
> Assuming the purpose of most of those tests is testing r2 command line flags not the r2 symlink or r2.bat couldn't they use the long executable name radare2? Wouldn't that solve the naming difference between Windows and other platforms?

Yes they could use `radare2` but now they are currently doing double duty. This is not ideal ofc, 1 reason being that a test could be modified without the modifier being aware of what duties the test is currently performing, but I don't think it's likely that:

1. The tests will be modified.
2. `r2.bat` will go missing again.

**Comment by kazarmy** [comment]
> If you won't work on that in the short time, please file an issue and assign that to me so I can have a look next week

Ok I'll file the issues after #17488 goes through

**Comment by kazarmy** [comment]
@ret2libc All yours #17494 #17495 

Regarding the commands, they could be buggy in the old parser as well and they certainly have the feel of being well off the beaten path, but then I needed only one working combination for the tests.

**Pull request merged**
