### PR TITLE
Do not write nops in the cache ##io

### PR DESCRIPTION
**Pull request by trufae**
**Checklist**

- [ ] Closing issues: #issue
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [radare2book](https://github.com/radareorg/radare2book)

**Description**

### CODE REVIEW

**Comment by trufae** [comment]
@condret what do you think about this? the idea is that some writes shouldnt probably happen if the contents in memory are the same, maybe this behaviour should be enabled/disabled during loading time, because under esil emulation we need to track all the writes even if they are the same. but for patching relocs we can simplify that quite a lot

**Comment by condret** [comment]
hm, for user this makes perfectly sense, and sometimes even for esil, if you want to extract a diff

**Comment by trufae** [comment]
Yeah but maybe we need a toggle to pick the behaviour instead of forcing one mode or the other

**Comment by condret** [comment]
but the only usecase for tracking all writes is memory mapped hardware

**Comment by condret** [comment]
I think we can pretty much force mode for userland and support different modes in APIland

**Pull request merged**
