### PR TITLE
Use rpvector for storing esil pc trace

### PR DESCRIPTION
**Pull request by pelijah**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

The main idea here is to use RPVector for storing some parts of esil trace instead of sdb since they anyway are accessed by index.
Also by using that vector as cache for RAnalOp objects we can improve speed of type analysis (`aaft`). But I don't know how it can affect the esil emulaton. Also these changes breaks some commands for quering trace db.

Analysis time (`aaa`) of a 18MB binary: 3m10s vs 2m25s (master vs current branch).

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by pelijah** [comment]
Well caching should be optional. In that case it would be better to use RVector of `ut64 + RAnalOp*`. But there are other trace entries which are accessed by index. So eventually this will require more complicated struct.

**Comment by radare** [comment]
please provide performance proof of this change.

btw, we should start to think about having test/bench to run on every commit and graph the performance gains/loss over time

**Comment by pelijah** [comment]
> please provide performance proof of this change.

Existing one is not enough? Any specific binary?

**Comment by thestr4ng3r** [comment]
Any specific binary with concrete commands and maybe a graph from a profiler would be nice.

**Comment by pelijah** [comment]
`time radare2 -Q -qq -A /usr/bin/snap`

_master_: 65.6s
_current_: 59.4s

**Comment by pelijah** [comment]
`radare2 -qq -c "aa;aac;aar;?t aaft" /usr/bin/snap`

_master_: 41.4s
_current_: 34.7s

**Comment by radare** [comment]
Is this affecting aae too? Which other aa subcommands make use of this?

Can you rebase to make it green?

Goo work!

**Comment by pelijah** [comment]
It fails 1 test.

**Comment by radare** [comment]
Why close

**Comment by pelijah** [comment]
Well I have found that it is not really possible to store trace events info in a vector. So I see no reason to continue work on this PR. And caching can be done in other way. I will try to do implement it later.

**Comment by radare** [comment]
ok :)

**Pull request closed without merging**
