### PR TITLE
WIP: Initial attempt to setup windows ci on github actions

### PR DESCRIPTION
**Pull request by trufae**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

Right now we use appveyour for Windows CI, let's try github actions

**Test plan**

this pr is still very wip, but it should run the testsuite

**Closing issues**

lets see if its faster than appveyour

### CODE REVIEW

**Comment by XVilka** [comment]
Any particular reason why AppVeyor is not fine as is?

**Comment by condret** [comment]
@XVilka me waiting for AppVeyor to finish: waiting .

Alternatively I'd suggest getting rid of digital bureaucracy stack, that is implemented here

**Comment by trufae** [comment]
@ret2libc you have self assigned to this PR, do this means that you'll be commiting and finishing it? I'm mainly interested in speeding up the windows builds, just curious if gha runs faster than apv also on windows (being owned by microsoft .. it should)

**Comment by ret2libc** [comment]
> @ret2libc you have self assigned to this PR, do this means that you'll be commiting and finishing it? I'm mainly interested in speeding up the windows builds, just curious if gha runs faster than apv also on windows (being owned by microsoft .. it should)

Nope, just that I want to review and merge it and keeping an eye on it.

**Comment by XVilka** [comment]
@condret we have 4 parallel AppVeyor jobs, I doubt GitHub Actions will be significantly faster. This one is the real bottleneck: https://github.com/radareorg/radare2/issues/16729

**Comment by XVilka** [comment]
Because we used Travis free, and AppVeyor is a paid instance with 4 parallel jobs:
image
And I pointed already the culrpit of the slow jobs - not the CI performance, but the general slowness of `r2r` on Windows. I am not against faster builds, just think it might not give you results you expect.

**Comment by XVilka** [comment]
Please also add a `clang-cl` job, it's vital for the modern world, since Google Chrome and Mozilla Firefox both use it by default: https://ci.appveyor.com/project/radareorg/radare2/builds/33446196/job/bg0lmyffrnf9x6yk
Also please a job for VS2017 if you plan to substitute AppVeyor completely.

**Comment by trufae** [comment]
22s for a hello world :D

Screenshot 2020-06-11 at 01 02 55

Build with 2019 is 8min in release mode

**Comment by XVilka** [comment]
Just a build on AppVeyor (plus also packaging the installer) is 7-10 minutes as well: https://ci.appveyor.com/project/radareorg/radare2/builds/33452374
It's tests that taking 40 min to complete.

**Comment by trufae** [comment]
Yeah seems like compilation times dont vary that much comparing gha and apv, the benefits i see in moving to gha:

* Same place to do all the builds and deploy the bins
* Unified scripts for building across all platforms
* Avoid having to pay comercial services when we have the same for free

if you dont think any of the reasons stated above make sense i'll just close the PR, i'm not mainintaining anything related to Windows and this was just a test to compare.

**Comment by trufae** [comment]
Also if we want faster builds we should run the tests with the static build of r2.

loading all the DLLs takes so much time compared to just loading a big executable. but obv this is not the bottleneck. the real problem is the one you spotted

**Comment by ret2libc** [comment]
I'm ok with having tests on GH if they tests the same thing as appveyor. I think we wanted to do that anyway.

**Comment by XVilka** [comment]
Don't be take me wrong, I am fine with GitHub Actions as well,so I won't
need to spend $100/month, just want to make sure it will have exactly the
same features and testing stuffs.

**Comment by trufae** [comment]
@XVilka feel free to contribute to this PR, as long as i dont have much time and i've never maintained anything related to windows you'll probably have more motivation than me to get it setup

**Comment by trufae** [comment]
@XVilka @ret2libc all yours

**Comment by ret2libc** [comment]
Yes I'm on this, let's close this for now!

**Pull request closed without merging**
