### PR TITLE
Remove inferior GNU Hexagon plugin

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

No need to have two Hexagon plugins in the repository. Plus, radare2's own (generated from [r2hexagon](https://github.com/radareorg/r2hexagon)) plugin supports more instructions and has corresponding analysis plugin while the GNU one - hasn't.

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by radare** [comment]
calling it inferior is offensive and humiliating. you should wash your hands with soap after writing this. mainly for the covid.

can you make a pr in r2-extras adding this code there? the plugin works and the binutils part is maintained by GNU. so better not kill it

**Comment by XVilka** [comment]
OK. I even took shower, washing hands wasn't enough,

**Comment by radare** [comment]
they were not even referenced from t¡he plugins.cfg :(

**Comment by radare** [comment]
Open a PR in radare2-extras moving this plugin there

**Comment by radare** [comment]
tired of waiting. i did the move here https://github.com/radareorg/radare2-extras/commit/a015f9fe7e3eded806f95c425a06dddde0ed219e

**Pull request merged**
