### PR TITLE
Integrate ABI diffing into CI scripts

### PR DESCRIPTION
**Pull request by MewtR**
- [x] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

My attempt at addressing #21055. I essentially added a new job to the CI that compares the ABI of the latest release to the one currently being built. Let me know what you think.

### CODE REVIEW

**Comment by trufae** [comment]
That's beautiful and I didn't expect it, which makes it even more beautiful.

Will be good to know exactly what this tool considers "ABI" because for us is fine to change internal structs and such.. can you enable the job for PRs too?

**Comment by MewtR** [comment]
Thanks
Is it alright if I remove the condition on the `linux-static` job? The new one depends on it (that's the reason why it's getting skipped).

> Will be good to know exactly what this tool considers "ABI"

Good point. You can check by running something like `abidw libr_main.so --out-file libr_main.abi`
The major problem I see right now is that it considers some external dependencies as part of the ABI. Stuff from libc for example. In theory, it should be possible to ignore these through a [suppression file like this one](https://github.com/endlessm/freedesktop-sdk/blob/3bfc8a401096a4a0a660a7276a8ceae734aac79e/utils/abidiff-suppressions.ini) but I haven't been able to get it to work properly yet.

Can you give an example of something that should be changeable triggering an abi incompatibility?

**Comment by trufae** [comment]
Check the `doc/abi.md` file for some examples of what we consider abi breaking changes.

Try adding a new field inside the `RCore` struct in `libr/include/r_core.h` for example.

**Comment by MewtR** [comment]
Yeah so doing that does seem to have caused [the job to fail](https://github.com/MewtR/radare2/actions/runs/3803767928/jobs/6470450590)...
I'll try to look further into the suppression options to see what can be done.

**Comment by trufae** [comment]
Amazing, thanks for confirming it works as expected. Let me know when it's ready to merge (i think it's fine already for me)

**Comment by MewtR** [comment]
Really? In that case, I suggest we merge. If it generates too many false positives it can be disabled/reworked. But yeah it'd be cool to see it in action.

**Comment by trufae** [comment]
Let's merge then! We can play and tweak it later if needed :) thank you!

**Comment by trufae** [comment]
Can you check this failing log? https://github.com/radareorg/radare2/actions/runs/3855015379/jobs/6574474060

Its from the last open pr

**Comment by MewtR** [comment]
Only reason I can think of for why the curl command would fail is that we're being [rate-limited by Github's API](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limiting).
According to the doc, there's a way to bump our requests per hour to 1000 (as opposed to 60)
I'll look into it.

**Pull request merged**
