### PR TITLE
Multiple refactors in io and util ##io ##util ##refactor

### PR DESCRIPTION
**Pull request by Lazula**
* Add r_io_map macros throughout code base.
* Update string NULL-checking with renamed functions r_str_get() and r_str_getf()
* Change string NULL-checks throughout code base to use functions
* Add r_str_get_fail() to specify a custom string to return if NULL-check fails
* Mark JSON to be updated with PJ with "TODO PJ"
* Incidental style updates such as missing spaces

### CODE REVIEW

**Review by trufae — APPROVED** [review]

**Comment by trufae** [comment]
See the failing test, can you repro in local?

**Comment by condret** [comment]
@trufae I got the same test failing befor I reabsed ... I doubt it's related to their pr

**Comment by Lazula** [comment]
> @trufae I got the same test failing befor I reabsed ... I doubt it's related to their pr

cmd_project.c is also untouched in my commit
Screenshot_20201212-184352_JuiceSSH

**Comment by condret** [comment]
@Lazula in theory it could be related somhow, when r_io falls, almost everything in r2 falls with it ... but then we'd see more failing tests

**Comment by Lazula** [comment]
@trufae Tests are all green locally. I don't think its related to my changes.

**Comment by trufae** [comment]
Please rebase your PR on top of master just to confirm and re-run the ci.

**Pull request merged**
