### PR TITLE
Fix #16413 - Analyze code refs spotted with aae ##anal

### LINKED ISSUE #16413: Radare2 doesn't detect all functions for ELF-MIPS malware sample
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | ELF 
| Architecture/bits of the file (mandatory)            | MIPS
|$ r2 Mozi_unpacked.bin 

[0x00400260]> aaa

[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for objc references
[x] Check for vtables
[x] Finding xrefs in noncode section with anal.in=io.maps
[x] Analyze value pointers (aav)
[x] Value from 0x00400000 to 0x00437680 (aav)
[x] 0x00400000-0x00437680 in 0x400000-0x437680 (aav)
[x] Emulate code to find computed references (aae)
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.

[0x00400260]> afl
0x00400260    2 100          entry0
0x004000b8    1 104          fcn.004000b8
0x0042c924    1 56           fcn.0042c924
0x00428384   16 976  -> 332  fcn.00428384
0x00431314    1 32           fcn.00431314

### Expected behavior
Ida produces about 750 functions so I'd assume the same amount should be produced in radare2
### Actual behavior
5 Functions are produced 
### Steps to reproduce the behavior 
Download attached zip file and analyze file mozi_unpacked.bin. 
$ r2 Mozi_unpacked.bin
[0x00400260]> aaa
[0x00400260]> afl

### PR DESCRIPTION
**Pull request by radare**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

run af on each UJMP/UCALL spotted when doing esil emulation to find out the register value

**Test plan**

see the test

**Closing issues**

fixes #16423

### CODE REVIEW

**Comment by radare** [comment]
this pr would improve arm and mips analysis

**Comment by thestr4ng3r** [comment]
> this pr would improve arm and mips analysis

Please put that in the description instead of an empty template

**Comment by radare** [comment]
if it wasnt obvious, its now filled and green. please review

**Comment by thestr4ng3r** [comment]
It is obvious, but an empty template is just spam.

**Comment by radare** [comment]
This change may lead to some issues with jumptables, but as long as the testsuite spotted no issues at all i assume its fine. And actually i have many more plans to improve aae. We have one week of testing if we can merge it now

**Pull request merged**
