### PR TITLE
r2pm: Allow package script to declare cleaning is done

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

This pr allows r2pm package scripts to do their own cleaning of their git dir.

**Test plan**

Add the following to the r2dec package script before R2PM_END:

```sh
if [ "$ACTION" = clean ]; then
	rm -rf "${R2PM_GITDIR}/r2dec-js"
	DONE=1
fi
```

and then run `r2pm -ci r2dec`. There should be no error message stating that the r2dec git dir cannot be found.

This is currently necessary for cleaning because the git dirname (`r2dec-js`) is hardcoded in the r2dec source.

**Closing issues**

...

### CODE REVIEW

**Comment by trufae** [comment]
What about returning a value and checking for error code instead of using the arbitrary DONE var that doesnt seems to specify anything related to cleaning or r2pm? Reading the pkg script doesnt makes it clear what the DONE var will do

**Comment by kazarmy** [comment]
Checking the return value can be done (b69d59393fd6fcb62963bfca3a7dd7713cf0898c with
```sh
if [ "$ACTION" = clean ]; then
	rm -rf "${R2PM_GITDIR}/r2dec-js"
	R2PM_END
	return 1
fi
```
) but is somewhat awkward (also, the `echo` in R2PM_END is not guaranteed to return 0) and I think renaming the DONE var to perhaps CLEAN_GITDIR is better.

**Comment by trufae** [comment]
Yes. Using a meaningful var is more readable. Maybe starting it with R2PM_ for consistency like all the other r2pm functions

**Comment by kazarmy** [comment]
> Yes. Using a meaningful var is more readable. Maybe starting it with R2PM_ for consistency like all the other r2pm functions

Ok bbc1bafedeaf7afc1ff8f1dca1c6cc1ab902e4d9 (and

```sh
if [ "$ACTION" = clean ]; then
	rm -rf "${R2PM_GITDIR}/r2dec-js"
	R2PM_CLEAN_GITDIR=0
fi
```
)

**Pull request merged**
