### PR TITLE
Fix a bug of clicking

### PR DESCRIPTION
**Pull request by Vane11ope**
Clicking does not properly work in panels and now this fixes it.

### CODE REVIEW

**Comment by radare** [comment]
let me test on mac before merging. thanks! what was the bug about?

**Comment by ITAYC0HEN** [comment]
> what was the bug about?

@Vane11ope try following the PR template next time, it's there for a good reason :)
It'd help us understand the issue and the solution. Also, the test case to review the PR

**Comment by radare** [comment]
@Vane11ope ping?

**Comment by radare** [comment]
just tested this on mac, and this PR basically makes the mouse not to work on mac at all, so i wont merge this. we need to clarify what is the bug in linux and we can temporarily aadd this option for non mac builds, but this is aa hack because mac users can ssh into linux machines and be unable to use the mouse obecause of this ifdef hack.

**Comment by Vane11ope** [comment]
hang on Im taking this back then. the problem is, the mouse does not properly click on the menu in linux and this fixes it. but since mac does not work with this then let me take this back

**Pull request closed without merging**
