### PR TITLE
Add initial function prelude support for v850 ##anal

### PR DESCRIPTION
**Pull request by trufae**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by XVilka** [comment]
Something like this should come with test, imho.

**Comment by trufae** [comment]
Yes, the problem is that we have no distributable v850 binary. the one that is in the testsuite is actually for v810, and our v850 disassembler is for v800, r2ghidra/v850 is the only able to handle that disasm/analytsis properly right now. ill try to get a toolchain to generate proper code for that. i can cook something by hand too, but i would prefer to get the right toolchains working first. From what ive seen < v850 there are no actual function preludes. and alignment is important, so those archs need more metainfo in the asm plugins too.

**Comment by trufae** [comment]
Yay i found the way to get proper prepare/dispose functions with the toolchain. I have commited a bin in tests and will add some tests and more preludes.

I am also fixing the v850 disassembler and analyzer to support the last instructions in the newest E models.

**Review by XVilka — APPROVED** [review]

**Comment by trufae** [comment]
rebased after the -Werror, lets hope its green too :)

**Pull request merged**
