### PR TITLE
CBM Basic Support

### PR DESCRIPTION
**Pull request by thestr4ng3r**

### CODE REVIEW

**Comment by XVilka** [comment]
Please rebase.

**Comment by radare** [comment]
Lgtm but the thing is.. why not in extras?

**Comment by thestr4ng3r** [comment]
More like, why in extras?

**Comment by radare** [comment]
i dont think there's much need on having CBM support by the 99% of the r2 users. so we probably dont want to ship in the default installation because its making builds slower and bigger (not a lot, but a bit)

**Comment by thestr4ng3r** [comment]
Will be moved to another repo + r2pm package

**Comment by thestr4ng3r** [comment]
Code moved here: https://github.com/thestr4ng3r/r2commodore

**Pull request closed without merging**
