### PR TITLE
Update to the latest quickjs-ng, so we dont need to ship custom patches

### PR DESCRIPTION
**Pull request by satk0**
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

### CODE REVIEW

**Comment by trufae** [comment]
it is now ready to merge? all r2 patches are now pushed upstream?

**Comment by satk0** [comment]
No, need to make a pr for that, give me a moment

**Comment by satk0** [comment]
https://github.com/quickjs-ng/quickjs/pull/592

**Comment by satk0** [comment]
:pray:

**Pull request merged**
