### PR TITLE
Build LinuxMeson with -O2

### PR DESCRIPTION
**Pull request by radare**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by radare** [comment]
we still need to know why meson builds are that slow

**Comment by radare** [comment]
@ret2libc can u open a PR with just build+install with meson to compare build times instead of running the whole suite? maybe the bottleneck is there

**Comment by ret2libc** [comment]
As said, meson build uses COVERAGE=1, so there are additional instrumentation points and reports being done and uploaded when running meson. So I don't think 17min of meson vs 14min of gcc build is that much of a problem.

**Comment by radare** [comment]
ok, then it will be good to rename the job to say something about coverage

**Pull request closed without merging**
