### PR TITLE
Fix R2_INCDIR on Windows

### PR DESCRIPTION
**Pull request by GustavoLCR**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

### CODE REVIEW

**Comment by thestr4ng3r** [comment]
Could you please add some more info on what the change exactly does and why it is needed? I think it could affect building cutter with `-DCUTTER_USE_BUNDLED_RADARE2=ON`.

**Comment by karliss** [comment]
This might allow removing windows specific header handling code from BundledRadare2.cmake in Cutter.

**Comment by GustavoLCR** [comment]
Turns out there was a difference on where `meson install` and meson.py installed the headers on windows, now its they are the same

**Comment by XVilka** [comment]
I think it makes sense but need a confirmation from the Cutter team first.

**Comment by trufae** [comment]
Anyone can review this?

**Pull request merged**
