### PR TITLE
Improve map tying support ##io

### PR DESCRIPTION
**Pull request by condret**
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

### CODE REVIEW

**Comment by trufae** [comment]
guess lgtm, no complains

**Comment by trufae** [comment]
Do we want to have double tie? I mean maps should resize if fd changes.. but what if the map is resized? May this always change the underlying fd?

**Comment by trufae** [comment]
ok to merge? rebase to be green, the failing tests is unrelated

**Comment by condret** [comment]
i added another command 'omtf' to tie maps forward to the desc. 'omt' and 'omtb' do the same, as they tie the map backwards

**Pull request merged**
