### PR TITLE
Try newer V for OpenBSD fix

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by radare** [comment]
And the result is?

**Comment by XVilka** [comment]
Result is still bad:
```
git clone --depth 1 --quiet https://github.com/vlang/tccbin /var/tmp/tcc
gmake[3]: Leaving directory '/home/build/radare2/test/src/v'
cd /var/tmp/tcc && git clean -xf && git pull --quiet
clang  -std=gnu11 -w -o v /tmp/vc/v.c  -lm
./v self
V panic: V tool "/home/build/radare2/test/src/v/cmd/tools/vself.v" could not be compiled
Segmentation fault (core dumped)
print_backtrace_skipping_top_frames is not implemented on this platform for now...
```

**Comment by XVilka** [comment]
Now it's a problem in radare2.v package it seems:
```
v/v -prod r2r.v
r2r.v:10:9: cannot import module "filepath" (not found)
module "filepath" not found in ["/usr/home/build/radare2/test/src", "/usr/home/build/radare2/test/src/modules", "/usr/home/build/radare2/test/src/v/vlib", "/home/build/.vmodules"] 
    8| 	json
    9| 	flag
   10| 	filepath
             	 ^
   11| 	radare.r2
   12| )
gmake[1]: *** [Makefile:9: all] Error 1
```

**Comment by radare** [comment]
that wont work at all. wait for my PR to be merged

**Pull request closed without merging**
