### PR TITLE
WIP: Fix some out of bound accesses in LE

### PR DESCRIPTION
**Pull request by marcograss**
**Detailed description**

I found some more out of bound access in le.c, I tried to fix them but some additional problems arise, either the rabin2 don't terminate, or it crashes in other locations.

the original problem was the code trusting some informations from the binary, which are invalid

I might need some help to fix this, I attach the test case.

[rabin2_crash_new2.zip](https://github.com/radareorg/radare2/files/4176556/rabin2_crash_new2.zip)

**Test plan**

see the attached test case, it should run without problems

**Closing issues**

if someone else more experienced can help debug and fix it would be appreciated

### CODE REVIEW

**Comment by radare** [comment]
Still wip?

**Comment by marcograss** [comment]
I can't work on it, also if someone with more experience with r2 internals can run the testcase and see what is going on any help would be appreciated.

I fixed that particular out of bound but there might be other problems with this testcase

thanks

**Comment by radare** [comment]
Which test? Travis is green

**Comment by marcograss** [comment]
it's attached to the original PR message

rabin2 -g rabin2_crash_file

**Comment by radare** [comment]
so, ok to merge and continue fixing more issues later?

**Comment by radare** [comment]
ive fixed the rest of bugs you reported in another PR, merging this one for now even if im not fully happy about the changes, this code have a bunch of things that must be fixed too

**Pull request merged**
