### PR TITLE
Add 6 minutes to cmd_aae timeout and skip aaa for swift_read fuzz test

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

The pr is because:

1. The master asan build is still timing out on the cmd_aae test despite #17793.
2. I accidentally ran the asan+fuzz tests (probably because I used the pencil) and the following asan fuzz test is timing out (https://github.com/radareorg/radare2/runs/1274872621#step:15:20):

swift_read-fuzz

**Test plan**

All builds are green.

**Closing issues**

...

### CODE REVIEW

**Comment by trufae** [comment]
What about removing /replacing slow tests for something that runs fast even with asan? otherweise i think its preferibly to skip those tests in asan mode, such timeouts for a single test are not something good. 99% of the tests run in less than 2s, while 3 tests take 5min to run, we must squash those out, even if it's needed to test big binaries somehow, the tests should be more concrete

**Comment by kazarmy** [comment]
> otherweise i think its preferibly to skip those tests in asan mode

sgtm for the fuzz test 641b4635c7d7210db4a00298cca92030339a16b0 ... for the cmd_aae test i think we should give that larger timeout a chance, so that we don't lose asan coverage for that test

**Comment by kazarmy** [comment]
you're probably right though -- there's probably a combination of tests that individually normally pass their timeout thresholds yet in combination they take up enough time that when the server is under enough load, the build time goes past its timeout threshold ... squashing them would require time logging i think

**Comment by trufae** [comment]
i have already identified them a month ago, fixed 2 of them, then lost interest on everything and stopped doing that, but shuold be easy to spot by running in local, doubt i have noted which were those tests sorry

**Comment by kazarmy** [comment]
I think this pr should still be merged though. The problem with linux-meson-gcc-newshell-tests might be an artifact of having both "linux-meson-gcc-newshell-tests (push)" and "CI / linux-meson-gcc-newshell-tests (pull_request)", and the time of week. The asan+fuzz "linux-gcc-tests-asan (push)" build is running it close at 89 minutes but there's still another 10 minutes left.

**Comment by kazarmy** [comment]
Ok I've bumped the linux-meson-gcc-newshell-tests timeout to 60 minutes, same as the macos-clang-tests timeout.

**Review by XVilka — APPROVED** [review]

**Pull request merged**
