### PR TITLE
Automatically set prj.git if `git` is found in PATH ##projects

### PR DESCRIPTION
**Pull request by trufae**
**Checklist**

- [ ] Closing issues: #issue
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [radare2book](https://github.com/radareorg/radare2book)

**Description**

### CODE REVIEW

**Comment by RHL120** [comment]
I think you should check the ret val of system("git config --global user.name && git config --global user.email")

**Comment by trufae** [comment]
> I think you should check the ret val of system("git config --global user.name && git config --global user.email")

this is not related to this PR, but i think we should have git projects enabled by default for the users. but in the CI we should test projects with and without git support. Comments on this?

**Comment by trufae** [comment]
ping @RHL120

**Comment by trufae** [comment]
Let's merge this, so we can start to improve the git integration and avoid mistakes that make people loose data when saving a project.

**Pull request merged**
