### PR TITLE
Change default value inside struct dyn

### PR DESCRIPTION
**Pull request by 08A**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**
The error value (not found) inside `RBinElfDynamicInfo` was 0. The problem is that some value inside the dynamic section are 0 and it is VALID. So i change the default value.

PS: All size have a value of 0, imho an invalid size is 0 not a big value.

**Test plan**

...

**Closing issues**
#12732

### CODE REVIEW

**Comment by 08A** [comment]
@ret2libc Any opinion on this?

**Comment by 08A** [comment]
@ret2libc the appveyor has ended but you can see it if you don't clik on the link

**Comment by ret2libc** [comment]
> @ret2libc the appveyor has ended but you can't see it if you don't click on the link

I see... probably some issues with Github. Let's wait and see if it pass in a short time, otherwise @XVilka or @radare can merge it anyway.

**Comment by radare** [comment]
stil WIP? lgtm

**Comment by 08A** [comment]
Nope @radare  i forget to remove the flag

**Comment by ret2libc** [comment]
I restarted appveyor build which was stuck.

**Pull request merged**
