### PR TITLE
fix getopt seg fault

### PR DESCRIPTION
**Pull request by aar0nge**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

run radiff2 without arguments in r2 command line
image
image
 

**Closing issues**

closes https://github.com/radareorg/radare2/issues/16306

...

### CODE REVIEW

**Comment by radare** [comment]
this issue will happen in all theo ther programs using getopt. it's a bug in libc, but we may address it in our codebase to not depend on 3rd party bugs.

Can you update the PR to do the same with all the other main programs?

```
pmb:main pancake$ git grep getopt
r2agent.c:      while ((c = r_getopt (argc, argv, "adhup:t:sv")) != -1) {
rabin2.c:       while ((c = r_getopt (argc, argv, "DjgAf:F:a:B:G:b:cC:k:K:dD:Mm:n:N:@:isSVIHeEUlRwO:o:pPqQrTtvLhuxXzZ")) != -1) {
radare2.c:      while ((c = r_getopt (argc, argv, "=02AMCwxfF:H:hm:e:nk:NdqQs:p:b:B:a:Lui:I:l:P:R:r:c:D:vVSTzuX"
radiff2.c:      while ((o = r_getopt (argc, argv, "Aa:b:BCDe:npg:m:G:OijrhcdsS:uUvVxXt:zqZ")) != -1) {
rafind2.c:      while ((c = r_getopt (argc, argv, "a:ie:b:jmM:s:S:x:Xzf:t:E:rqnhvZ")) != -1) {
ragg2.c:        while ((c = r_getopt (argc, argv, "n:N:he:a:b:f:o:sxXrk:FOI:Li:c:p:P:B:C:vd:D:w:zq:S:")) != -1) {
rahash2.c:      while ((c = r_getopt (argc, argv, "p:jD:rveE:a:i:I:S:s:x:b:nBhf:t:kLqc:")) != -1) {
rasm2.c:        while ((c = r_getopt (argc, argv, "a:Ab:Bc:CdDeEf:F:hi:jk:l:L@:o:O:pqrs:vwx")) != -1) {
pmb:main pancake$
```

**Comment by XVilka** [comment]
There are good portable `getopt()` implementations with a suitable license, maybe just to reuse them?
- https://github.com/skeeto/getopt
- https://github.com/skeeto/optparse
Way more powerful than the current implementation.

**Comment by radare** [comment]
why did you closed the PR? you can just update it

**Comment by aar0nge** [comment]
I found that this way to fix may not be enough, and I am not sure about the proper way.

**Comment by radare** [comment]
https://github.com/radareorg/radare2/pull/16325

**Comment by radare** [comment]
i think my pr should fix the issue. check it out

**Pull request closed without merging**
