### PR TITLE
Capstone BPF ESIL ##esil

### PR DESCRIPTION
**Pull request by aemmitt-ns**
- [x] Mark this if you consider it ready to merge
- [x] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

Adds ESIL for nearly every BPF instuction. This should include both cBPF and eBPF, though capstone makes the distinction confusing so this will need more testing. Likely some of it still needs some work but overall it is nearly complete. thanks to @terorie, let me know if anything looks wrong 

```
┌ 96: fcn.00008000 ();
│           0x00008000      280000000c00.  ldh [0xc]                   ; 12,0,+,[2],a,= ; a=0xffff
│      ┌┌─< 0x00008008      15000005dd86.  jeq 0x86dd, +0x0, +0x5      ; 34525,a,==,$z,?{,32784,}{,32824,},pc,= ; pc=0x8038 -> 0x3000015 ; likely
│      └──> 0x00008010      300000001400.  ldb [0x14]                  ; 20,0,+,[1],a,= ; a=0xff
│      ┌──< 0x00008018      150006000600.  jeq 0x6, +0x6, +0x0         ; 6,a,==,$z,?{,32848,}{,32800,},pc,= ; pc=0x8020 -> 0x6000015 ; likely
│    ┌┌───< 0x00008020      150000062c00.  jeq 0x2c, +0x0, +0x6        ; 44,a,==,$z,?{,32808,}{,32856,},pc,= ; pc=0x8058 -> 0x6 ; likely
│    └────> 0x00008028      300000003600.  ldb [0x36]                  ; 54,0,+,[1],a,= ; a=0xff
│   ┌┌────< 0x00008030      150003040600.  jeq 0x6, +0x3, +0x4         ; 6,a,==,$z,?{,32848,}{,32856,},pc,= ; pc=0x8058 -> 0x6 ; likely
│ ┌┌────└─> 0x00008038      150000030008.  jeq 0x800, +0x0, +0x3       ; 2048,a,==,$z,?{,32832,}{,32856,},pc,= ; pc=0x8058 -> 0x6 ; likely
│ └───────> 0x00008040      300000001700.  ldb [0x17]                  ; 23,0,+,[1],a,= ; a=0xff
│ ┌─────┌─< 0x00008048      150000010600.  jeq 0x6, +0x0, +0x1         ; 6,a,==,$z,?{,32848,}{,32856,},pc,= ; pc=0x8058 -> 0x6 ; likely
│ └─└──└──> 0x00008050      060000000000.  ret 0x40000                 ; 262144,r0,=,8,sp,+=,sp,[8],pc,= ; r0=0x40000 ; sp=0x8 ; pc=0xffffffffffffffff
└  └─└└─└─> 0x00008058      060000000000.  ret 0x0                     ; 0,r0,=,8,sp,+=,sp,[8],pc,= ; r0=0x0 ; sp=0x10 ; pc=0xffffffffffffffff
```

```
┌ 152: sym.func ();
│           0x08000040      bf2300000000.  mov64 r3, r2                ; r2,r3,= ; [02] -r-x section size 152 named .text ; r3=0x0
│           0x08000048      bf1400000000.  mov64 r4, r1                ; r1,r4,= ; r4=0x0
│           0x08000050      631af8ff0000.  stxw [r10+0xfff8], r1       ; r1,65528,r10,+,=[4]
│           0x08000058      632af4ff0000.  stxw [r10+0xfff4], r2       ; r2,65524,r10,+,=[4]
│           0x08000060      61a1f8ff0000.  ldxw r1, [r10+0xfff8]       ; 65528,r10,+,[4],r1,= ; r1=0x0
│           0x08000068      61a2f4ff0000.  ldxw r2, [r10+0xfff4]       ; 65524,r10,+,[4],r2,= ; r2=0x0
│           0x08000070      070200001f00.  add64 r2, 0x1f              ; 31,r2,+= ; r2=0x1f
│           0x08000078      670200002000.  lsh64 r2, 0x20              ; 32,r2,<<= ; r2=0x1f00000000
│           0x08000080      770200002000.  rsh64 r2, 0x20              ; 32,r2,>>= ; r2=0x1f
│       ┌─< 0x08000088      5d2104000000.  jne r1, r2, +0x4            ; r2,r1,-,?{,134217904,pc,=,} ; pc=0x80000b0 -> 0x1b7 loc.LBB0_2 ; likely
│      ┌──< 0x08000090      050000000000.  jmp +0x0                    ; 134217880,pc,= ; pc=0x8000098 -> 0x1b7 loc.LBB0_1 ; loc.LBB0_1(0x0, -1, -1, -1)
│      ││   ;-- LBB0_1:
│      ││   ; CODE XREF from sym.func @ 0x8000090(x)
│      └──> 0x08000098      b70100000400.  mov64 r1, 0x4               ; 4,r1,= ; r1=0x4
│       │   0x080000a0      631afcff0000.  stxw [r10+0xfffc], r1       ; r1,65532,r10,+,=[4]
│      ┌──< 0x080000a8      050003000000.  jmp +0x3                    ; 134217928,pc,= ; pc=0x80000c8 -> 0xfffca061 loc.LBB0_3 ; loc.LBB0_3(0x4, -1, -1, -1)
│      ││   ;-- LBB0_2:
│      │└─> 0x080000b0      b70100000000.  mov64 r1, 0x0               ; 0,r1,= ; r1=0x0
│      │    0x080000b8      631afcff0000.  stxw [r10+0xfffc], r1       ; r1,65532,r10,+,=[4]
│      │┌─< 0x080000c0      050000000000.  jmp +0x0                    ; 134217928,pc,= ; pc=0x80000c8 -> 0xfffca061 loc.LBB0_3 ; loc.LBB0_3(0x0, -1, -1, -1)
│      ││   ;-- LBB0_3:
│      ││   ; CODE XREFS from sym.func @ 0x80000a8(x), 0x80000c0(x)
│      └└─> 0x080000c8      61a0fcff0000.  ldxw r0, [r10+0xfffc]       ; 65532,r10,+,[4],r0,= ; r0=0x0
└           0x080000d0      950000000000.  exit                        ; 8,sp,+=,sp,[8],pc,= ; sp=0x8 ; pc=0xffffffffffffffff
```

### CODE REVIEW

**Comment by trufae** [comment]
Screenshot 2022-06-05 at 17 34 36

**Comment by aemmitt-ns** [comment]
I need to fix the unsigned cjmp instructions before this is merged

**Comment by aemmitt-ns** [comment]
This is close to finished, just need to add a workaround for `lddw` which capstone gets wrong. ill also make a PR to capstone to fix. also @trufae I know you want to get rid of { <,>,<=,>= } but I would like to keep them for selfish reasons. For symbolic execution they create simpler and quickly solved ASTs. They also make expressions easier to read.

**Comment by trufae** [comment]
Those comparators are handy. It's mainly @condret who's planning to remove them. But with the abi/abi rules we should plan those deprecations in advance, and they can be replaced with macros at some point. So lgtm.

no need to wait for capstone fix to merge imho

**Comment by aemmitt-ns** [comment]
Ok i think its all done. To the best of my very poor knowledge of BPF all of the expressions are accurate. @trufae you can merge it when you are ready

**Comment by trufae** [comment]
Beautiful! Thanks! Cant wait to see what the crazy blockchain people will do now 🙈

**Pull request merged**
