### PR TITLE
WIP: Adding regression tests for FreeBSD build

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by XVilka** [comment]
Hmm, seems like tests are very slow at BSD. I think we should rewrite the tests from JavaScript to something native

**Comment by radare** [comment]
ok to merge @XVilka ?

**Comment by XVilka** [comment]
Not yet - see, the job is failing.

**Comment by unixfreaxjp** [comment]
@XVilka would you please explain how to install this in easy steps to freebsd and what is the requirements? I would like to try.
cc: @radare @devnexen

**Comment by devnexen** [comment]
Do you mean this ? https://builds.sr.ht

**Comment by XVilka** [comment]
Same problem as before - it stuck after this test:
```
[FX] db/tools/r2 r2 -L  97
[**]                    db/tools/r2   OK    5 BR    1 XX    0 FX    4
```

**Comment by XVilka** [comment]
You might be interested in this instead: https://github.com/radareorg/radare2/issues/15657

**Comment by XVilka** [comment]
Superseded by https://github.com/radareorg/radare2/pull/15852

**Pull request closed without merging**
