### PR TITLE
WIP: Initial cleanup of the jemalloc library to actually compile

### PR DESCRIPTION
**Pull request by radare**

### CODE REVIEW

**Comment by ret2libc** [comment]
What's the status of this? Can it be closed? I'd like to clean super-old PRs that have not been touched for a long time.

**Comment by radare** [comment]
Needs to be finished and tested. Problem is we dont have any test for jemalloc

**Comment by XVilka** [comment]
@ret2libc it is also quite related to:
- https://github.com/radare/radare2/issues/11886
- https://github.com/radare/radare2/issues/4328
- https://github.com/radare/radare2/issues/5390

Basically reliance on the host platform should be removed and the code should be refactored to be more portable, for example allowing heap navigation for remote gdb targets of a different architecture, bitness and endianess.

**Comment by radare** [comment]
without having tests for jemalloc refactoring this is just going to break things, closing because in 2 years nobody cared to maintain this

**Pull request closed without merging**
