### PR TITLE
[WIP] Merge asm.dalvik into anal

### PR DESCRIPTION
**Pull request by gogo2464**
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

### CODE REVIEW

**Comment by Lazula** [comment]
This is far from ready, so I'm marking it as a draft. Please mark it for review once it's in working order.

**Comment by trufae** [comment]
I would suggest @gogo2464 to work on a simplest plugin instead. It will be essier to review too. Dalvik one is probably the most complex of the remaining ones

**Comment by gogo2464** [comment]
Alright. Should I just push a last time to let someone continue on my work?

**Comment by trufae** [comment]
im curious about how the new output is getting printed , because i think its more readable, but can cause problems to understand which exact overloaded function is being called. so not sure if there's an `asm.` variable to select that or how you got the different disassembly on the failing tests

Screenshot 2022-07-14 at 17 32 57

**Comment by gogo2464** [comment]
Basically I just changed RAsm struct by RAnal. But the names of the attributes are different. Then I probably made a mistake.

**Comment by Lazula** [comment]
its using `RAnal.binb.get_name()`. previously it used `RAsm.binb.get_name()` and passed `RAsm.pseudo` as `sd` (`simplified`), but idk which if any anal member would be used

**Comment by Lazula** [comment]
Right now simplified is just always enabled instead of being configured

**Comment by gogo2464** [comment]
Ah yes and I put the fourth argument of RAnal.binb.get_name() as alway true! It could be the mistake.

**Pull request closed without merging**
