### PR TITLE
r2pm: Support cleaning of package cloned to <package>.git ##tools

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

There is at least 1 r2pm package that clones itself into a \<package\>.git folder. This pr allows cleaning of those kind of packages.

**Test plan**

`r2pm -c r2ghidra-dec`

**Closing issues**

...

### CODE REVIEW

**Comment by trufae** [comment]
Maybe it should clean Wrkdir instead. Also, which packages are behaving like this?

**Comment by kazarmy** [comment]
> Maybe it should clean Wrkdir instead.

sometimes the only quick way to fix a problem is to clean everything ... besides, cleaning Wrkdir can be done during installation e.g. [here](https://github.com/radareorg/radare2-pm/blob/dafdd43b6bae6dc166afbe30bdca7f16041ef989/db/r2ghidra-dec#L10) ... in this case r2ghidra-dec is a pretty large download but an `r2pm -ci` due to a release shouldn't happen too often

> Also, which packages are behaving like this?

apart from r2ghidra-dec, i didn't check ... anyway i think in this case r2pm should be accommodating

**Comment by trufae** [comment]
I would rather prefer to fix the r2ghidra pkg instead of doing this

**Comment by kazarmy** [comment]
```
db]$ git grep '\.git"'
emscripten:R2PM_GIT "https://github.com/juj/emsdk.git"
os9:R2PM_GIT "https://github.com/thestr4ng3r/r2-os9.git"
r2commodore:R2PM_GIT "https://github.com/thestr4ng3r/r2commodore.git"
r2ghidra-dec:R2PM_GIT "https://github.com/radareorg/r2ghidra-dec.git"
retdec-r2plugin:R2PM_GIT "https://github.com/avast/retdec-r2plugin.git"
```

I think cloning to \<package\>.git is frequent enough that we should support \<package\>.git cleaning as well.

**Comment by trufae** [comment]
Frequent enough? It never happens to me. On which environment/situation is this mandatory? It can be removed also r2pm_git accepts a 2nd arg with the name of the directory to clone it

**Pull request merged**
