### PR TITLE
Fix a fatmach0 test under aarch64 ##test

### PR DESCRIPTION
**Pull request by thestr4ng3r**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [x] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

When the host where r2 runs is aarch64, the 64 bit part of the binary is selected by default and the test fails, so I select the arch/bits explicitly.
Since I never worked with fatmach0 stuff I am not entirely sure whether switching with `oa` is the correct approach here so please review.

**Test plan**

Run the tests on a 64 bit arm system.

### CODE REVIEW

**Comment by ret2libc** [comment]
Can't you specify the bits to select with `-b 32`? I remember there was some option for fat bins.

**Comment by trufae** [comment]
Yes, from commandline you can select the slice with -a and -b, by using the RBin api you can select by index too

**Comment by trufae** [comment]
I would say to use ARGS instead of reopening. but maybe good to test both ways

**Comment by thestr4ng3r** [comment]
Related: #17049

**Comment by thestr4ng3r** [comment]
Updated to use ARGS.
Yes I think oa needs tests in general.

**Pull request merged**
