### PR TITLE
Fix long PPC ESIL (#16102)

### LINKED ISSUE #16102: `r_strbuf_fini` in PPC analop "hides" longer ESIL statements
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | DOL
| Architecture/bits of the file (mandatory)            | PPC/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.3.0-git 23907 @ linux-x86-64 git.4.2.1-188-gcf1e7d9a6 commit: cf1e7d9a680f12b85895ae317f10366c7330ddf7 build: 2020-03-02__13:38:39

### Expected behavior

`pie` shows all supported ESIL statements regardless of their length

### Actual behavior

ESIL statements longer than about 30 characters (i.e. the static buffer size of RStrBuf) aren't shown

### Steps to reproduce the behavior 
Example test case:

    EXPECT=<<EOF
    bdnz 0xfffffffffffffff0
    0x00000000 1,ctr,-=,$z,!,?{,0xfffffffffffffff0,pc,=,}
    EOF
    CMDS=<<EOF
    e asm.arch=ppc
    e asm.bits=32
    e cfg.bigendian=true
    "(pi bytes,wx $0,pi 1,pie 1)"
    .(pi 4200fff0)
    EOF

### PR DESCRIPTION
**Pull request by quantumdude836**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [x] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

Unlike other analysis plugins, the PPC analysis (`libr/anal/p/anal_ppc_cs.c`) doesn't have a separate `analop_esil` function; instead, ESIL is unconditionally generated in the main `analop` function. Instead of refactoring the code and extracting out a separate `analop_esil` function, this PR just fixes the linked issue by discarding the generated ESIL (via a call to `r_strbuf_fini`) only if the corresponding mask bit isn't set.

**Test plan**

Added test case to db/esil/ppc_32 to verify ESIL statements longer than 30 characters are printed

**Closing issues**

closes #16102

### CODE REVIEW

**Comment by radare** [comment]
i think this is introducing a memory leak in some situations, a better fix must be done

**Comment by quantumdude836** [comment]
> i think this is introducing a memory leak in some situations, a better fix must be done

Yep, there's no `r_anal_op_fini` call when printing instructions (`libr/core/disasm.c` lines 6506-6525). Adding that call seems to fix the introduced leak.

**Comment by radare** [comment]
can you send a p r fixing this?

**Comment by radare** [comment]
see https://github.com/radareorg/radare2/issues/16113

**Pull request merged**
