### PR TITLE
Add help for `aij` and `arj` ##anal

### PR DESCRIPTION
**Pull request by officialcjunior**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**
Added internal help for `aij` and `arj` under `ai?` and `ar?`, respectively. 
Also updated `test/db/json` with `aij`.
I'm also hoping to add help for `pdaj`. But I'm confused on where exactly to add them.

**Test plan**

- [x] Decide on where to add help for `pdaj`: under `pd?` or under `pda?`. (`pda?` doesn't exist yet.)

- [x] Add help for `@v`

**Closing issues**

None.

### CODE REVIEW

**Comment by trufae** [comment]
Can you add a list of checkboxes describing what's left to not be a draft? Thank you!

**Comment by officialcjunior** [comment]
Sorry about that, I didn't know that's how it was supposed to be done. I'll keep that in my mind. 👍🏻

**Review by trufae — APPROVED** [review]

**Comment by trufae** [comment]
Yes, you should also update the PR to include pda[j] in the help message, as well as handle pda?

There are many other pd subcommands that doesnt handle the ? well. can you also look at this?

**Review by trufae — CHANGES_REQUESTED** [review]
See comment

**Comment by officialcjunior** [comment]
> Yes, you should also update the PR to include pda[j] in the help message, as well as handle pda?
> 
> There are many other pd subcommands that doesnt handle the ? well. can you also look at this?

I'll create `pda?` and add the help for `pdaj` under it. I'll also make `pds?` look good.

Here's what I think for `pds?`
```
pdsf  - sumarize the current function
pdsb  - sumarize N bytes
```

That'll be it, right? Does it have args? I tried passing args to pdsb, but there weren't much difference.

```

**Comment by trufae** [comment]
Yeah that sounds good

**Comment by officialcjunior** [comment]
Added help for `pdaj` under `pda` and `psdf`, `pdsb` under `pds`. Also added `pi` and `pI` under `p?`.

If there's any mistakes, you can requesting changes.

There's also the command `@v` which doesn't have any help. What should that say? I have no idea what that command is doing.

**Comment by XVilka** [comment]
I think for `@v` we also need some tests as well.

**Comment by XVilka** [comment]
@ret2libc by the way, `@v` command doesn't work with `e cfg.newshell=true`:
```
[0x00006b60]> e cfg.newshell=false
[0x00006b60]> px 10
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00006b60  f30f 1efa 31ed 4989 d15e                 ....1.I..^
[0x00006b60]> px 10 @v:0x6b64
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00006b60  646b 0000 0000 0000 d15e                 dk.......^
[0x00006b60]> 
```

**Comment by officialcjunior** [comment]
Added help for `@v`. I have no extra helps to be added to this pull request.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Review by trufae — APPROVED** [review]

**Review by XVilka — APPROVED** [review]

**Pull request merged**
