### PR TITLE
Update tree-sitter to 0.17.2

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

Update tree-sitter runtime library to include TinyCC build fixes:
- https://github.com/radareorg/radare2/pull/17295
- https://github.com/tree-sitter/tree-sitter/pull/743

**Test plan**

All green

### CODE REVIEW

**Comment by ret2libc** [comment]
Did you re-compile the radare2 grammar? Look at https://github.com/radareorg/radare2/blob/master/shlr/radare2-shell-parser/README.md for the steps to update it.

**Comment by XVilka** [comment]
@ret2libc no need for that - TS runtime is backward-compatible, should work without that. We can recompile grammar later.

**Comment by ret2libc** [comment]
I know it should work even without, but every time I update tree-sitter I usually also update the grammar to make sure we take advantage of any fix/new thing.

**Comment by XVilka** [comment]
I am reluctant to install `npm` just for this :D

**Comment by XVilka** [comment]
@ret2libc please take a look again and lets this get merged.

**Review by ret2libc — APPROVED** [review]

**Pull request merged**
