### PR TITLE
Add Meson option to specify whether CLI tools should be built

### PR DESCRIPTION
**Pull request by oleavr**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

Found myself needing this to speed up CI builds in a [project](https://github.com/frida/cryptoshark) that consumes r2's libraries.

### CODE REVIEW

**Comment by ret2libc** [comment]
Running:
```
$ meson -Dlocal=true --prefix=~/.local -Dcli=disabled build-cli-disabled
```
gives me
```
test/unit/meson.build:63:4: ERROR: Unknown variable "rpath".
```

**Comment by ret2libc** [comment]
@karliss AFAIK Cutter uses radare2 as a submodule, right? Is this change ok for you? I'm no cutter expert, but it could be you are using the r2 binaries in cutter and this would not compile them when r2 is included as a meson subproject.

**Comment by oleavr** [comment]
> test/unit/meson.build:63:4: ERROR: Unknown variable "rpath".

Oops, sorry about that!  Fixed.

**Comment by oleavr** [comment]
@ret2libc @karliss The option's default value of `auto` preserves the existing behavior of disabling CLI tools when used as a subproject:

```meson
cli_option = get_option('cli')
if cli_option.auto()
  cli_enabled = not meson.is_subproject()
else
  cli_enabled = cli_option.enabled()
endif
```

**Comment by karliss** [comment]
@ret2libc Shouldn't be a problem. Meson build isn't currently used for release packages so presence of r2 executables doesn't matter too much.

**Review by ret2libc — APPROVED** [review]

**Comment by ret2libc** [comment]
Thanks!

**Pull request merged**
