### PR TITLE
Fix capstone include directory

### PR DESCRIPTION
**Pull request by hamarituc**
- [x] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

Capstone requires to explicitly state the include path like `#include <capstone/capstone.h>` (see https://www.capstone-engine.org/lang_c.html). Until version 4 `#include <capstone.h>` worked as well. But from version 5 on, the former method is required (see https://github.com/capstone-engine/capstone/issues/1807).

This PR fixes the include paths such that Radare2 can be built against newer versions of capstone.

### CODE REVIEW

**Comment by trufae** [comment]
R2 builds fine against cs3, 4 and 5. The latest is the default. This change will break backward compat i think

**Comment by trufae** [comment]
```
/home/runner/work/radare2/radare2/libr/..//libr/anal/p/anal_6502_cs.c:8:10: fatal error: capstone/capstone.h: No such file or directory
[990](https://github.com/radareorg/radare2/runs/6242267041?check_suite_focus=true#step:4:990)
    8 | #include <capstone/capstone.h>
[991](https://github.com/radareorg/radare2/runs/6242267041?check_suite_focus=true#step:4:991)
      |          ^~~~~~~~~~~~~~~~~~~~~
[992](https://github.com/radareorg/radare2/runs/6242267041?check_suite_focus=true#step:4:992)
compilation terminated.
[993](https://github.com/radareorg/radare2/runs/6242267041?check_suite_focus=true#step:4:993)
make[5]: *** [/home/runner/work/radare2/radare2/libr/../global.mk:42: /home/runner/work/radare2/radare2/libr/..//libr/anal/p/anal_6502_cs.o] Error 1
[994](https://github.com/radareorg/radare2/runs/6242267041?check_suite_focus=true#step:4:994)
make[4]: *** [/home/runner/work/radare2/radare2/libr/..//libr/rules.mk:86: prelib-build] Error 2
[995](https://github.com/radareorg/radare2/runs/6242267041?check_suite_focus=true#step:4:995)
make[3]: *** [Makefile:23: main] Error 2
[996](https://github.com/radareorg/radare2/runs/6242267041?check_suite_focus=true#step:4:996)
make[2]: *** [Makefile:164: anal] Error 2
[997](https://github.com/radareorg/radare2/runs/6242267041?check_suite_focus=true#step:4:997)
make[2]: *** Waiting for unfinished jobs....
```

**Comment by hamarituc** [comment]
> R2 builds fine against cs3, 4 and 5. The latest is the default. This change will break backward compat i think

Did you built against system capstone library? In my case it fails:

```
# ./configure --without-libuv --with-syscapstone --with-syslz4 --with-sysmagic --with-sysxxhash --with-syszip --with-openssl
[...]
Final report:
 - BUILD = x86_64-unknown-linux-gnu
 - CC = gcc
 - CFLAGS = ""
 - DEBUGGER = 1
 - HAVE_ARC4RANDOM_UNIFORM = 0
 - HAVE_EXPLICIT_BZERO = 1
 - HAVE_EXPLICIT_MEMSET = 0
 - HAVE_FORK = 1
 - HAVE_GPERF = 1
 - HAVE_LIBUV = 0
 - HAVE_LIB_GMP = 0
 - HAVE_OPENSSL = 1
 - HAVE_PTRACE = 1
 - HOST = x86_64-unknown-linux-gnu
 - LDFLAGS = ""
 - LIBVERSION = 5.6.8
 - PKGCONFIG = /usr/bin/pkg-config
 - PREFIX = /usr/local
 - R_CHECKS_LEVEL = 2
 - TARGET = x86_64-unknown-linux-gnu
 - USERCC = gcc
 - USEROSTYPE = gnulinux
 - USE_CAPSTONE = 1
 - USE_LIB_MAGIC = 1
 - USE_LIB_XXHASH = 1
 - USE_LIB_ZIP = 1
 - USE_PTRACE_WRAP = 1
 - USE_SYSLZ4 = 0
 - VERSION = 5.6.8
 - WANT_DYLINK = 1

# LANG=C make all
[...}
gcc -Iarch/arm/v35arm64//arch-arm64/disassembler/  -I/usr/local/src/radare2-5.6.8/libr -I/usr/local/src/radare2-5.6.8/libr/include -MD -DR2_PLUGIN_INCORE -Iarch/include -Iarch -I../../shlr   -fPIC -g -Wall -D__UNIX__=1  -I./arch/8051/ -I./arch/amd29k/ -I/usr/local/src/radare2-5.6.8/libr/asm/arch/cr16 -I/usr/local/src/radare2-5.6.8/libr/asm/arch/h8300 -I./arch/or1k/ -I./arch/propeller/ -I/usr/local/src/radare2-5.6.8/libr/asm/arch/pyc -I/usr/local/src/radare2-5.6.8/libr/asm/arch/rsp -I./arch/v810 -I/usr/local/src/radare2-5.6.8/libr/asm/arch/v850 -I/usr/local/src/radare2-5.6.8/libr/../shlr/sdb/src -fvisibility=hidden -o p/asm_arm_cs.o -c p/asm_arm_cs.c
In file included from p/asm_arm_cs.c:6:
p/cs_version.h:4:10: fatal error: capstone.h: No such file or directory
    4 | #include <capstone.h>
      |          ^~~~~~~~~~~~
compilation terminated.

# cat /usr/lib64/pkgconfig/capstone.pc
prefix=/usr
exec_prefix=${prefix}
libdir=${prefix}/lib64
includedir=${prefix}/include

Name: capstone
Description: Capstone disassembly engine
Version: 5.0.0
URL: http://www.capstone-engine.org
archive=${libdir}/libcapstone.a
Libs: -L${libdir} -lcapstone
Cflags: -I${includedir}
archs=
```

Distro: Gentoo Linux

It builds fine against system capstone 4 and 5 with the patches applied. Shall I open a GitHub Issue about this?

**Comment by trufae** [comment]
I see, yes, it will be good to test r2 builds with cs5 and cs4 system -wide installed. Can you update the PR to handle that?

**Comment by trufae** [comment]
Can you rebase to fix the conflicts?

**Comment by trufae** [comment]
Not sure how can you handle capstone/capstone.h and capstone.h without modifying all the C files

**Comment by hamarituc** [comment]
> Not sure how can you handle capstone/capstone.h and capstone.h without modifying all the C files

It should just be a matter of the build system and the right compiler flags. I need a closer look onto the build system to figure out how things work. Give me some time to think about it and to test all the different build modes. I will continue to work on this issue, but I am not able to solve it right now.

My goal is to push a new capstone version for Gentoo Linux and to keep Radare2 running under Gentoo.

**Comment by trufae** [comment]
Looks good now!

the problem with your solution is that it wont allow r2 to compile with system-wide, stock capstone3 installation.

But anway. it's 2022, and cs5 should be out several years ago. so im fine to merge this pr as it is right now.

thanks!

**Pull request merged**
