### PR TITLE
Set rpath if non-Windows Meson shared build

### PR DESCRIPTION
**Pull request by kazarmy**
For non-root installs and side-by-side builds.

### CODE REVIEW

**Comment by kazarmy** [comment]
For non-root installs and side-by-side builds.

**Comment by radare** [comment]
@GustavoLCR can you have a look at this?

**Comment by kazarmy** [comment]
Meson apparently ignores `install_rpath` on Windows: https://github.com/mesonbuild/meson/blob/7e2c54c0a38788380c7f05dff3244faaa76e0220/mesonbuild/compilers/d.py#L218-L219

**Comment by radare** [comment]
please rebase the pr. the rpath is unrecommended for distros becacuse they want to override all the flags, and the rpath is quite intrussive. thats why --with-rpath is not enabled by default in configure.

Also, i see some spaguetti here, can we simplify this to have it only in 1 place?

**Comment by kazarmy** [comment]
> please rebase the pr.

done

> the rpath is unrecommended for distros becacuse they want to override all the flags, and the rpath is quite intrussive.

ok i'll only set rpath if there is a `--local` flag

> Also, i see some spaguetti here, can we simplify this to have it only in 1 place?

probably

**Comment by kazarmy** [comment]
> Also, i see some spaguetti here, can we simplify this to have it only in 1 place?

Since Meson [does not support user-defined functions](https://mesonbuild.com/Syntax.html#userdefined-functions-and-methods) then fbe7d59bcdd3f1b0dfdd5a5d1621185f42dcd220 apparently is best possible if only involving `install_rpath`.

**Comment by radare** [comment]
Is there a way to build with meson.. without the rpath?

**Comment by kazarmy** [comment]
> Is there a way to build with meson.. without the rpath?

yes 50c716123e977a3ef2e0daf2755c64510cdad9be by default, rpath is not set

**Comment by kazarmy** [comment]
ok to merge?

**Pull request merged**
