### PR TITLE
sdb: Strip UTF8 BOM when creating db

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

This pr prevents the following:

BOM_in_sdb_with_oval

i.e. a UTF8 BOM in the sdb.

**Test plan**

All builds are green.

**Closing issues**

...

### CODE REVIEW

**Comment by trufae** [comment]
Some questions here:

* Why is having such sequence in a binary file is a problem?
* Why apply this fix in r2 insterad of the sdb repo directly?

**Comment by ret2libc** [comment]
Yeah this should be done in https://github.com/radareorg/sdb . Closing this, please move it there.

**Comment by trufae** [comment]
My guess is that he pushed this change in here to ensure r2 suite was not breaking after the change

**Comment by kazarmy** [comment]
> Why is having such sequence in a binary file is a problem?

It's a problem because it attaches itself to the following characters (it's a bona fide unicode char after all) and in this case, it causes the following to fail:

https://github.com/radareorg/radare2/blob/cdd039a38ae9d28b81fe820a7c85289085d14952/libr/anal/cc.c#L161

bringing down at least type propagation with it.

> Why apply this fix in r2 insterad of the sdb repo directly?

Because r2 is an sdb client and it doesn't pull from the sdb repo automatically? I'm honestly confused here. Yes, the fix should be in the sdb repo as well.

> My guess is that he pushed this change in here to ensure r2 suite was not breaking after the change

That's one reason.

**Comment by ret2libc** [comment]
> > Why apply this fix in r2 insterad of the sdb repo directly?
> 
> Because r2 is an sdb client and it doesn't pull from the sdb repo automatically? I'm honestly confused here. Yes, the fix should be in the sdb repo as well.

Things should land first in sdb, as it is mainly an independent project (:D) and then you should get the changes by using `make sdb-sync `.

**Comment by kazarmy** [comment]
oh ok https://github.com/radareorg/sdb/pull/209

**Pull request closed without merging**
