### PR TITLE
Merge asm.tms320 into anal.tms320

### PR DESCRIPTION
**Pull request by terorie**
- [x] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

### CODE REVIEW

**Comment by trufae** [comment]
please rebase and check the failing tests, its not easy to do from ghwebui :P

**Comment by terorie** [comment]
Sorry, I'm not sure why these tests are still failing. :(

**Comment by trufae** [comment]
Ill take a look. Thanks!

**Comment by trufae** [comment]
Congratulations you found a bug in capstone. im gonna report that 👍

**Comment by trufae** [comment]
context: https://github.com/capstone-engine/capstone/issues/1893

**Pull request closed without merging**
