### PR TITLE
fortunes: remove nsfw and creepy fortunes

### PR DESCRIPTION
**Pull request by FFY00**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [X] I've added tests that prove my fix is effective or that my feature works (if possible)
- [X] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

From the commit description:

    These fortunes make a lot of people unconfortable and can be trigering
    for some. Even if they are not active by default, they should have no
    place here if you are trying to be a welcoming project.

    There are a lot of other ways to be quirky and fun, I see no logical
    reason to have these fortunes knowing they will negatively impact
    people.

### CODE REVIEW

**Review by thestr4ng3r — CHANGES_REQUESTED** [review]
I can see how nsfw fortunes may be considered offensive to some, but there is no reason to remove the creepy ones. There are way more creepy things inside this repo.

**Comment by FFY00** [comment]
> Your hair smells different when you are not sleeping. 

> My sister says that mommy killed her. Mommy says that I don't have a sister.

> I wanted you to fill what I felt.

> Nobody can hear your calls for help

Some of them are still uncomfortable and may be triggering. Those are the obvious ones.

> There are way more creepy things inside this repo.

That would be very much an issue.

**Comment by thestr4ng3r** [comment]
> > Your hair smells different when you are not sleeping.
> 
> > My sister says that mommy killed her. Mommy says that I don't have a sister.
> 
> > I wanted you to fill what I felt.
> 
> > Nobody can hear your calls for help
> 
> Some of them are still uncomfortable and may be triggering. Those are the obvious ones.

I am triggered by dynamically typed languages. That is not an argument.

> > There are way more creepy things inside this repo.
> 
> That would be very much an issue.

PR to rewrite the swift demangler is welcome.

**Comment by FFY00** [comment]
> I am triggered by dynamically typed languages. That is not an argument.

Yeah, that is absolutely the same :disappointed:

I will not waste my time trying to explain how these sentences are bad and this project would be better without them.

@trufae this is what people are referring to when they criticize radare2. People are not out to get you, and do not hate radare2 just because... They are referring to this kind of behavior, which is harmful to others.

I don't understand how having these stupid sentences show up when you start the program is worth possibly hurting users.

**Comment by FFY00** [comment]
I am reopening this in the hopes you reconsider. I have looked at the community guidelines for Open Collective and I believe neither of the fortune categories meets them.

https://docs.opencollective.com/help/about/community-guidelines

**Review by XVilka — APPROVED** [review]
If the community believes it's so harmful - let's merge it.

**Review by wargio — APPROVED** [review]
Seems a good reason.

**Comment by thestr4ng3r** [comment]
> I am reopening this in the hopes you reconsider. I have looked at the community guidelines for Open Collective and I believe neither of the fortune categories meets them.
> 
> https://docs.opencollective.com/help/about/community-guidelines

Could you please point out the specific sentences that it violates? I think then there is a concrete argument for removal.

**Review by kazarmy — APPROVED** [review]

**Comment by stephen-fox** [comment]
Hello @thestr4ng3r,

From https://docs.opencollective.com/help/about/community-guidelines#be-respectful:

```
We have zero tolerance for unacceptable behavior. Being a jerk will
not get you a place in this community; it will turn people away.
We don’t want that noise in the system. If your account is found
to be engaged in any kind of unacceptable behavior, we can close it.

Unacceptable behaviors include: spamming, trolling, intimidating,
harassing, abusive, discriminatory, derogatory or demeaning speech
or actions by any participant in our community online, at all related
events and in one-on-one communications carried out in the context
of community business. 

Harassment includes: harmful or prejudicial verbal or written comments
related to gender, sexual orientation, race, religion, disability;
inappropriate use of nudity and/or sexual images (including
presentation slides); inappropriate depictions of violence (including
presentation slides); deliberate intimidation, stalking or following;
harassing photography or recording; sustained disruption of talks
or other events; inappropriate physical contact, and unwelcome
sexual attention.
```

**Review by thestr4ng3r — APPROVED** [review]
Thanks, I agree that this can be considered to apply here.

**Review by trufae — APPROVED** [review]

**Comment by termhn** [comment]
> Thanks, I agree that this can be considered to apply here.

Absolutely incredible that you can link a document as though it proves your point and then have quite literally a third of that document re-quoted back to you and suddenly agree that it's being violated. Have you even read your own code of conduct before this? Christ, how could you ever possibly even make an argument that this shit has any place here? Like, if it's legacy from people who no longer work on the project or bygone days, then that's unfortunate but whatever, at least it's gone now, but why would you ever put up a fight over a PR which literally does all the work of removing it from your codebase?

Glad it's gone but incredulous that we had someone actually arguing to keep it, lol

**Comment by thestr4ng3r** [comment]
First of all, I would kindly ask you to refrain from using curse words here.

There is no "own code of conduct" of radare2. The linked document is the one from OpenCollective, but which of course the project also has to follow to the point where it makes sense.

As with every other pull request on, there needs to be a proper reasoning of why the change is good and it must be clearly visible to anybody looking at the description or comments. The argument that it MAY be triggering is purely subjective, but the quoted paragraph covers it concrete enough. Without this, I may for example also say that I, as an atheist, am triggered by your comment because you used the word "Christ".

**Comment by termhn** [comment]
It's painfully obvious that you've never been actually triggered by anything in your life and are evidently incapable of being empathetic enough towards other people to realize that you seeing the word Christ is on such a different level from an actual trigger that it's not even on the same plane of existence.

**Comment by thestr4ng3r** [comment]
I completely agree. And this is exactly the point why proper reasoning is strictly necessary for these kinds of topics.

**Pull request merged**
