### PR TITLE
Test =h on Linux

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [X] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

This pr tests the r2 webserver (`=h`) on Linux.

**Test plan**

All builds are green.

**Closing issues**

...

### CODE REVIEW

**Comment by ret2libc** [comment]
I still wonder whether we really want webui at all.. At least whether we want it in the main repo.

**Comment by kazarmy** [comment]
Well @trufae wants to maintain it and it's only a bunch of text files (with the odd image thrown in). We might even get some web developers as contributors!

**Review by ret2libc — APPROVED** [review]
I know, it's just that maintaining and developing a web application is a completely different topic/focus than a reverse engineering framework. What webui is just a web application on top of r2, but it has nothing to do with reverse engineering. That's why I find it very out of place.

That said, the PR ofc is ok :)

**Comment by XVilka** [comment]
> We might even get some web developers as contributors!

It didn't happen for the last 5 years though...

**Comment by XVilka** [comment]
Can you please also add a test for *BSD too?

**Comment by kazarmy** [comment]
I'll open the test for all when I'm done doing the Windows version.

**Comment by kazarmy** [comment]
> I know, it's just that maintaining and developing a web application is a completely different topic/focus than a reverse engineering framework. What webui is just a web application on top of r2, but it has nothing to do with reverse engineering. That's why I find it very out of place.

Yeah it's basically Cutter in JavaScript, and there are a lot of things in r2 that need fixing and polishing

> It didn't happen for the last 5 years though...

If somebody tweets about it, then the Lindy effect might no longer apply

**Pull request merged**
