### PR TITLE
R2_590 change ESIL pop signature

### PR DESCRIPTION
**Pull request by luc-tielen**
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

Merge #21886 first, also this doesn't fix all warnings yet..

### CODE REVIEW

**Comment by trufae** [comment]
comments on this @condret ?

**Comment by trufae** [comment]
Can you rebase this PR we should target r2-6.x now

**Comment by condret** [comment]
sorry for the late response. i'm not a fan of this. I don't see any necessity, and all these casts to char * feel bloaty to me. We can do this, if you really want this

**Comment by trufae** [comment]
Theres a noticeable perf boost by not strduping every word. Thats the reason behind this patch. So maybe the casts are ugly but i wanted to make clear the intentions behind

**Comment by condret** [comment]
can't we then just rm the strdups

**Comment by trufae** [comment]
Nope i tried. Some because invalid pointers. So we need again an abstraction over strings

**Comment by condret** [comment]
ok, but why does it have to be const then, if the problem is just the strdups?

**Comment by trufae** [comment]
Because const is the way to tell the user that the token string is there and cant be modified. Making it clear that its not in the heap and cant be owned by the struct

**Comment by trufae** [comment]
@condret can you take care of this optimiation before 6.x your proposal about making the whole string a single char* and then replace , with 0 looks good to me too

**Comment by trufae** [comment]
too much conflicts closing

**Pull request closed without merging**
