### PR TITLE
Fix GP calculation when there are multiple entries ##anal

### PR DESCRIPTION
**Pull request by junchao-loongson**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

When [some files](https://github.com/junchao-loongson/test-bin/blob/master/cc1-nogp) have multiple entries and no loc._gp,calculation error in GP

 In [this files](https://github.com/junchao-loongson/test-bin/blob/master/cc1-nogp) 

pd 10 @ 0x1213185e8

            0x1213185e8      .qword 0x000000012011f0e0 ; entry.init0   ; [23] -rw- section size 288 named .init_array
            0x1213185f0      .qword 0x000000012011b980 ; entry.init1
            0x1213185f8      .qword 0x000000012011b9c8 ; entry.init2
            0x121318600      .qword 0x000000012011ba10 ; entry.init3
            0x121318608      .qword 0x000000012011bc00 ; entry.init4
            0x121318610      .qword 0x000000012011bd10 ; entry.init5
            0x121318618      .qword 0x000000012011bd68 ; entry.init6
            0x121318620      .qword 0x000000012011bdb0 ; entry.init7
            0x121318628      .qword 0x000000012011be50 ; entry.init8
            0x121318630      .qword 0x000000012011bef0 ; entry.init9

pd 1 @ 0x121318708

           0x121318708      .qword 0x000000012011f088 ; entry.fini0

r_list_pop  will return 0x12011f088（ entry.fini0 ）Instead of 0x12011efa0 (entry0)

We should use r_list_pop_head to make sure it gets entry0 instead of entry.fini0 

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by trufae** [comment]
Can you add a test? Thanks!

**Comment by junchao-loongson** [comment]
> Can you add a test? Thanks!

Get it done

**Comment by junchao-loongson** [comment]
How can I request a recheck

**Comment by XVilka** [comment]
Just rebase on top of the master and force push.

**Review by trufae — APPROVED** [review]

**Review by XVilka — APPROVED** [review]

**Pull request merged**
