### PR TITLE
FIX ESIL AARCH64 LDP

### PR DESCRIPTION
**Pull request by 0x8008135**
- [ ] Closing issues: None found
- [X] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [radare2book](https://github.com/radareorg/radare2book)

**Description**
The ESIL instructions  LDR,STR,STP,LDP were always performing a writeback on preindex which was confirmed to be wrong on a real target and qemu.

"ldp x0, x1, [x8, -0x10]**!**" <= MUST writeback
"ldp x0, x1, [x8, -0x10]" <= DON'T writeback

### CODE REVIEW

**Comment by trufae** [comment]
Can you add a test for those fixed instructions? i'll review during the weekend and merge! thanks!

**Comment by aemmitt-ns** [comment]
I'm a bit confused by what you mean. Sometimes the "%s,tmp,=" are unnecessarily in the ESIL but it does not always write to the base register like in these instrs 
```
            0x100003f04      fc6fbaa9       stp x28, x27, [sp, -0x60]! ; 96,sp,-=,x28,sp,=[8],x27,sp,8,+,=[8] ; sp=0xffffffffffffffa0 -> 0xbebafeca
            0x100003f08      fa6701a9       stp x26, x25, [sp, 0x10]   ; x26,sp,16,+,=[8],x25,sp,16,+,8,+,=[8]
            0x100003f0c      f85f02a9       stp x24, x23, [sp, 0x20]   ; x24,sp,32,+,=[8],x23,sp,32,+,8,+,=[8]
```
sp does not get written to. Maybe I am misunderstanding.

**Comment by 0x8008135** [comment]
> I'm a bit confused by what you mean. Sometimes the "%s,tmp,=" are unnecessarily in the ESIL but it does not always write to the base register like in these instrs
> 
> ```
> 0x100003f04      fc6fbaa9       stp x28, x27, [sp, -0x60]! ; 96,sp,-=,x28,sp,=[8],x27,sp,8,+,=[8] ; sp=0xffffffffffffffa0 -> 0xbebafeca
> 0x100003f08      fa6701a9       stp x26, x25, [sp, 0x10]   ; x26,sp,16,+,=[8],x25,sp,16,+,8,+,=[8]
> 0x100003f0c      f85f02a9       stp x24, x23, [sp, 0x20]   ; x24,sp,32,+,=[8],x23,sp,32,+,8,+,=[8]
> ```
> 
> sp does not get written to except in the preindexed instruction. Maybe I am misunderstanding.

Whenever preindex is used the register is not updated, unless the exclamation mark is put in the end (==writeback). It is not like postindexing where the register is updated in any cases.

Regarding the ESIL "%s,tmp,=" and DUP instruction, I simply didn’t want to modify them to avoid unwanted impacts since the emulation  was working well as-is. Maybe it could be worth checking if the ESIL could be improved…

**Comment by 0x8008135** [comment]
> Can you add a test for those fixed instructions? i'll review during the weekend and merge! thanks!

Will attempt to add tests before the weekend

**Comment by aemmitt-ns** [comment]
Could you explain which part of those expressions for the different STP instructions above is wrong though? They look ok to me.

**Comment by 0x8008135** [comment]
> Could you explain which part of those expressions for the different STP instructions above is wrong though? They look ok to me.

Thanks for the heads-up you are indeed right (I probably messed up while troubleshooting the issue)

I reverted all unnecessary changes back and discovered that the identified issue is only with LDP instructions....and patch it :)

Before 
```
[0x00000000]> pdt 3
name addr       bytes    disasm                    comment esil                                 refs       xrefs
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
     0x00000000 0415ffa8 ldp x4, x5, [x8], #-0x10          x8,[8],x4,=,x8,8,+,[8],x5,=,16,x8,-= 0x00000000 
     0x00000004 020d40a9 ldp x2, x3, [x8]                  x8,0,+,[8],x2,=,x8,0,+,8,+,[8],x3,=  0x00000000 
     0x00000008 0005ffa9 ldp x0, x1, [x8, #-0x10]!         16,x8,-=,x8,[8],x0,=,x8,8,+,[8],x1,= 0x00000000 
```
After
```
[0x00000000]> wx 0415ffa8020d40a90005ffa9
[0x00000000]> pdt 3
name addr       bytes    disasm                    comment esil                                 refs       xrefs
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
     0x00000000 0415ffa8 ldp x4, x5, [x8], #-0x10          x8,[8],x4,=,x8,8,+,[8],x5,=,16,x8,-= 0x00000000 
     0x00000004 020d40a9 ldp x2, x3, [x8]                  0,x8,+,[8],x2,=,8,0,x8,+,+,[8],x3,=  0x00000000 
     0x00000008 0005ffa9 ldp x0, x1, [x8, #-0x10]!         16,x8,-=,x8,[8],x0,=,8,x8,+,[8],x1,= 0x00000000 
```

**Comment by aemmitt-ns** [comment]
Ok nice yeah that was definitely broken before. This LGTM!

**Comment by 0x8008135** [comment]
> > Can you add a test for those fixed instructions? i'll review during the weekend and merge! thanks!
> 
> Will attempt to add tests before the weekend

@trufae I modified the LDP test to encompass the faulty LDP (preindex-no writeback). 

Should be fine now

Cheers

**Comment by trufae** [comment]
Merged! thank you!

**Pull request merged**
