### PR TITLE
Remove duplicate mention of CPPFLAGS

### PR DESCRIPTION
**Pull request by saagarjha**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

There are two `CPPFLAGS` descriptions in the configure script. I got rid of the less useful one.

**Test plan**

`./configure --help`

**Closing issues**

### CODE REVIEW

**Comment by trufae** [comment]
This file is autogenerated with the autogen.sh script. Can you send fix PR to the ACR repository? Its in the acr-sh file

**Comment by trufae** [comment]
Good finding! Thanks

**Comment by saagarjha** [comment]
Sure. Will you take care of updating the file here once that gets done?

**Comment by saagarjha** [comment]
https://github.com/radare/acr/pull/26

**Comment by trufae** [comment]
Yep ive updated it in a pr

**Pull request closed without merging**
