### PR TITLE
Remove r_sign_item_dup ##signatures

### PR DESCRIPTION
**Pull request by swoops**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [x] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

The `r_sign_item_dup` appears to only be used in one place. This is to set up a list of `RSignItems` for `r_search`. The items don't need to be duplicated if they are never free'd. This should result in a performance boost. 

The `r_sign_item_dup` function also has a bug where it does not properly duplicate the `items` signature. So by refactoring this function out, the `searchHitCB` should now get the necessary information to apply the type information to a function.

**Test plan**

See the command executed in #17607 PR.

**Closing issues**

...

### CODE REVIEW

**Review by XVilka — APPROVED** [review]

**Review by ret2libc — COMMENTED** [review]
I'm not so sure the `_dup` is not required. Those `RSignItem`s get added to `ss->items` and `ss->items` is freed in `r_sign_search_free`, for example.

**Review by trufae — APPROVED** [review]

**Review by ret2libc — CHANGES_REQUESTED** [review]
Just to make sure none merge the PR without first checking what said in previous comment.

**Comment by swoops** [comment]
> I'm not so sure the `_dup` is not required. Those `RSignItem`s get added to `ss->items` and `ss->items` is freed in `r_sign_search_free`, for example.

The `_dup` was required previously because the only `foreach` function would allow the callback to *borrow* the `RSignItem`, but not keep it. This is because the `foreach` kept a reference to each `RSignItem` and free'd that item on each loop.

This code ads a `foreach_no_free` function which never free's the `RSignItem`s it produces. This means the item can be given away and put inside of `ss->items`. The end result is the same, `ss->items` contains all the `RListItems`. They are just the items given away by the `foreach_no_free` function instead duplicates of the items borrowed from `foreach`.

**Comment by ret2libc** [comment]
@swoops if you look at `cmd_zign.c:searchRange` there are calls, in this order, to: `r_sign_search_new`+`r_sign_search_init`+`r_sign_search_update`+`r_sign_search_free`. In `r_sign_search_new` `ret->items` is initialized with `r_list_newf (r_sign_item_free)` (see https://github.com/radareorg/radare2/blob/master/libr/anal/sign.c#L2217). Then, in `r_sign_search_free` there is a call to `r_list_free (ss->items)` (see https://github.com/radareorg/radare2/blob/master/libr/anal/sign.c#L2227) which not only free the rlistiterator, but it also calls the function `r_sign_item_free`. If the RSignItems are not duplicated, as in your PR, this ends up in double free.

Am I missing anything?

**Comment by swoops** [comment]
Everything you said is correct, I think you are missing the removal of a free from whiten `r_sign_search_innit` call chain. Here is how it would work before the PR:

1. Create item `it` (bt: `foreachCB`, `r_sign_foreach`, `r_sign_search_init`)
2. Duplicate `it` into `it2`(bt: `addSearchKwCB`, `foreachCB`, `r_sign_foreach`, `r_sign_search_init`)
3. Add `it2` to `ss->items` (bt: `addSearchKwCB`, `foreachCB`, `r_sign_foreach`, `r_sign_search_init`)
4. free `it` (bt: `foreachCB`, `r_sign_foreach`, `r_sign_search_init`)
5. use `ss->items` in search
6. Free `ss->items` in `r_sign_search_free`

Now it looks like this:

1. Create item `it` (bt: `foreachCB`, `r_sign_foreach_nofree`, `r_sign_search_init`)
2. REMOVED
3. Modified: Add *original* `it` to `ss->items` (bt: `addSearchKwCB`, `foreachCB`, `r_sign_foreach_nofree`, `r_sign_search_init`)
4. REMOVED 
5. use `ss->items` in search
6. Free `ss->items` in `r_sign_search_free`

Notice the `r_sign_foreach_nofree` is used instead of `r_sign_foreach`. The `r_sign_foreach_nofree` sets `ctx.freeit == false` causing the `foreachCB` to skip the call to `r_sign_item_free`. As a result the `it` is not free'd in step 4. So it will still exist for steps 5 and 6.

**Review by ret2libc — APPROVED** [review]
Ok I think I kinda understand now! Thanks for the explanation.

**Pull request merged**
