### PR TITLE
Fix release 4.5.0 iOS and MacOS static build

### LINKED ISSUE #17469: sdb build problems after iOS fixes
```
Generating r_version.h file
/Applications/Xcode_11.6.app/Contents/Developer/usr/bin/make -C shlr targets
Makefile:173: warning: overriding commands for target `sdb/sdb'
Makefile:137: warning: ignoring old commands for target `sdb/sdb'
#for TARGET in  sdb/sdb ; do /Applications/Xcode_11.6.app/Contents/Developer/usr/bin/make $TARGET ; done
/Applications/Xcode_11.6.app/Contents/Developer/usr/bin/make sdb-native-build HOST_CC=gcc CC=gcc
Makefile:173: warning: overriding commands for target `sdb/sdb'
Makefile:137: warning: ignoring old commands for target `sdb/sdb'
make[2]: *** No rule to make target `sdb-native-build'.  Stop.
make[1]: *** [targets] Error 2
make: *** [all] Error 2
##[error]Process completed with exit code 2.
```
https://github.com/radareorg/radare2/runs/983548362#step:9:90

```
Generating r_version.h file
make -C shlr targets
make[1]: Entering directory '/home/runner/work/radare2/radare2/shlr'
Makefile:173: warning: overriding recipe for target 'sdb/sdb'
#for TARGET in  sdb/sdb ; do make $TARGET ; done
Makefile:137: warning: ignoring old recipe for target 'sdb/sdb'
make sdb-native-build HOST_CC=gcc CC=gcc
make[2]: Entering directory '/home/runner/work/radare2/radare2/shlr'
Makefile:173: warning: overriding recipe for target 'sdb/sdb'
Makefile:137: warning: ignoring old recipe for target 'sdb/sdb'
make[2]: *** No rule to make target 'sdb-native-build'.  Stop.
make[2]: Leaving directory '/home/runner/work/radare2/radare2/shlr'
make[1]: *** [targets] Error 2
Makefile:132: recipe for target 'targets' failed
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by ret2libc**
**Closing issues**

Fix #17469

### CODE REVIEW

**Comment by XVilka** [comment]
The build is fixed, not sure why tests are failing. Some demangling is broken, for example:
```
[XX] db/cmd/cmd_pd2 flag-func_sig order
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'e asm.demangle=true
e asm.bytes=false
e asm.filter=false
e asm.sub.jmp=false
aa
e asm.cmt.right=true
pd 1 @ 0x080493b4
pd 1 @ 0x080493ca
?e
e asm.cmt.right=false
pd 1 @ 0x080493b4
pd 1 @ 0x080493ca
' bins/elf/abcde-qt32
-- stdout
@@ -1,10 +1,8 @@
 |           0x080493b4      call 0x80490b0                             ; sym.imp.strlen ; size_t strlen(const char *s)
-|           0x080493ca      call 0x80490e0                             ; sym.imp.QString::fromAscii_helper_char_const___int
-|                                                                      ; QString::fromAscii_helper(char const*, int)
+|           0x080493ca      call 0x80490e0                             ; sym.imp._ZN7QString16fromAscii_helperEPKci
 
 |           ; sym.imp.strlen
 |           ; size_t strlen(const char *s)
 |           0x080493b4      call 0x80490b0
-|           ; sym.imp.QString::fromAscii_helper_char_const___int
-|           ; QString::fromAscii_helper(char const*, int)
+|           ; sym.imp._ZN7QString16fromAscii_helperEPKci
 |           0x080493ca      call 0x80490e0
```

Also this:
```
[XX] db/cmd/cmd_pd varsub for rip variable
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'aa; s main
e asm.syntax=att
e asm.var=0
e asm.lines.bb=0
e asm.bytes=0
e asm.comments=false
pdf
' bins/elf/varsub_2
-- stdout
@@ -1,7 +1,7 @@
 / 21: int main (int argc, char **argv, char **envp);
 | 0x0000061a      pushq %rbp
 | 0x0000061b      movq %rsp, %rbp
-| 0x0000061e      movl $1, obj.sa
+| 0x0000061e      movl $1, obj._ZL2sa
 | 0x00000628      movl $0, %eax
 | 0x0000062d      popq %rbp
 \ 0x0000062e      retq
```

**Comment by ret2libc** [comment]
@XVilka the failing tests are not due to this PR. I created https://github.com/radareorg/radare2/pull/17543 and you can see that even there there are the same tests (a bit more, but anyway...). That PR was created with the code *before* the sdb header changes. So I would say there are other issues with static builds :( but at least this PR makes it compile on release-4.5 branch.

**Review by XVilka — APPROVED** [review]
Ok then.

**Comment by ret2libc** [comment]
I'm not sure though why static fails and that's definitely a bug.

**Pull request merged**
