### PR TITLE
Fix #17759 - Add vector35 arm64 plugin ##disasm

### LINKED ISSUE #17759: Integrate V35 ARM64 disassembler ##disasm
**Is your feature request related to a problem? Please describe.**
Integrate Vector35's ARM64 disassembler in radare2. The source is now available here: https://github.com/Vector35/arch-arm64

**Describe the solution you'd like**
Much like the other supported disassembler backends in rasm2, this disassembler should be supported as well.

**Additional context**
It is licensed under Apache 2.0 and can be moved in-tree.

### PR DESCRIPTION
**Pull request by trufae**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

Capstone5 will  probably never come, been waiting so much years for it and still no tag. So having the vector35 arm64 disassembler seems to be an idea solution here to cover arm64 targets, benefits i see:

* better maintained
* just a single .c file
* smaller (8KLOC)

**Test plan**

its working, analysis is 3-4 times fster than capstone, but theres still not much metainfo, or esil implemented on top of it. but basic control flow analysis and disasm works as expected!

**Closing issues**

#17759

### CODE REVIEW

**Review by XVilka — CHANGES_REQUESTED** [review]
Not sure, maybe remove unused code in `#if 0`?

**Comment by wargio** [comment]
i agree with XVilka. might be better to remove unused code.

**Comment by trufae** [comment]
it's still WIP and red, i plan to complete more the arm64 support, and the commented code will be uncommented when ready and working. But looks really promising to me

**Comment by wargio** [comment]
i think this is too big and should go to extras.

**Comment by trufae** [comment]
It's big indeed. The repo was few KBs some weeks ago when i did the PR, but not it got much bigger. im fine for moving this to extras. I think v35 disassemblers are a great candidate to kill capstone. which is very badly maintained and outdated and misses a lot of instructions. So i'll just push this to extras and close the PR. i have a couple of colleagues interested in contributing, so having this in core is not the way to go for contributing either.

**Comment by wargio** [comment]
Yes, can be nice to use a proper library and keep it updated.

**Comment by meme** [comment]
Sounds good. V35 has released a newer version as well which is _much_ more complete but still "experimental"

**Comment by trufae** [comment]
Done https://github.com/radareorg/radare2-extras/pull/269

**Pull request closed without merging**
