### PR TITLE
Fix big endian DWARF parsing ##bin

### PR DESCRIPTION
**Pull request by HoundThe**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

So when I was working on #17434 I've seen that the READ macros have hardcoded little endian and hot fixed that, now I've fixed rest of the hardcoded endianity that was left and added test on big endian ppc64 binary

### CODE REVIEW

**Comment by XVilka** [comment]
```


[XX] db/cmd/dwarf "big endian variable info"
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'e asm.dwarf=false
aaa
pdf @  dbg.init
' bins/elf/ppc64_sudoku_dwarf
-- stdout
@@ -3,7 +3,7 @@
             ;-- method.Grid.init:
 / 64: dbg.init (Grid * const this);
 |           ; arg Grid * const this @ r3
-|           0x100012bc      39030144       addi r8, r3, 0x144          ; arg1 ; void init(Grid * const this);
+|           0x100012bc      39030144       addi r8, r3, 0x144          ; arg1 ; void init(Grid * const this);
 |           0x100012c0      38e30168       addi r7, r3, 0x168          ; arg1
 |           0x100012c4      39400000       li r10, 0
 |           ; CODE XREF from Grid::init() @ 0x100012e8

-- stderr
[ ] Analyze all flags starting with sym. and entry0 (aa)
[
[x] Analyze all flags starting with sym. and entry0 (aa)

[ ] Analyze function calls (aac)
[
[x] Analyze function calls (aac)
[ ] Analyze len bytes of instructions for references (aar)
[
[x] Analyze len bytes of instructions for references (aar)
[ ] Check for vtables
[
[x] Check for vtables
[ ] Finding xrefs in noncode section with anal.in=io.maps
[
[x] Finding xrefs in noncode section with anal.in=io.maps
[x] Finding xrefs in noncode section with anal.in=io.maps
[ ] Analyze value pointers (aav)
[
[x] Analyze value pointers (aav)
[ ] Value from 0x10000000 to 0x10002038 (aav)
[
[x] Value from 0x10000000 to 0x10002038 (aav)
[ ] 0x10000000-0x10002038 in 0x10000000-0x10002038 (aav)
[
[x] 0x10000000-0x10002038 in 0x10000000-0x10002038 (aav)
[ ] Emulate functions to find computed references (aaef)
[Warning: No SN reg alias for current architecture.
Warning: No SN reg alias for current architecture.
Warning: No SN reg alias for current architecture.
Warning: No SN reg alias for current architecture.
Warning: No SN reg alias for current architecture.
Warning: No SN reg alias for current architecture.
Warning: No SN reg alias for current architecture.
Warning: No SN reg alias for current architecture.
Warning: No SN reg alias for current architecture.
Warning: No SN reg alias for current architecture.

[x] Emulate functions to find computed references (aaef)
[ ] Type matching analysis for all functions (aaft)
[
[x] Type matching analysis for all functions (aaft)
[ ] Propagate noreturn information
[
[x] Propagate noreturn information
[ ] Integrate dwarf function information.
[
[x] Integrate dwarf function information.
[ ] Use -AA or aaaa to perform additional experimental analysis.
[
[x] Use -AA or aaaa to perform additional experimental analysis.
```

**Comment by HoundThe** [comment]
Woah I can't see a difference and copy pasting the diffed line seems to not make any difference, weird. I'll look in the morning

**Comment by XVilka** [comment]
There are also conflicts to be solved.

**Comment by XVilka** [comment]
What
```
|           0x100012bc      39030144       addi r8, r3, 0x144          ; arg1 ; void init(Grid * const this);
|           0x100012bc      39030144       addi r8, r3, 0x144          ; arg1 [0m; void init(Grid * const this);
```
does mean? It looks weird
cc @ret2libc

**Comment by ret2libc** [comment]
I'm not sure. It could be something related to colors? Is it necessary only in this PR? Or maybe some oob that is showing up here...

**Comment by trufae** [comment]
This glitch/bug seems unrelated to this PR but it seems like its printing uninitialized memory before an ansi escape code, what's ASAN thinking about this?

**Comment by HoundThe** [comment]
I think it's just `\u001b[0m` RESET_COLOR escape code that is somewhere outside of an if check probably.

**Comment by HoundThe** [comment]
In hex editor it's just `1B 5B 30 6D` which is the reset color in hex

**Comment by XVilka** [comment]
Shouldn't r2r ignore these when comparing the output? cc @kazarmy

**Review by ret2libc — APPROVED** [review]
seems ok to me

**Review by XVilka — APPROVED** [review]

**Comment by XVilka** [comment]
Please rebase.

**Comment by kazarmy** [comment]
> Shouldn't r2r ignore these when comparing the output? cc @kazarmy

No since they are unexpected if `e scr.color=0`

**Pull request merged**
