### PR TITLE
Fix UB in core.java plugin

### PR DESCRIPTION
**Pull request by trufae**
***SQUASH ME***
==============

```
libr/core/p/core_java.c: In function 'r_cmd_java_handle_help':
libr/core/p/core_java.c:390:34: warning: iteration 20 invokes undefined behavior [-Waggressive-loop-optimizations]
   help_msg[3 + (i * 3) + 0] = cmd->name;
                               ~~~^~~~~~
libr/..//libr/core/p/core_java.c:388:2: note: within this loop
  for (i = 0; i < END_CMDS; i++) {
```
 

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Review by ret2libc — CHANGES_REQUESTED** [review]
Just remove `LIST_CODE_REFS_IDX = 15,` from the enum and shift all the values after that (or even better, just remove all the values apart from `= 0`).

**Comment by trufae** [comment]
I think its safer to expect null items at the end of the array than syncing it's size with the enum and such.

**Comment by ret2libc** [comment]
You are not really solving anything by putting `NULL, NULL, NULL` at the end of the array. The array is not traversed until the null item, it is traversed until `END_CMDS`. And the issue is that the enum and the array are not in sync, so if you don't remove the entry i said in https://github.com/radareorg/radare2/pull/17831#pullrequestreview-515929603 all commands after `15` will be wrong.

**Comment by trufae** [comment]
wtf seems like some of my fixes got lost, this pr is incomplete. let me tweak it back

**Review by ret2libc — CHANGES_REQUESTED** [review]
This does not work well anyway, because some of the enum values are used to access the JAVA_CMDS array, so they have to be adjusted no matter what. Please remove the `LIST_CODE_REFS_IDX = 15` and shift all values after that.

**Comment by XVilka** [comment]
@wargio the same pattern here, as in https://github.com/radareorg/radare2/pull/17829

**Comment by wargio** [comment]
> `LIST_CODE_REFS_IDX`

Also remove lines from 215 to 218
```c
#define LIST_CODE_REFS "lcr"
#define LIST_CODE_REFS_ARGS " [addr]"
#define LIST_CODE_REFS_DESC "list all references to fields and methods in code sections"
#define LIST_CODE_REFS_LEN 3
```

**Comment by trufae** [comment]
This issue was introduced in 3ead80cca8a9e03ce4c755718d6772cf583d5716 i think the custom analysis of this plugin was more precise, but it's true that the default analysis should be the one handling everything in here. so im fine for removing this as long as the rest of the code was already removed.

**Review by wargio — APPROVED** [review]

**Review by ret2libc — APPROVED** [review]

**Pull request merged**
