### PR TITLE
r2r.v, BROKEN=0: Check only first char

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](../DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](../DEVELOPERS.md#code-style)
- [X] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](../../radare2book) with the relevant information (if needed)

**Detailed description**

This pr is to prevent surprise when unbreaking a test with a BROKEN comment. 

**Test plan**

r2r.v is OK (instead of FX) with the included "BROKEN=0 with comment" test.

**Closing issues**

See description.

### CODE REVIEW

**Comment by radare** [comment]
uhm r2r ends in red when all tests pass :? in local i have 1 XX and it returns 0 :_

**Comment by kazarmy** [comment]
https://travis-ci.com/radareorg/radare2/jobs/288027701

Travis_ban

https://ci.appveyor.com/project/radareorg/radare2/builds/30851502/job/9y6hwu3s3v9xk7ha

AppVeyor_ban

i'll try again tomorrow

**Comment by kazarmy** [comment]
restarted the AppVeyor build though

**Comment by kazarmy** [comment]
> Travis_ban

and "you" here apparently doesn't refer to me

**Comment by XVilka** [comment]
Can we just cache it, not to install it every time? It doesn't change often after all.

**Comment by kazarmy** [comment]
Hooray it's green :)

**Pull request merged**
