### PR TITLE
Add cfg.charset and the new pse command ##print

### PR DESCRIPTION
**Pull request by trufae**
**Checklist**

- [ ] Closing issues: #issue
- [x] Mark this if you consider it ready to merge
- [x] I've added tests (optional)
- [ ] I wrote some lines in the [radare2book](https://github.com/radareorg/radare2book)

**Description**

Implements the pse command and the cfg.charset configurarion variable.

**Future**

I think we can merge now and improve later. Stuff in my mind:

* move rcharset instance from core to print
* use it in the hexdump too
* maybe pse is not needed because the charset has been set once and must be applied everytime we process it for printing .. maybe laburious
* add a command to write.. this is write a string but encoding it using this translation table

335AA158-FAED-4826-ACAA-AD7FA440E53E

### CODE REVIEW

**Comment by trufae** [comment]
cc @gogo2464 @condret 

i did the changes i requrested in the other pr. this thing now needs testing and feedback. apart from that lgtm and dont wanna delay PRs that much anymore. Active interactions to contributors must be a thing to avoid frustration and stuck situations.

**Comment by gogo2464** [comment]
I am sorry. As I told I need time because I have a trouble with my partition [here ](https://github.com/radareorg/radare2/pull/16621#issuecomment-743978763). Can you just fork my repo and send me the pull request before I do my own PR? I would love to see the difference between what I did and your work in git.

**Comment by gogo2464** [comment]
By testing, do you mean unit test or just manual testing?

**Comment by gogo2464** [comment]
The issue [18059](https://github.com/radareorg/radare2/pull/18059) has been merged. You can cross the `move rcharset instance from core to print` in the future tab.

**Pull request merged**
