### PR TITLE
Fixes for #23579 and #23560

### PR DESCRIPTION
**Pull request by wgrr**
- [x] Mark this if you consider it ready to merge
- [x] I've added tests (optional)

**Description**

In dwarf5 it's not possible to use the same logic to add files to sdb_addrinfo, the 0'th index of directories is valid and emitted by compilers, currently we translate indexes from an array starting at 1 to 0, when a compiler emit a set_file opcode to 0 then the file wont be inserted in sdb_addrinfo because it would underflow, notably clang likes to emit set_file to 0. So i changed the file_names array to always have a minimum of 1 element, this makes the struct work for both dwarf versions, when `dwarf < 5` indexes start at 1 and the 0'th element is all zeros and unused, in dwarf 5 indexes start at 0 and _i think_ it's always present and is the compilation unit path.

Also `dwarf < 5` parser was inserting one extra slash between the base directory and the file, making the output inconsistent with `dwarf 5`, fixed that too and removed an out of date comment from the code.

we could also cleanup those path before inserting in sdb_addrinfo, like removing leading/trailing slash from paths, dot and dotdot that resolve to itself etc. i considered realpath(3) but Windows and i don't feel like it's a good ideia to resolve symlinks here.

### CODE REVIEW

**Comment by trufae** [comment]
use ##bin or ##dwarf

**Comment by trufae** [comment]
the file pathr esolution is another problem that is partly covered and maybe an open place to discussion because file paths can be in multiple places, and the user need to handle absolute and relative paths to them.. actually relative paths are needed for the CI to work, because we cant rely on absolute ones in CI systems.

Another issue is that there's no way to actually map the src/dst directories where to translate them. for example, maybe the bin have srces for libc in /home/blah/src/libc, but we want them in /opt/libc.. and other files are located in a different place. right now we can only override a global directory for flat files in there. not sure how complex or well we really want to cover this to not make it difficult to use

**Comment by wgrr** [comment]
> the file pathr esolution is another problem that is partly covered and maybe an open place to discussion because file paths can be in multiple places, and the user need to handle absolute and relative paths to them.. actually relative paths are needed for the CI to work, because we cant rely on absolute ones in CI systems.
> 

Does radare2 attempt to do something if the file pointed by dwarf exists on the users file system? I was thinking more in making  full resolved *dwarf paths* (no file system involved) printing nicer, ie `./foo/./bar.c` be cleaned up with `/foo/bar.c` and the like, just string cleanup, no filesystem involved

**Comment by wgrr** [comment]
Previous commit still using wrong output, just making sure the test passes. I will fix that later, the correct file output should be `/home/pancake/prg/radare2/libr/core/cfile.c` i think.

**Comment by trufae** [comment]
About the // and /./ rvc have this code https://github.com/radareorg/radare2/blob/e25d1beb23397520603ed78d98ed468698fe0abf/libr/util/rvc_rvc.c#L143 which we may want to move into libr/util/file.c after the next release and also handle /./ in there.

maybe we can generalize this function to also handle the abspath in a portable way, but i would probably think in a way for the user to specify via `k` a key=value list of paths to be replaced, so we can have a command to list all the directories used by the dwarf files loaded and where we want to be remapped. and ideally being able to do this automatically via dir.source so the user doesnt need to map all this by hand everytime. 

check this pad i created for further discussions on this topic https://github.com/radareorg/radare2/blob/e25d1beb23397520603ed78d98ed468698fe0abf/libr/util/rvc_rvc.c#L143

**Pull request merged**
