### PR TITLE
Add MacOS Meson build job

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

Checking if it helps with https://github.com/radareorg/radare2/issues/17870

### CODE REVIEW

**Review by trufae — APPROVED** [review]

**Comment by trufae** [comment]
Can you rebase so we get it green?

**Comment by XVilka** [comment]
And first bug in Meson/Ninja build configuration:
```
[1408/1535] Linking target binr/rarun2/rarun2.
FAILED: binr/rarun2/rarun2 
clang  -o binr/rarun2/rarun2 'binr/rarun2/c604330@@rarun2@exe/rarun2.c.o' -Wl,-dead_strip_dylibs -Wl,-undefined,error -Wl,-headerpad_max_install_names -Wl,-force_load libr2sdb.a -Wl,-force_load -Wl,-force_load -Wl,-force_load libr/main/libr_main.4.6.0.dylib libr/config/libr_config.4.6.0.dylib libr/cons/libr_cons.4.6.0.dylib libr/io/libr_io.4.6.0.dylib libr/util/libr_util.4.6.0.dylib libr2spp.a libr2zlib.a libr/flag/libr_flag.4.6.0.dylib libr/asm/libr_asm.4.6.0.dylib libr/core/libr_core.4.6.0.dylib libr/debug/libr_debug.4.6.0.dylib libr/hash/libr_hash.4.6.0.dylib libr/bin/libr_bin.4.6.0.dylib libr/lang/libr_lang.4.6.0.dylib libr/anal/libr_anal.4.6.0.dylib libr/parse/libr_parse.4.6.0.dylib libr/bp/libr_bp.4.6.0.dylib libr/egg/libr_egg.4.6.0.dylib libr/reg/libr_reg.4.6.0.dylib libr/search/libr_search.4.6.0.dylib libr/syscall/libr_syscall.4.6.0.dylib libr/socket/libr_socket.4.6.0.dylib libr/fs/libr_fs.4.6.0.dylib libr/magic/libr_magic.4.6.0.dylib libr/crypto/libr_crypto.4.6.0.dylib -ldl -lm -lutil -Wl,-headerpad_max_install_names -Wl,-rpath,@loader_path/../../libr/main -Wl,-rpath,@loader_path/../../libr/config -Wl,-rpath,@loader_path/../../libr/util -Wl,-rpath,@loader_path/../.. -Wl,-rpath,@loader_path/../../libr/cons -Wl,-rpath,@loader_path/../../libr/io -Wl,-rpath,@loader_path/../../libr/socket -Wl,-rpath,@loader_path/../../shlr -Wl,-rpath,@loader_path/../../shlr/gdb -Wl,-rpath,@loader_path/../../libr/hash -Wl,-rpath,@loader_path/../../libr/crypto -Wl,-rpath,@loader_path/../../libr/flag -Wl,-rpath,@loader_path/../../libr/asm -Wl,-rpath,@loader_path/../../libr/syscall -Wl,-rpath,@loader_path/../../libr/parse -Wl,-rpath,@loader_path/../../libr/reg -Wl,-rpath,@loader_path/../../libr/lang -Wl,-rpath,@loader_path/../../libr/core -Wl,-rpath,@loader_path/../../libr/search -Wl,-rpath,@loader_path/../../libr/anal -Wl,-rpath,@loader_path/../../libr/fs -Wl,-rpath,@loader_path/../../libr/magic -Wl,-rpath,@loader_path/../../libr/egg -Wl,-rpath,@loader_path/../../libr/debug -Wl,-rpath,@loader_path/../../libr/bp -Wl,-rpath,@loader_path/../../libr/bin
ld: warning: argument missing after -force_load
ld: file not found: -force_load
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[1409/1535] Linking target binr/rahash2/rahash2.
FAILED: binr/rahash2/rahash2 
```
cc @trufae @ret2libc

**Comment by ret2libc** [comment]
> And first bug in Meson/Ninja build configuration:
> ```
> [1408/1535] Linking target binr/rarun2/rarun2.
> FAILED: binr/rarun2/rarun2 
> clang  -o binr/rarun2/rarun2 'binr/rarun2/c604330@@rarun2@exe/rarun2.c.o' -Wl,-dead_strip_dylibs -Wl,-undefined,error -Wl,-headerpad_max_install_names -Wl,-force_load libr2sdb.a -Wl,-force_load -Wl,-force_load -Wl,-force_load libr/main/libr_main.4.6.0.dylib libr/config/libr_config.4.6.0.dylib libr/cons/libr_cons.4.6.0.dylib libr/io/libr_io.4.6.0.dylib libr/util/libr_util.4.6.0.dylib libr2spp.a libr2zlib.a libr/flag/libr_flag.4.6.0.dylib libr/asm/libr_asm.4.6.0.dylib libr/core/libr_core.4.6.0.dylib libr/debug/libr_debug.4.6.0.dylib libr/hash/libr_hash.4.6.0.dylib libr/bin/libr_bin.4.6.0.dylib libr/lang/libr_lang.4.6.0.dylib libr/anal/libr_anal.4.6.0.dylib libr/parse/libr_parse.4.6.0.dylib libr/bp/libr_bp.4.6.0.dylib libr/egg/libr_egg.4.6.0.dylib libr/reg/libr_reg.4.6.0.dylib libr/search/libr_search.4.6.0.dylib libr/syscall/libr_syscall.4.6.0.dylib libr/socket/libr_socket.4.6.0.dylib libr/fs/libr_fs.4.6.0.dylib libr/magic/libr_magic.4.6.0.dylib libr/crypto/libr_crypto.4.6.0.dylib -ldl -lm -lutil -Wl,-headerpad_max_install_names -Wl,-rpath,@loader_path/../../libr/main -Wl,-rpath,@loader_path/../../libr/config -Wl,-rpath,@loader_path/../../libr/util -Wl,-rpath,@loader_path/../.. -Wl,-rpath,@loader_path/../../libr/cons -Wl,-rpath,@loader_path/../../libr/io -Wl,-rpath,@loader_path/../../libr/socket -Wl,-rpath,@loader_path/../../shlr -Wl,-rpath,@loader_path/../../shlr/gdb -Wl,-rpath,@loader_path/../../libr/hash -Wl,-rpath,@loader_path/../../libr/crypto -Wl,-rpath,@loader_path/../../libr/flag -Wl,-rpath,@loader_path/../../libr/asm -Wl,-rpath,@loader_path/../../libr/syscall -Wl,-rpath,@loader_path/../../libr/parse -Wl,-rpath,@loader_path/../../libr/reg -Wl,-rpath,@loader_path/../../libr/lang -Wl,-rpath,@loader_path/../../libr/core -Wl,-rpath,@loader_path/../../libr/search -Wl,-rpath,@loader_path/../../libr/anal -Wl,-rpath,@loader_path/../../libr/fs -Wl,-rpath,@loader_path/../../libr/magic -Wl,-rpath,@loader_path/../../libr/egg -Wl,-rpath,@loader_path/../../libr/debug -Wl,-rpath,@loader_path/../../libr/bp -Wl,-rpath,@loader_path/../../libr/bin
> ld: warning: argument missing after -force_load
> ld: file not found: -force_load
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> [1409/1535] Linking target binr/rahash2/rahash2.
> FAILED: binr/rahash2/rahash2 
> ```
> cc @trufae @ret2libc 

I think you just have to install a newer version of meson. It could be on mac it is still using 0.52 due to a bug there was at some point

**Comment by XVilka** [comment]
The only problem now is the missing `shlr/www/index.html` file:
```
[XX] db/archos/darwin-x64/http =h
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc !scripts/test-webserver.sh --
-- stdout
@@ -17,14 +17,4 @@
             0x000006b6      lea rcx, sym.__libc_csu_init
             ; 0x81e
             0x000006bd      lea rdi, main
-<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
-<html xmlns="http://www.w3.org/1999/xhtml">
-<head>
-<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=false" />
-	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
-	<meta name="language" content="en" />
-
-	<title>radare2 webui</title>
-
-	<script type="text/javascript" src="m/vendors/jquery.min.js"></script>
-	<script type="text/javascript" src="m/r2.js"></script>
+File not found


-- stderr
```

**Comment by XVilka** [comment]
Don't forget to update "master" branch protection rules from `macos-clang-tests` to `macos-meson-clang-tests` and `macos-acr-clang-tests`.

**Pull request merged**
