### PR TITLE
Fix raspbian32 db/cmd/cmd_pf_elf

### PR DESCRIPTION
**Pull request by eagleoflqj**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

Random negative numbers #17898 

**Test plan**

`r2r db/cmd/cmd_pf_elf` on rpi4. No fail.

**Closing issues**

...

### CODE REVIEW

**Comment by XVilka** [comment]
Strange, should have been caught by the https://github.com/radareorg/radare2/commit/e20b1056e9fb1d96dc9bc3a2c281b30b8513362c

**Review by XVilka — APPROVED** [review]

**Comment by eagleoflqj** [comment]
> Strange, should have been caught by the [e20b105](https://github.com/radareorg/radare2/commit/e20b1056e9fb1d96dc9bc3a2c281b30b8513362c)

I guess that doesn't apply to function pointer here.

**Comment by XVilka** [comment]
You are right, I created new PR for checking callbacks too: https://github.com/radareorg/radare2/pull/17906

**Comment by XVilka** [comment]
I think this one can be closed in favor of more complete https://github.com/radareorg/radare2/pull/17906

**Comment by XVilka** [comment]
You could try to rerun the tests again.

**Pull request closed without merging**
