### PR TITLE
In cBPF jt and jf are unsigned, fix the code ##anal

### PR DESCRIPTION
**Pull request by infrastation**
- [x] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

### CODE REVIEW

**Comment by trufae** [comment]
@terorie can you review this PR?

**Comment by terorie** [comment]
@trufae LGTM 👍🏻 cBPF is a bit weird. jt and jf are jump offsets but they are unsigned indeed because backwards jumps are not allowed. In eBPF jump offsets are signed though. 
@infrastation Thank you for the contribution 🙌🏻

**Comment by trufae** [comment]
I'm happy with @terorie confirmation that the fix is good. So i'm merging because it was an awful bug, i'll wait for the tests in another pr, no stress :)

thanks!

**Comment by infrastation** [comment]
Alright, thank you!

**Pull request merged**
