### PR TITLE
x86-16 bit disasm print filter more tests

### PR DESCRIPTION
**Pull request by lasek0**
**Checklist**

- [ ] Closing issues: #issue
- [x] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [radare2book](https://github.com/radareorg/radare2book)

**Description**

added more tests for x86-16 bit disasm filter. unfortunatelly not all pass so I think that there is still something wrong with parsing.
in general when seg:off format is used in disasm and seg is = 0 then disassembly is wrong.

seg = 0 (wrong)
```
-        ,=< 0000:0005     ea0d000000     ljmp funcA
+        ,=< 0000:0005     ea0d000000     ljmp 0:funcA
```
```
-|           0000:0005     9a0d000000     lcall funcA
+|           0000:0005     9a0d000000     lcall 0:                      ; funcA
```

seg > 0 (good)
```
\       `=< 0000:0403      ea00000400     ljmp funcA
```
```
\           0000:0403      9a00000400     lcall funcA
```

this is probably because some previous replacement (before filter function) see that part of assembly mnemonic is a valid address and replace it ignoring seg:off format.

in general the filter function is now not a problem because the input (data argument) to filter function (libr/parse/filter.c) is like that (in case of 0 seg) `ljmp 0:funcA` or `lcall 0:funcA`

I will try fix that and will send a PR (this time in correct way I guess :smile:)

### CODE REVIEW

**Comment by trufae** [comment]
thats mking some tests red

```
-|           0000:0403     9a00000400     lcall funcA
401
+|           0000:0403     9a00000400     lcall 4, 0
```

**Comment by lasek0** [comment]
I know that. Problem is that I can not easly reproduce it locally. Need speend more time on this, But I will fix it eventually I guess. Hope You agree with me that r2 output is not good, and expected is correct. What I debug so far is that input to filter functuon looks like this `lcall 4, 0` which makes code detecting collon in seg:off format impossible. What is funny is that same thing works correctly for ljmp instr. What I plan is to merge x86-16 tests to that branch and close previous PR, to see how changes in that PR fix seg=0 Red tests.

**Comment by lasek0** [comment]
found that improper disassembly format (`lcall 4, 0`) is come from capstone in file libr/asm/p/asm_x86_cs.c, directly after cs_disasm I got following output as insn->mnemonic, insn->op_str () -> `lcall 4, 0`

the funny fact is that I have two r2 git repo locally, one official radare2 and one my radare2-fork, and on official radare2 I have improper format (`lcall 4, 0`) but on my fork I got proper format (`lcall 4:0`). I am sure that master of my fork is identical to the master of official r2 git repo.

what I found that my fork use this capstone repo https://github.com/aquynh/capstone.git
and official r2 use https://github.com/capstone-engine/capstone.git

when I clone capstone from same url as official r2, and switch to 'next' branch of capstone, then I got following output:

`lcall 4, 0`

and I think that official capstone-engine had a bug...

**Comment by trufae** [comment]
Please post this patch upstream in capstone

**Comment by lasek0** [comment]
done. https://github.com/capstone-engine/capstone/pull/1827

**Comment by kabeor** [comment]
merged in Capstone.

**Comment by trufae** [comment]
Uodate the commit hash in shlr/Makefile and libr/meson.build

**Comment by trufae** [comment]
Or rebase

**Comment by lasek0** [comment]
should be rebased now, but I am afraid that my last commit from PR in capstone will not fix that issue, because I need to update .inc files using llvm-tblgen, and somehow I have wrong version of llvm. I asked capstone team how to generate it properly.
my comment url: https://github.com/capstone-engine/capstone/pull/1827#issuecomment-1020579778

**Comment by lasek0** [comment]
as I afraid, generating inc files was not that straight forward thing. to push this topic further (since I do not want to spend time on reversing capstone build scripts) I will commit soon a temporary workaround just for that lcall for x86-16, and then when capstone will be complete fixed I will remove it.

**Pull request closed without merging**
