### PR TITLE
eprintln instead of eprint

### PR DESCRIPTION
**Pull request by radare**

### CODE REVIEW

**Comment by radare** [comment]
this macro is not used anywhere, but at least is not breaking the build of the V suite

**Comment by radare** [comment]
What do u think about eliminating eprint() instead of renaming it to eprintln()? it is just used in base85.c cc @ret2libc @thestr4ng3r

**Comment by thestr4ng3r** [comment]
Yeah, why not just replace the calls by eprintf?

**Comment by radare** [comment]
yeah kiss

**Pull request merged**
