### PR TITLE
Dont assert when no calling convention defined ##anal

### PR DESCRIPTION
**Pull request by trufae**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by thestr4ng3r** [comment]
Do you have some context about from where passing NULL here would make valid sense?

**Comment by thestr4ng3r** [comment]
Does it really make sense to make passing NULL valid here? Wouldn't it make more sense to check at the callsites?

**Comment by trufae** [comment]
Static builds of r2 dont have the calling conventions because there were moved from inside r2 to external SDB files. This is a known issue for a very long time, at least for me, i know the analysis of arguments will be wrong when no CC is found, but having a runtime assert for something that is loaded at runtime is a bad idea imho

**Comment by XVilka** [comment]
- https://gcc-renesas.com/manuals/SH-ABI-Specification.html
- https://devblogs.microsoft.com/oldnewthing/20190820-00/?p=102792

**Comment by thestr4ng3r** [comment]
Sure, there can always be cases where you don't have a cc. But the question is where exactly to check this. If the assert is removed there, meaning NULL is a "valid cc" for this API, then the asserts in all the other functions in this file must be removed too.

**Comment by ret2libc** [comment]
So, what have we chosen on this?

I'm personally against considering cc=NULL a valid cc, because when cc is null there is probably nothing we can really do, and probably a lot of features (all the vars/args stuff, etc.) can't work at all. Having cc=NULL as a valid cc would just mean that we "ignore" the problem and pretend everything is alright, when it actually isn't. I think we should find a better solution for this.

**Comment by radare** [comment]
R2 should have at least one CC per-arch hardcoded, not depending on .sdb files to work imho. i agree that getting rid of this "warning" is not a good idea, but maybe it should be an eprintf instead of a soft assert. that can be hidden behind anal.verbose

**Comment by kazarmy** [comment]
Pedantic me says that one should not even think of passing a NULL cc to a function named `r_anal_cc_arg` / `r_anal_cc_max_arg`. Practical me says that one should not be so pedantic.

**Comment by trufae** [comment]
Uhm, i see this warning now. shouldnt this pr get merged to be consistent?

```
$ r2 -a tms320 -
WARNING: No calling convention defined for this file, analysis may be inaccurate.
 -- Prove you are a robot to continue ...
[0x00000000]> 

```

**Comment by ret2libc** [comment]
@trufae do you see double warnings?

**Comment by trufae** [comment]
No, asserts are not happening anymore. But imho we should cover all generic calling conventrions inside r2 without depending on loading runtime sdb files

**Comment by thestr4ng3r** [comment]
One option would be to automatically try to derive a fallback cc from the register profile.

**Comment by trufae** [comment]
Yeah that would be easy to do and work in some cases. But ideally we may be able to embed any arbitrary list of calling conventions and type info into the binary

**Comment by trufae** [comment]
Let's close this, the right fix is somewhere else

**Comment by trufae** [comment]
aka in another castle

**Pull request closed without merging**
