### PR TITLE
Initial implementation of the annotation parser for DEX ##bin

### PR DESCRIPTION
**Pull request by radare**
https://dzone.com/articles/creating-custom-annotations-in-java

Screenshot 2019-07-07 at 17 35 22

[call-fun.zip](https://github.com/radare/radare2/files/3365827/call-fun.zip)

```json
$ jq . foo/sources/defpackage/Call.json
{
  "package": "defpackage",
  "type": "interface",
  "implements": [
    "java.lang.annotation.Annotation"
  ],
  "dex": "Call.dex",
  "fields": [],
  "methods": [
    {
      "signature": "stuAddress()Ljava/lang/String;",
      "return-type": "java.lang.String",
      "arguments": [],
      "lines": [],
      "offset": "0x0",
      "name": "stuAddress",
      "declaration": "String stuAddress()",
      "access-flags": 1025
    },
    {
      "signature": "stuStream()Ljava/lang/String;",
      "return-type": "java.lang.String",
      "arguments": [],
      "lines": [],
      "offset": "0x0",
      "name": "stuStream",
      "declaration": "String stuStream() default \"CSE\"",
      "access-flags": 1025
    },
    {
      "signature": "studentAge()I",
      "return-type": "int",
      "arguments": [],
      "lines": [],
      "offset": "0x0",
      "name": "studentAge",
      "declaration": "int studentAge() default 18",
      "access-flags": 1025
    },
    {
      "signature": "studentName()Ljava/lang/String;",
      "return-type": "java.lang.String",
      "arguments": [],
      "lines": [],
      "offset": "0x0",
      "name": "studentName",
      "declaration": "String studentName()",
      "access-flags": 1025
    }
  ],
  "imports": [
    "java.lang.annotation.Documented",
    "java.lang.annotation.ElementType",
    "java.lang.annotation.Inherited",
    "java.lang.annotation.Retention",
    "java.lang.annotation.RetentionPolicy",
    "java.lang.annotation.Target"
  ],
  "name": "Call",
  "alias": "defpackage.Call",
  "declaration": "@Inherited\n@Documented\n@Target({ElementType.METHOD})\n@Retention(RetentionPolicy.RUNTIME)\n/* renamed from: Call reason: default package */\npublic @interface Call ",
  "access-flags": 9729
}
```

### CODE REVIEW

**Comment by radare** [comment]
Right now:

```
$ r2 /tmp/Call.dex
Parse annotations
0x00000178  annotationOffset
0x00000160  classAnnotationOffset
            className LCall;
            fieldsCount 0
            annotatedMethodCount  0
            annotatedParametersCount  0
Visibility: SYSTEM
TypeSize: 2 1 (I)
ITEM 1 Call.java
Visibility: RUNTIME
TypeSize: 6 0 (Ljava/lang/Object;)
Visibility: RUNTIME
TypeSize: 8 0 (Ljava/lang/annotation/Annotation;)
Visibility: RUNTIME
TypeSize: 9 1 (Ljava/lang/annotation/Documented;)
Visibility: RUNTIME
TypeSize: 11 1 (Ljava/lang/annotation/Inherited;)
[0x0000035d]>
```

**Comment by radare** [comment]
defaults are still not supported, we need a way to store this info.. probably better to just hold it inside sdb for now. but ideally we must hint all the headers with proper info. we need data analysis structures like we have for code (structs vs bb, references vs pointers ,...)

**Comment by radare** [comment]
ill rebase and continue this PR when the dex refactor gets merged

**Comment by radare** [comment]
so many conflicts now

**Comment by ret2libc** [comment]
Closing. This had no review, no changes, no nothing for a long time. I'm closing the PR as there is no benefit in keeping this open. The branch will still be active, so if @trufae wants he can continue working on this when he has time. No need to keep it in the backlog.

**Comment by radare** [comment]
This is a very important PR, if it has no reviews is not my fault. It was my next item in the list after fixing all the COVs in DEX, because there were conflicts and this is a huge patch, which needs tests and so on. main reason why this wasnt merged was performance, because DEX was loading too slow at the time and this was making it even slower. Now it shuold be fine again. I'm reopening because i never abandon anything and yes, i would appreciate a review when rebased

**Comment by ret2libc** [comment]
> This is a very important PR, if it has no reviews is not my fault. It was my next item in the list after fixing all the COVs in DEX, because there were conflicts and this is a huge patch, which needs tests and so on. main reason why this wasnt merged was performance, because DEX was loading too slow at the time and this was making it even slower. Now it shuold be fine again. I'm reopening because i never abandon anything and yes, i would appreciate a review when rebased

Please notice I did not say this is not important, that I don't want to review it, see this merged or anything like this. I did not intend to even block you from keeping working on this. It's just that it was created 1 year ago, it was stale for a long while and it has conflicts and what not. Nobody prevents you from moving this forward, but if a PR has been opened for more than ~5 months without updates, with conflicts, without active comments/review from people... maybe it wasn't just ready enough to be a "Pull Request". Maybe it was still just some development you were doing. When that development reaches a good enough state it makes sense to create the PR and asks others to review.

**Comment by trufae** [comment]
ive solved the conflicts and rebased, but github keeps saying there are conflicts. this happned to me once. ill wait a bit and create a new pr if that doesnt work

**Comment by trufae** [comment]
Tests are green now... but the fuzz step fails
Screenshot 2021-01-04 at 12 39 59

**Comment by trufae** [comment]
ill rebase after merging https://github.com/radareorg/radare2/pull/18170/checks?check_run_id=1645041246

but the suite looks pretty green. i think i will do some more testing before merging, because it's about the time

**Pull request merged**
