### PR TITLE
Move test/scripts into test/bins/src

### LINKED ISSUE #16576: Move test/scripts into test/bins/src

### PR DESCRIPTION
**Pull request by valdaarhun**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

Contents of `test/scripts` have been moved into `test/bins/src`

**Test plan**

...

**Closing issues**

closes #16576 
...

### CODE REVIEW

**Comment by trufae** [comment]
bins live in a separate repository https://github.com/radareorg/radare2-testbins, you cant just move those files, also there are several tests depending on those scripts to work. the PR should be done first in the other repository

**Comment by valdaarhun** [comment]
@trufae Hi. Sorry for the mess-up, looks like there was some huge confusion on my part. 

There is a folder called `src` in the `radare2-testbins` repository. Should I move the contents of `test/scripts` into that folder?

**Comment by trufae** [comment]
Yes. I think that makes sense

**Comment by valdaarhun** [comment]
I have moved the contents of `test/scripts` into the `src` directory in the `radare2-testbins` repository.

**Comment by trufae** [comment]
Please update this PR im afraid of merging this and lose/break tests in the process. i will check it out after doing the release.

**Comment by valdaarhun** [comment]
Yep, I am in fact doing it right now.

**Comment by valdaarhun** [comment]
In the file `test/db/archos/darwin-x64/http`, on line 3, should `CMDS=!!scripts/test-webserver.sh` be changed to `CMDS=!!bins/src/test-webserver.sh`?

**Comment by valdaarhun** [comment]
There were several changes that had been made in several files before updating this PR. So I though it would be more convenient to open a new PR with all the required commits there. Here's the new PR: #18031

**Pull request closed without merging**
