### PR TITLE
Fix running arch specific tests in r2r

### PR DESCRIPTION
**Pull request by koyaan**
- [X] Mark this if you consider it ready to merge

commit d032c6955508f1303a972be51dee8444224ed97f broke running arch specific test since the test folders do not match anymore.
This also adds bits to folder names
```
WARN: Skipping db/extras because it requires additional dependencies
ERROR: Skipping db/archos/windows-x86_64 because it does not match the current platform "linux-x86_64"
ERROR: Skipping db/archos/darwin-x86_64 because it does not match the current platform "linux-x86_64"
```

### CODE REVIEW

**Comment by koyaan** [comment]
`test/db/archos/linux-x86_64linux` results:
`[148/148]                82 OK        15 BR       51 XX        0 F`

**Comment by trufae** [comment]
umf so maybe better not to run those tests until they pass, or at least mark them as broken. also there are many FX ones that should be marked as unbroken

**Comment by koyaan** [comment]
Looks like the `cmd_dx` tests take 1 hour...
```
Wed, 20 Dec 2023 20:19:23 GMT[775/839] db/archos/linux-x86_64/dbg_fds 14897 OK 1065 BR 0 XX 17 FX
Wed, 20 Dec 2023 21:19:18 GMT[776/832] db/archos/linux-x86_64/cmd_dx 14902 OK 1068 BR 0 XX 17 FX
```

**Comment by trufae** [comment]
this 1h... seems to be like a timeout somewhere :/

if you download the r2r.json from the artifacts you can see how long it needs each test to run. thing is... i dont see the dbg tests in that file.. and i guess thats because the results.json is not published as an artifact. can you give it a look.

also iirc theres no way to disable a test. so slow tests should be commented with `#` good work!

**Comment by koyaan** [comment]
Just replicated the whole test run in an Ubuntu 20.04 VM, 
`Finished in 8 minutes and 31 seconds.` 
Really weird

**Comment by trufae** [comment]
ive implemented the NORUN directive in r2r https://github.com/radareorg/radare2/pull/22511

**Comment by trufae** [comment]
Screenshot 2023-12-22 at 01 19 27

**Comment by koyaan** [comment]
image
omg :D

**Comment by trufae** [comment]
It’s over 9000!!!1!1

**Comment by koyaan** [comment]
Finally tests run in a reasonable amount of time! 3min 31s

**Comment by trufae** [comment]
What was it? Can you squash/split the last commits?

**Comment by trufae** [comment]
I can squash them all too if its ok for you

**Comment by koyaan** [comment]
last fix done, squashed and should be ready to go

**Pull request merged**
