### PR TITLE
Add initial implementation of agfm command ##anal

### PR DESCRIPTION
**Pull request by swoops**
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

Initial implementation of `agfm` command. This outputs the current functions cfg in mermaid syntax. Apparently github accepts this now. So for the following function

```
[0x00017950]> agfb
⠈⠉⠉⠉⠉⠉⠉⠉⠉⠉⢹⣻⣿⣟⣛⣛⣛⣒⣒⣒⣒⣒⣒⣒⣒⣲⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣟⡛⠛⠛⠃⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣒⣂⣀⣀⣀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⠶⠶⠶⠖⠒⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣛⣃⣀⣀⡀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⡤⠤⠤⠤⠤⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⠭⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣟⠉⠉⠉⠀⠀⠀⠀⠀⠀⠀⢸⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⠿⢿⡿⠥⠤⠤⠤⠤⠤⠤⠤⠤⠤⠤⠼⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⢷⠒⠒⠒⠒⠒⠒⠒⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣽⣿⣯⡭⠉⡇⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⠛⢻⡟⠒⠒⠃⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⢀⣰⣒⣒⣒⣒⣒⣒⣚⡉⠉⠉⠉⠉⡇⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⢸⣾⣿⣷⣖⣒⣒⡒⠀⡇⠀⠀⠀⠀⡇⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠘⠛⢻⡟⠒⠒⠒⠒⠒⠃⠀⠀⠀⠀⡇⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⣀⣖⣒⣒⣚⣉⢉⣹⣀⣀⣀⣀⣀⣀⣀⡀⡇⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⣷⣿⣿⣒⠀⢸⢸⣾⣿⣗⡒⠒⠒⠒⠀⡇⡇⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠉⡏⠉⠉⠉⠉⠘⢻⠛⠛⠒⠒⠒⠒⠒⠃⡇⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⢀⣉⣷⣒⣒⣒⣒⣚⣀⣀⣀⣀⣀⡀⠀⠀⡇⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⢸⣿⣿⡶⠖⠒⠒⠒⠒⠒⠒⠒⠒⡇⠀⠀⡇⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠈⠉⢹⣏⣉⣉⣉⣉⣉⣉⣉⣉⣉⣁⣀⣀⣇⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠈⠉⠉⠉⠉⢹⠀⠀⠀⠀⠀⠀⠀⠀⠓⢿⣦⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣽⣿⣯⣭⣭⣍⡉⠉⡇⣯⣿⣿⡭⠭⠭⠉⠉⠉⠉⠉⠉⠉⢹⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣷⣶⣶⣖⠀⡇⠿⠿⠿⠿⠯⠭⠭⠭⠭⠭⠭⠭⠭⠽⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⠿⠿⠿⠷⠶⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣧⣀⣀⣀⣀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣉⣉⣉⣉⣁⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⣀⣀⣀⣀⣀⣀⣀⣸⠧⠤⠤⠤⠤⠤⠤⠤⠤⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⣶⣷⣖⣒⣒⣒⣒⡒⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⣿⣿⣯⣍⣉⣉⣉⡁⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠛⢻⡟⠒⠒⠒⠒⠒⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⣤⣯⡭⠭⠭⠭⠭⠭⡍⠉⠉⠉⠉⠉⠉⠉⠉⡇⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⣿⣿⣿⣭⣭⣭⣅⡀⡇⠀⠀⠀⠀⠀⠀⠀⠀⡇⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠛⠛⣿⠒⠒⠒⠒⠒⠃⠀⠀⠀⠀⠀⠀⠀⠀⡇⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⣀⣖⣒⣒⣒⣒⣋⣉⡉⢉⣹⣀⣀⣀⣀⠀⠀⠀⠀⠀⠀⡇⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠
⣿⣿⡷⠖⠒⠒⠒⠂⡇⢸⣿⣿⣒⠀⢸⠀⠀⠀⠀⠀⠀⡇⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸
⠛⡟⠛⠓⠒⠒⠒⠒⠃⠈⢹⠉⠉⠉⠉⠀⠀⠀⠀⠀⠀⡇⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈
⠀⠉⠉⠉⠉⠉⠉⠉⢹⣶⣾⣤⣤⣤⣤⣤⣤⣤⣤⣤⣤⣇⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⣶⣾⣟⣓⣒⣒⣒⣒⣒⣒⣒⣒⣒⣒⣒⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⡯⠭⠭⠭⠅⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⣿⣿⡏⠉⠉⠉⠉⠁⠀⠀⠀⠀⠀⠀⠀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⣿⣟⣃⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀

```
The mermaid output (so far) looks like:
```
stateDiagram-v2
        state "ENTRY: 0x17950" as _0x17950
        state "0x1799d" as _0x1799d
        state "0x179aa" as _0x179aa
        state "0x179bb" as _0x179bb
        state "0x179c3" as _0x179c3
        state "0x179cc" as _0x179cc
        state "0x17a09" as _0x17a09
        state "0x17a1e" as _0x17a1e
        state "0x17a40" as _0x17a40
        state "0x17a50" as _0x17a50
        state "0x17a62" as _0x17a62
        state "0x17a70" as _0x17a70
        state "0x17a77" as _0x17a77
        _0x17950 --> _0x17a77: true
        _0x17950 --> _0x1799d: false
        _0x1799d --> _0x17a77: true
        _0x1799d --> _0x179aa: false
        _0x179aa --> _0x17a40: true
        _0x179aa --> _0x179bb: false
        _0x179bb --> _0x179c3
        _0x179c3 --> _0x17a77: true
        _0x179c3 --> _0x179cc: false
        _0x179cc --> _0x17a1e: true
        _0x179cc --> _0x17a09: false
        _0x17a09 --> _0x17a50: true
        _0x17a09 --> _0x17a1e: false
        _0x17a40 --> _0x179c3
        _0x17a50 --> _0x17a70: true
        _0x17a50 --> _0x17a62: false
        _0x17a62 --> _0x17a1e
        _0x17a70 --> _0x17a1e
        _0x17a77 --> _0x17a80
```

Which adding the `mermaid` part to the MD here gives us a graph:
```mermaid
stateDiagram-v2
        state "ENTRY: 0x17950" as _0x17950
        state "0x1799d" as _0x1799d
        state "0x179aa" as _0x179aa
        state "0x179bb" as _0x179bb
        state "0x179c3" as _0x179c3
        state "0x179cc" as _0x179cc
        state "0x17a09" as _0x17a09
        state "0x17a1e" as _0x17a1e
        state "0x17a40" as _0x17a40
        state "0x17a50" as _0x17a50
        state "0x17a62" as _0x17a62
        state "0x17a70" as _0x17a70
        state "0x17a77" as _0x17a77
        _0x17950 --> _0x17a77: true
        _0x17950 --> _0x1799d: false
        _0x1799d --> _0x17a77: true
        _0x1799d --> _0x179aa: false
        _0x179aa --> _0x17a40: true
        _0x179aa --> _0x179bb: false
        _0x179bb --> _0x179c3
        _0x179c3 --> _0x17a77: true
        _0x179c3 --> _0x179cc: false
        _0x179cc --> _0x17a1e: true
        _0x179cc --> _0x17a09: false
        _0x17a09 --> _0x17a50: true
        _0x17a09 --> _0x17a1e: false
        _0x17a40 --> _0x179c3
        _0x17a50 --> _0x17a70: true
        _0x17a50 --> _0x17a62: false
        _0x17a62 --> _0x17a1e
        _0x17a70 --> _0x17a1e
        _0x17a77 --> _0x17a80
```

## TODO:
* add assembly into each block
* handle switch cases

I don't know when I will get that done, maybe tomorrow? Switches should be really easy to add. So if you want to wait for me to add to this, that is fine.

### CODE REVIEW

**Comment by trufae** [comment]
can you add a test? this looks amazing <3 very nice contribution!

**Comment by swoops** [comment]
Added a test, that graph looks even better I think:

```mermaid
stateDiagram-v2
       state "ENTRY: 0x15cc0" as _0x15cc0
       state "0x15d06" as _0x15d06
       state "0x15d12" as _0x15d12
       state "0x15d29" as _0x15d29
       state "0x15d67" as _0x15d67
       state "0x15d7e" as _0x15d7e
       state "0x15da0" as _0x15da0
       state "0x15db5" as _0x15db5
       state "0x15dc9" as _0x15dc9
       state "0x15dd0" as _0x15dd0
       state "0x15dd5" as _0x15dd5
       state "0x15dda" as _0x15dda
       state "0x15de3" as _0x15de3
       state "0x15df0" as _0x15df0
       state "0x15df6" as _0x15df6
       _0x15cc0 --> _0x15db5: true
       _0x15cc0 --> _0x15d06: false
       _0x15d06 --> _0x15db5: true
       _0x15d06 --> _0x15d12: false
       _0x15d12 --> _0x15db5: true
       _0x15d12 --> _0x15d29: false
       _0x15d29 --> _0x15d7e: true
       _0x15d29 --> _0x15d67: false
       _0x15d67 --> _0x15da0: true
       _0x15d67 --> _0x15d7e: false
       _0x15da0 --> _0x15d7e
       _0x15db5 --> _0x15df6: true
       _0x15db5 --> _0x15dc9: false
       _0x15dc9 --> _0x15dd0
       _0x15dd0 --> _0x15dda: true
       _0x15dd0 --> _0x15dd5: false
       _0x15dd5 --> _0x15df0: true
       _0x15dd5 --> _0x15dda: false
       _0x15dda --> _0x15dd0: true
       _0x15dda --> _0x15de3: false
```

**Comment by trufae** [comment]
Can this be reused for `agn/age` usage? that would be ideal :) as well as having a way to load the markdown graphs as agn/age commands, this way we can use the mermaid syntax in r2slides :D

**Comment by swoops** [comment]
> Can this be reused for `agn/age` usage? that would be ideal :) as well as having a way to load the markdown graphs as agn/age commands, this way we can use the mermaid syntax in r2slides :D

I should be able to do at least some of these things. Going mermaid to r2 will be a bit harder but is doable. I am going to update this code first to support a couple other things. Then it would be cool to get it working with call graphs, dependency tree's, etc

**Comment by iGio90** [comment]
looks dope! GJ!

**Pull request merged**
