### PR TITLE
Add s390x reg profile

### PR DESCRIPTION
**Pull request by radare**

### CODE REVIEW

**Comment by XVilka** [comment]
Much better, but still not enough to fix the build:
```
p/debug_native.c: In function ‘r_debug_native_bp’:
p/debug_native.c:1453:10: warning: unused variable ‘dbg’ [-Wunused-variable]
  RDebug *dbg = bp->user;
          ^~~
p/debug_native.c: At top level:
p/debug_native.c:1652:2: warning: #warning Unsupported architecture [-Wcpp]
 #warning Unsupported architecture
  ^~~~~~~
p/debug_native.c:1263:13: warning: ‘set_drx_regs’ defined but not used [-Wunused-function]
 static void set_drx_regs (RDebug *dbg, drxt *regs, size_t num_regs) {
             ^~~~~~~~~~~~
p/debug_native.c:1237:13: warning: ‘sync_drx_regs’ defined but not used [-Wunused-function]
 static void sync_drx_regs (RDebug *dbg, drxt *regs, size_t num_regs) {
             ^~~~~~~~~~~~~
p/debug_native.c:95:12: warning: ‘r_debug_handle_signals’ defined but not used [-Wunused-function]
 static int r_debug_handle_signals(RDebug *dbg) {
            ^~~~~~~~~~~~~~~~~~~~~~
p/native/linux/linux_debug.c: In function ‘print_fpu’:
p/native/linux/linux_debug.c:931:2: warning: #warning print_fpu not implemented for this platform  -Wcpp]
 #warning print_fpu not implemented for this platform
  ^~~~~~~
p/native/linux/linux_debug.c: In function ‘linux_reg_read’:
p/native/linux/linux_debug.c:1025:3: warning: #warning getfpregs not implemented for this platform [-Wcpp]
  #warning getfpregs not implemented for this platform
   ^~~~~~~
p/native/linux/linux_debug.c:1032:4: error: unknown type name ‘R_DEBUG_REG_T’; did you mean ‘R_BUF_SET’?
    R_DEBUG_REG_T regs;
    ^~~~~~~~~~~~~
    R_BUF_SET
p/native/linux/linux_debug.c:1049:31: error: ‘PTRACE_GETREGS’ undeclared (first use in this function); did you mean ‘PTRACE_GETREGSET’?
    ret = r_debug_ptrace (dbg, PTRACE_GETREGS, pid, NULL, &regs);
                               ^~~~~~~~~~~~~~
                               PTRACE_GETREGSET
p/native/linux/linux_debug.c:1049:31: note: each undeclared identifier is reported only once for each function it appears in
p/native/linux/linux_debug.c:936:7: warning: variable ‘showfpu’ set but not used [-Wunused-but-set-variable]
  bool showfpu = false;
       ^~~~~~~
p/native/linux/linux_debug.c: In function ‘linux_reg_write’:
p/native/linux/linux_debug.c:1127:34: error: ‘PTRACE_SETREGS’ undeclared (first use in this function); did you mean ‘PTRACE_SETREGSET’?
   int ret = r_debug_ptrace (dbg, PTRACE_SETREGS, pid, 0, (void*)buf);
                                  ^~~~~~~~~~~~~~
                                  PTRACE_SETREGSET
At top level:
p/native/linux/linux_debug.c:843:13: warning: ‘print_fpu’ defined but not used [-Wunused-function]
 static void print_fpu(void *f){
             ^~~~~~~~~
make[4]: *** [p/native/linux/linux_debug.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [foo] Error 2
make[2]: *** [debug] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2
```

**Comment by radare** [comment]
We need a shell on a s390x machine to do that. Othwrwise its black magic. Can we shell into this travis run?

Also we dont even support disassembling this arch. Its only supported by objdump afaik. Any volunteers? Also, can we get some bins out of this travis task for testing s390x? I dont think we have any

**Comment by XVilka** [comment]
Yes, it is possible: https://docs.travis-ci.com/user/running-build-in-debug-mode/

**Comment by radare** [comment]
another blind commit

**Pull request merged**
