### PR TITLE
Fix wrong format for long

### PR DESCRIPTION
**Pull request by eagleoflqj**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

%li instead of %i

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by XVilka** [comment]
Ideally, it should be like the rest of radare2 - PFMT64d. Not sure how to
handle imported sources like this though.

**Comment by eagleoflqj** [comment]
Would you follow upstream changes? If so I should try to commit to mpc directly.

**Comment by XVilka** [comment]
Yes, we synchronize with the mainstream periodically.

**Comment by radare** [comment]
imho those variables shuld be size_t instead of long. from my experience mpc have a very bad coding quality, we have done many fixes on it . and git log doesnt shows any sync. cc @thestr4ng3r

**Pull request merged**
