### PR TITLE
WIP Try MSVC 2019 for AppVeyor ##build

### PR DESCRIPTION
**Pull request by XVilka**

### CODE REVIEW

**Comment by pelijah** [comment]
изображение

**Comment by XVilka** [comment]
OK, latest meson still doesn't support VS2019: https://github.com/mesonbuild/meson/issues/4640  (will be solved as part of 50.1 release).

**Comment by pelijah** [comment]
You should remove `Preview`, not `Community`

**Comment by pelijah** [comment]
Hmm weird

**Comment by XVilka** [comment]
@pelijah no, path is right, it is meson problem - see the output:
```
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.0.0-pre.2.1
** Copyright (c) 2018 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
[r2-meson][DEBUG]: Root: C:\projects\radare2-shvdd
[r2-meson][DEBUG]: Meson: ['C:\\Python37-x64\\Scripts\\meson.exe']
[r2-meson][DEBUG]: Version: 3.4.0-git
[r2-meson][DEBUG]: Arguments: Namespace(alias=False, asan=False, backend='vs2019', dir='build', install='radare2-vs2019_64-3.4.0-git', nosudo=False, options=['static_runtime=true'], prefix='C:\\projects\\radare2-shvdd\\build\\priv_install_dir', project=False, pull=False, release=True, shared=False, symstall=False, uninstall=False, xp=True)
[r2-meson][INFO]: Building radare2
[r2-meson][DEBUG]: Invoking meson: ['C:\\Python37-x64\\Scripts\\meson.exe', 'C:\\projects\\radare2-shvdd', 'C:\\projects\\radare2-shvdd\\build', '--prefix=C:\\projects\\radare2-shvdd\\build\\priv_install_dir', '--backend=vs2019', '--buildtype=release', '--default-library=static', '-Dstatic_runtime=true']
usage: meson setup [-h]
                   [--buildtype {plain,debug,debugoptimized,release,minsize,custom}]
                   [--strip] [--unity {on,off,subprojects}] [--prefix PREFIX]
                   [--libdir LIBDIR] [--libexecdir LIBEXECDIR] [--bindir BINDIR]
                   [--sbindir SBINDIR] [--includedir INCLUDEDIR]
                   [--datadir DATADIR] [--mandir MANDIR] [--infodir INFODIR]
                   [--localedir LOCALEDIR] [--sysconfdir SYSCONFDIR]
                   [--localstatedir LOCALSTATEDIR]
                   [--sharedstatedir SHAREDSTATEDIR] [--werror]
                   [--warnlevel {0,1,2,3}] [--layout {mirror,flat}]
                   [--default-library {shared,static,both}]
                   [--backend {ninja,vs,vs2010,vs2015,vs2017,xcode}]
                   [--stdsplit] [--errorlogs] [--install-umask INSTALL_UMASK]
                   [--auto-features {enabled,disabled,auto}]
                   [--optimization {0,g,1,2,3,s}] [--debug]
                   [--wrap-mode {default,nofallback,nodownload,forcefallback}]
                   [-D option] [--cross-file CROSS_FILE]
                   [--native-file NATIVE_FILE] [-v] [--fatal-meson-warnings]
                   [--reconfigure] [--wipe]
                   [builddir] [sourcedir]
meson setup: error: argument --backend: invalid choice: 'vs2019' (choose from 'ninja', 'vs', 'vs2010', 'vs2015', 'vs2017', 'xcode')
[r2-meson][ERROR]: Meson error. Exiting.
Command exited with code 1
```

**Comment by XVilka** [comment]
Waiting when https://github.com/mesonbuild/meson/pull/5064 will be merged

**Comment by thestr4ng3r** [comment]
CMake supports it since 3.14, just saying ¯\\_(ツ)_/¯
https://cmake.org/cmake/help/v3.14/generator/Visual%20Studio%2016%202019.html

**Comment by XVilka** [comment]
@thestr4ng3r it will be the part of the next bugfix Meson release - 0.50.1, so not really much of a difference.

**Comment by thestr4ng3r** [comment]
I'm just trolling

**Comment by XVilka** [comment]
Now it depends on this https://github.com/mesonbuild/meson/pull/5252 being merged.

**Comment by XVilka** [comment]
Meson now supports VS2019 completely. Only a couple issues until 0.50.1, and waiting until AppVeyor updates its VS2019 image. Then should be ready to merge.

**Comment by XVilka** [comment]
Hmm, quite strange errorr now:
```
Проект "C: \ projects \ radare2-shvdd \ build \ radare2.sln" (1) строит "C: \ projects \ radare2-shvdd \ build \ libr \ syscall \ d \ 09a402f @@ s110-arm- 16.sdb@cus.vcxproj "(178) на узле 1 (цели по умолчанию).
   178> Проект "C: \ projects \ radare2-shvdd \ build \ libr \ syscall \ d \ 09a402f @@ s110-arm-16.sdb @ cus.vcxproj" (178) строит "C: \ projects \ radare2-" shvdd \ build \ REGEN.vcxproj "(3: 123) на узле 1 (цели по умолчанию).
     3> C: \ Program Files (x86) \ Microsoft Visual Studio \ 2019 \ Preview \ MSBuild \ Current \ Bin \ Microsoft.Common.CurrentVersion.targets (2817,7): ошибка MSB4057: цель "CreateManifestResourceNames" не существует в проекте. [C: \ projects \ radare2-shvdd \ build \ REGEN.v cxproj]
     3> Готово Создание проекта "C: \ projects \ radare2-shvdd \ build \ REGEN.vcxproj" (цели по умолчанию) - СБОЙ.
   178> Готово Создание проекта "C: \ projects \ radare2-shvdd \ build \ libr \ syscall \ d \ 09a402f @@ s110-arm-16.sdb @ cus.vcxproj" (цели по умолчанию) - СБОЙ.
```

**Comment by radare** [comment]
ping

**Comment by XVilka** [comment]
@radare it doesn't depend on us - AppVeyor still didn't update their VMs. We should wait until they do this:  https://github.com/appveyor/ci/milestone/144

**Comment by XVilka** [comment]
Quite strange error now:
```
     3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(379,5): error MSB8020: The build tools for v142_xp (Platform Toolset = 'v142_xp') cannot be found. To build using the v142_xp build tools, please install v142_xp build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\projects\radare2-shvdd\build\REGEN.vcxproj]
     3>Done Building Project "C:\projects\radare2-shvdd\build\REGEN.vcxproj" (default targets) -- FAILED.
     2>Done Building Project "C:\projects\radare2-shvdd\build\shlr\cafa177@@r2capstone@sta.vcxproj" (default targets) -- FAILED.
```

Seems related to https://stackoverflow.com/questions/55509980/build-fails-for-c-cx-project-with-v141-platform-toolset-in-visual-studio-2019

**Comment by XVilka** [comment]
Created an issue in AppVeyor https://github.com/appveyor/ci/issues/2944

**Comment by XVilka** [comment]
Everything is fixed now, except missing Inno Setup to form installers in VS2019 image. See https://github.com/appveyor/ci/issues/2948

**Comment by radare** [comment]
ping

**Comment by XVilka** [comment]
Don't ping on this one, told you - it totally depends on Appveyor to install that program.

**Comment by XVilka** [comment]
See also https://github.com/appveyor/ci/issues/3009 (MSYS2 request for AppVeyor)

**Comment by XVilka** [comment]
It consistently fails with
```
[XX] db\cmd\cmd_pB pxb 8  782
$ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -i C:\Users\appveyor\AppData\Local\Temp\1\tmp-4140ahd00Pea0NXd -
pxb 8
-0x00000000 0000.0000  0000.0000  0000.0000  0000.0000  0x00000000  ....
-0x00000004 0000.0000  0000.0000  0000.0000  0000.0000  0x00000000  ....
+0x00000000 0000.00000  0000.00000  0000.00000  0000.00000  0x00000000  ....
+0x00000004 0000.00000  0000.00000  0000.00000  0000.00000  0x00000000  ....
EXPECT=<<EOF
0x00000000 0000.00000  0000.00000  0000.00000  0000.00000  0x00000000  ....
0x00000004 0000.00000  0000.00000  0000.00000  0000.00000  0x00000000  ....
```

**Comment by XVilka** [comment]
@GustavoLCR maybe you can check this one?

**Comment by XVilka** [comment]
Oh, nevermind, it's still memmove bug, sorry for disturbing.

**Comment by XVilka** [comment]
Depends on https://github.com/appveyor/ci/issues/3093

**Comment by XVilka** [comment]
OK, it passes the problematic test. There is still failing https://github.com/radareorg/radare2/issues/15147 but it fails on master too. Merging then.

**Pull request merged**
