### PR TITLE
Fix first r_anal_op call after asm.bits change

### PR DESCRIPTION
**Pull request by thestr4ng3r**

### CODE REVIEW

**Comment by radare** [comment]
do you have a test case?

**Comment by thestr4ng3r** [comment]
yes, look at the diff. Before the code changes, the second ao just fails hard.

**Comment by radare** [comment]
travis is red

**Comment by thestr4ng3r** [comment]
afl ordering in that test is a bit different and the analysis for entry0 changes (left is old, right is new):
Bildschirmfoto vom 2019-12-11 13-48-56
The new behavior makes more sense to me, the old one was probably caused by this bug too.

**Pull request merged**
