### PR TITLE
Support building windbg plugin under mingw

### PR DESCRIPTION
**Pull request by ypsvlq**
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

```
../libr/io/p/io_windbg.c:481:43: error: use of undeclared identifier 'DEBUG_ENGOPT_KD_QUIET_MODE'
                                ITHISCALL (dbgCtrl, AddEngineOptions, DEBUG_ENGOPT_KD_QUIET_MODE);

../libr/io/p/io_windbg.c:613:38: error: no member named 'GetValidRegionVirtual' in 'struct IDebugDataSpaces3Vtbl'
                if (SUCCEEDED (ITHISCALL (dbgData, GetValidRegionVirtual, io->off, count, &ValidBase, &ValidSize))) {
```

first is ~~probably fine to remove~~ gone now because it didn't work to begin with, second is more useful though

### CODE REVIEW

**Comment by trufae** [comment]
please rebase to get the green static build

**Comment by ypsvlq** [comment]
w64 builds are failing because of the `GetValidRegionVirtual` which I haven't patched

**Comment by trufae** [comment]
Cool, looking forward the final patch for it :)

**Comment by trufae** [comment]
Good to go?

**Comment by ypsvlq** [comment]
Think so, the plugin has unrelated bugs that were there before but it at least compiles now

**Comment by trufae** [comment]
Ive personally never used this backend either and there are no tests so hard to say when that broke or how.

thanks for the code cleanups. Those always help to improve syability

**Pull request merged**
