### PR TITLE
Fix Objective-C classes Swift demangling ##bin

### PR DESCRIPTION
**Pull request by mrmacete**
- [x] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

Use `r_bin_demangle_swift` to demangle Swift Objective-C classes in the couple of places where that was missing, and ensure all parsed classes have `index` set, to allow coexistence of different categories with the same name.

### CODE REVIEW

**Comment by trufae** [comment]
test output should be updated. a bit more verbose, but if that fixes other usecases better sync up

Screenshot 2024-07-10 at 21 50 36

**Comment by mrmacete** [comment]
yeah not sure of all this sudden `Swift.` prefixing

**Comment by mrmacete** [comment]
apart from that yeah it fixes a lot of stuff, but we need better test coverage

**Comment by trufae** [comment]
please rebase

**Comment by mrmacete** [comment]
rebased, but also observed that the `Swift.` prefix is an artifact of r2's own demangler, because it goes away on macos by enabling `-e bin.demangle.trylib=true`

**Comment by mrmacete** [comment]
i can work around it in mach0_classes or we can fix the root cause, what do you think?

**Comment by trufae** [comment]
ok to merge?

**Comment by mrmacete** [comment]
yeah should be "good enough" now

**Comment by trufae** [comment]
merged!

**Pull request merged**
