### PR TITLE
Fix r_cons_rgb_parse() harder

### LINKED ISSUE #16060: Cutter color themes showed wrongly on updated radare2 submodule
**Environment information**
* Operating System: Arch
* Cutter version: Newest from git
* Obtained from:
  - Built from source
* File format: Any

**Describe the bug**

After updating radare2, Cutter's color themes (e.g Ayu) looks very weird on the widgets and on the integrated console. Interestingly, themes look just fine on radare2 from the terminal.

**Ayu color theme on Cutter:**
Disassembly:
image

Cutter's console widget:
image

Radare2 console from the regular terminal:
image

**To Reproduce**

1. Update the radare1 submodule
2. Build Cutter with the updated version of radare2
3. Open a binary in Cutter
4. See that the themes look weird

**Expected behavior**
Themes should look as before, with no broken colors

### PR DESCRIPTION
**Pull request by thestr4ng3r**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] ~~I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)~~

**Detailed description**

This fixes the broken color themes in Cutter and some read beyond the given string.

**Test plan**

* Use Cutter
* Run the added unit tests

**Closing issues**

Fix #16060

### CODE REVIEW

**Comment by karliss** [comment]
What do you think of fixing call sites? Last time I checked there were only two of them.

**Comment by thestr4ng3r** [comment]
Yes, there are only two. But what is there to fix about them except what I just pushed?

**Comment by karliss** [comment]
Making them pass pointer to the same position of color code so that r_cons_rgb_parse doesn't have to guess if it was given pointer "0x1b" '[" or symbol after "[". And documenting what r_cons_rgb_parse expects as input.

Either it expect pointer to 0x1b and r_cons_html_filter needs to be updated and it should return an error if the input doesn't start with "0x1b[" or it expects pointer after "[" and r_meta_print needs to be updated.

By the way I am not fully convinced by r_meta_print having to parse terminal color code. Storing line color annotations as terminal color sequence makes  the project less portable. In my opinion it would be better to save them in r2 specific format and convert it to terminal color during disassembly printing using current terminal settings.

**Comment by thestr4ng3r** [comment]
I don't really have a strong negative opinion on the \x1b and [ part. I think the way it is now (skip over \x1b if found, then skip over [ if found) is quite clear, without subtracting from the pointer.

About meta, I agree, but this should be done in another pr.

**Pull request merged**
