### PR TITLE
Rearrange 'dij' output curly brace and commas

### PR DESCRIPTION
**Pull request by Talos878**
**Checklist**

- [x] Closing issues: #issue
- [x] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [radare2book](https://github.com/radareorg/radare2book)

**Description**

update dij so that the output doesn't have inconsistent use of curly braces

### CODE REVIEW

**Comment by trufae** [comment]
Please, switch to use the PJ api, its safer and cleaner way to serialize json. Thanks

**Comment by Talos878** [comment]
What is the PJ api?

**Comment by trufae** [comment]
Check libr/util/pj.c and grep for uses in the source with `git grep r_core_pj_new`

**Comment by Talos878** [comment]
Okay, I will make a separate pull request in the future in esilsolve when switching over, cause I think that uses the old api. Do you know is the person who made esilsolve still active with it?

**Comment by trufae** [comment]
The author of esilsolver wrote radius which is a replacement for it. So i assume its not as maintained as radius

**Comment by Talos878** [comment]
I saw radius but haven't had the time to truly learn rust, so I avoided it since I am just doing this for learning purposes. For now I am going to mark this closed, and will open another request later if I do anything with radius or esilsolve

**Comment by aemmitt-ns** [comment]
esilsolve does not use dij, and only uses di to check whether a debugger is being used. same with radius. but they might use dij in the future so thanks for the fix

**Comment by Talos878** [comment]
Hells yeah, that would be awesome. How much longer have you been working on radius since esilsolve? Also what made you choose to write your own solver, rather than try to append functionality to something like angr to make it be able to handle esil instructions? Thanks for the tool

**Comment by aemmitt-ns** [comment]
ok i realized that i switched to just checking `di` in uncommitted changes, so they are pushed now and r200.py should work again. been working on radius for like 9 months? and i mostly made it just cuz i liked ESIL and wanted to try using it for symbolic execution. its really nice to be able to write ESIL expressions to do quick things, like in the ESILSolve r2 plugin or the `radius2` cmd line tool. `radius2` is really easy to use you can install it with `cargo install radius2` and do cool things like solve r200 with just `radius2 -p r200 -s stdin 48 str -X Incorrect -m 0x4007ba` and it takes ~0.1 seconds not ~2.4 like for ES. And you can write hooks in ESIL so like if you add `-H main SP,1,+,.` itll print out rsp+1 when it starts main. radius adds two ESIL operators `.` to print an arg and `_` which constrains the arg to be  != 0. So nearly everything you might want to do in a hook can be done with a short ESIL string. Its great for rapidly trying things in a flexible way that other frameworks like angr and manticore are too slow and annoying for.

**Comment by trufae** [comment]
@Talos878 do you have the other PR using PJ ready?

**Comment by Talos878** [comment]
Sorry, no. Give me a week or two. I have some things I have to sort through
before I can get to that.

**Pull request closed without merging**
