### PR TITLE
 Convert kvx analysis plugin into arch ##arch 

### PR DESCRIPTION
**Pull request by jmaselbas**
Notable change during the conversion: the arch plugin now uses init/fini for decode context which might not be the final solution but it is better than using a per thread local storage.

### CODE REVIEW

**Comment by jmaselbas** [comment]
I am marking this as a draft, I will like to test this a bit more (I only compiled r2 and haven't tested this properly)

**Comment by trufae** [comment]
The meson build is what is missing here to be fully green, i can fix it if you want, but to build with meson just do: `meson b; ninja -C b`. guess you'll need to fix libr/meson.build and libr/(anal|arch)/meson.build too. Let's make the arch transition happen!

**Comment by jmaselbas** [comment]
I have this error, when running `meson b`:
```
shlr/meson.build:211:2: ERROR: File capstone/arch/BPF/BPFDisassembler.c does not exist.
```
Did I miss a setup step ?

**Comment by trufae** [comment]
Looks great! merged!

**Pull request merged**
