### PR TITLE
 Bring back tcc support ##build

### PR DESCRIPTION
**Pull request by trufae**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

Building r2 with TCC is somewhat desirable. This PR aims to fix https://github.com/radareorg/radare2/issues/4328

**Test plan**

Maybe add a github action with the following lines:

```
r2pm -ci tcc
export CC="tcc"
r2pm -r ./configure --with-compiler=tcc
r2pm -r make
```

**Closing issues**

Closes https://github.com/radareorg/radare2/issues/4328

### CODE REVIEW

**Comment by XVilka** [comment]
If it works could land in 4.5.0

**Comment by XVilka** [comment]
It fails because of the TCC error it seems:
```
tcc: x86_64-gen.c:452: load: Assertion `((ft & VT_BTYPE) == VT_INT) || ((ft & VT_BTYPE) == VT_LLONG) || ((ft & VT_BTYPE) == VT_PTR) || ((ft & VT_BTYPE) == VT_FUNC)' failed.
make[3]: *** [/home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_mach0.o] Aborted (core dumped)
/home/runner/work/radare2/radare2/libr/../global.mk:38: recipe for target '/home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_mach0.o' failed
make[3]: Leaving directory '/home/runner/work/radare2/radare2/libr/bin'
make[2]: *** [bin] Error 2
Makefile:159: recipe for target 'bin' failed
make[1]: *** [all] Error 2
make[2]: Leaving directory '/home/runner/work/radare2/radare2/libr'
Makefile:22: recipe for target 'all' failed
make[1]: Leaving directory '/home/runner/work/radare2/radare2/libr'
Makefile:56: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by ret2libc** [comment]
Removing from 4.5.0 because this has been an issue for over 3 years, I don't think it's *that* important at this point.

**Comment by XVilka** [comment]
Probably we should send a bug description (or a patch) to [`tinycc-devel`](https://lists.nongnu.org/mailman/listinfo/tinycc-devel) mailing list. Apparently there is a [lot of activity happenning there](https://lists.nongnu.org/archive/html/tinycc-devel/2020-07/index.html).

**Comment by XVilka** [comment]
There is also another error - we saw it in the past:
```
"tcc -D__LITTLE_ENDIAN__=1 -shared -Dxx -o libr_fs.so -sonamelibr_fs.so p/fs_ext2.o p/fs_fat.o p/fs_fb.o p/fs_hfs.o p/fs_hfsplus.o p/fs_io.o p/fs_iso9660.o p/fs_jfs.o p/fs_minix.o p/fs_ntfs.o p/fs_posix.o p/fs_r2.o p/fs_reiserfs.o p/fs_sfs.o p/fs_tar.o p/fs_udf.o p/fs_ufs.o p/fs_xfs.o fs.o fs_file.o shell.o  -L/home/runner/work/radare2/radare2/libr/util -L/home/runner/work/radare2/radare2/libr/io -lr_util -lr_io   -fPIC -fvisibility=hidden    /home/runner/work/radare2/radare2/libr/../shlr/grub/libgrubfs.a -fvisibility=hidden"
/home/runner/work/radare2/radare2/libr/io/libr_io.so: error: referenced dll 'libr_socket.so' not found
tcc: error: library 'r_io' not found
make[4]: *** [libr_fs.so] Error 1
../rules.mk:82: recipe for target 'libr_fs.so' failed
```

**Comment by XVilka** [comment]
TinyCC developers fixed the problem, also attached the patch to radare2, but it's still not sufficient to build it: https://lists.nongnu.org/archive/html/tinycc-devel/2020-08/txt5WwrLjrHAf.txt

**Comment by trufae** [comment]
I'm not sure about the extra dependencies, if those are really needed why they didnt failed in any other compiler? would be good to compare make depgraph to see if there's any issue there

**Comment by trufae** [comment]
Good patches @XVilka ! is there any other patch for tcc needed to continue in here? can you post the fixes/commits/issues from their repo? thanks!

**Comment by XVilka** [comment]
These are commits in TinyCC itself that were done for various bugs preventing to compile radare2:
- https://repo.or.cz/tinycc.git/commit/dcb87d36fee6825aee50df2b5f92ef457bb9a486
- https://repo.or.cz/tinycc.git/commit/8b8e7145170949f871b20f2de1c13b3cfe140bc3
- https://repo.or.cz/tinycc.git/commit/70b16cb7f84d166e8b1548770d4dfe7f2de4ef73
- https://repo.or.cz/tinycc.git/commit/50fe33f88009c8194b286c5dc579ddbf300fba51
- https://repo.or.cz/tinycc.git/commit/4c9e3a5988b4281cba6add9ecc2cf1d6b4650bcf

**Comment by XVilka** [comment]
Seems the only remaining problem is this library dependency, can you @trufae please check? Just be sure to update `tcc` first.

**Comment by XVilka** [comment]
Still a dependency problem:
```
2020-09-10T04:12:47.3536463Z "tcc -D__LITTLE_ENDIAN__=1 -shared -Dxx -o libr_bin.so -sonamelibr_bin.so bin.o dbginfo.o bin_ldr.o bin_write.o demangle.o dwarf.o filter.o bfile.o bobj.o blang.o mangling/cxx/cp-demangle.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_any.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_art.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_avr.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_bf.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_bflt.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/bflt/bflt.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_bios.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_bootimg.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_cgc.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_coff.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/coff/coff.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_dex.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_dbginfo_dex.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/dex/dex.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_dmp64.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/dmp/dmp64.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_dol.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_dyldcache.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_elf.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_dbginfo_elf.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_write_elf.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/elf/elf.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/elf/elf_write.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_elf64.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_dbginfo_elf64.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_write_elf64.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/elf/elf64.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/elf/elf64_write.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_fs.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_java.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_le.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/le/le.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_mach0.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/mach0/mach0.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/objc/mach0_classes.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/objc/mach064_classes.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_write_mach0.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_mach064.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_write_mach064.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/mach0/mach064.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_mbn.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_mdmp.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/mdmp/mdmp.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/mdmp/mdmp_pe.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/mdmp/mdmp_pe64.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_menuet.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_mz.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/mz/mz.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_ne.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/ne/ne.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_nes.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_nin3ds.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_ninds.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_ningb.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_ningba.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_nro.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_nso.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/nxo/nxo.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_omf.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/omf/omf.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_p9.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/p9/p9bin.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_pe.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_write_pe.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/pe/pe.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/pe/pe_write.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_pe64.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_write_pe64.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/pe/pe64.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/pe/pe64_write.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_pebble.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_prg.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_psxexe.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_pyc.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/pyc/marshal.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/pyc/pyc_magic.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/pyc/pyc.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_qnx.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_sfc.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_smd.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_sms.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_spc700.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_symbols.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/mach0/coresymbolication.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_te.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/te/te.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_vsf.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_wasm.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/wasm/wasm.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_xbe.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_xnu_kernelcache.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/xnu/r_cf_dict.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_z64.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_zimg.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/zimg/zimg.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_xtr_dyldcache.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/mach0/dyldcache.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_xtr_fatmach0.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/mach0/fatmach0.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_xtr_pemixed.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/../format/pe/pemixed.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_xtr_sep64.o /home/runner/work/radare2/radare2/libr/..//libr/bin/p/bin_ldr_linux.o mangling/demangler.o mangling/microsoft_demangle.o mangling/objc.o mangling/cxx.o mangling/msvc.o mangling/swift.o mangling/swift-sd.o mangling/java.o mangling/rust.o pdb/pdb_downloader.o pdb/omap.o pdb/stream_pe.o pdb/gdata.o pdb/fpo.o pdb/dbi.o pdb/tpi.o pdb/stream_file.o pdb/pdb.o  -L/home/runner/work/radare2/radare2/libr/util -L/home/runner/work/radare2/radare2/libr/io -L/home/runner/work/radare2/radare2/libr/socket -L/home/runner/work/radare2/radare2/libr/magic -L/home/runner/work/radare2/radare2/libr/hash -L/home/runner/work/radare2/radare2/libr/syscall -L/home/runner/work/radare2/radare2/libr/cons -lr_util -lr_io -lr_socket -lr_magic -lr_hash -lr_syscall -lr_cons   -fPIC /home/runner/work/radare2/radare2/libr/../shlr/zip/librz.a /home/runner/work/radare2/radare2/libr/../shlr/zip/librz.a /home/runner/work/radare2/radare2/libr/..//shlr/yxml/libyxml.a /home/runner/work/radare2/radare2/libr/..//shlr/java/libr_java.a /home/runner/work/radare2/radare2/libr/..//shlr/ar/libr_ar.a -fvisibility=hidden    -fvisibility=hidden"
2020-09-10T04:12:47.3741114Z tcc: error: referenced dll 'libr_crypto.so' not found
2020-09-10T04:12:47.3741427Z tcc: error: library 'r_io' not found
2020-09-10T04:12:47.3752606Z make[3]: *** [libr_bin.so] Error 1
2020-09-10T04:12:47.3753308Z /home/runner/work/radare2/radare2/libr/..//libr/rules.mk:82: recipe for target 'libr_bin.so' failed
2020-09-10T04:12:47.3754020Z make[3]: Leaving directory '/home/runner/work/radare2/radare2/libr/bin'
2020-09-10T04:12:47.3757734Z make[2]: *** [bin] Error 2
2020-09-10T04:12:47.3758170Z Makefile:166: recipe for target 'bin' failed
2020-09-10T04:12:47.3759216Z make[1]: *** [all] Error 2
2020-09-10T04:12:47.3759714Z make[2]: Leaving directory '/home/runner/work/radare2/radare2/libr'
```

**Comment by trufae** [comment]
@XVilka any update from tcc devs?

**Comment by XVilka** [comment]
@trufae update for what? They fixed all bugs in git that were found during the radare2 compilation. It's now only the dependency problem that prevents radare2 being built.

**Comment by trufae** [comment]
Amazing! great to see tcc back to r2land. ive checked the error  and it seems like its not buildling r_io for some reason i ignore . therefor later it fails. can i have a shell in this env? otherwise i can try to repro in local. Can you repro?

**Comment by XVilka** [comment]
It builds r_io just fine, I think:
```
tcc -D__LITTLE_ENDIAN__=1 -c    -fPIC -g -Wall -D__UNIX__=1 -Wall -DR2_PLUGIN_INCORE -I/home/runner/work/radare2/radare2/libr/../shlr/zip/include -I/home/runner/work/radare2/radare2/libr/..//shlr/ptrace-wrap/include -I/home/runner/work/radare2/radare2/libr/../shlr/ar -I/home/runner/work/radare2/radare2/libr/../shlr/bochs/include/ -I/home/runner/work/radare2/radare2/libr/../shlr/gdb/include/ -I/home/runner/work/radare2/radare2/libr/../shlr/qnx/include/ -I/home/runner/work/radare2/radare2/libr/../shlr/winkd -I../../shlr/zip/include  -I/home/runner/work/radare2/radare2/libr -I/home/runner/work/radare2/radare2/libr/include -I/home/runner/work/radare2/radare2/libr/../shlr/sdb/src -fvisibility=hidden -o io_fd.o io_fd.c
"tcc -D__LITTLE_ENDIAN__=1 -shared -Dxx -o libr_io.so -sonamelibr_io.so p/io_ar.o p/io_bfdbg.o p/io_bochs.o p/io_debug.o p/io_default.o p/io_fd.o p/io_gdb.o p/io_gprobe.o p/io_gzip.o p/io_http.o p/io_ihex.o p/io_mach.o p/io_malloc.o p/io_mmap.o p/io_null.o p/io_procpid.o p/io_ptrace.o p/io_qnx.o p/io_r2k.o p/io_r2k_linux.o p/io_r2pipe.o p/io_r2web.o p/io_rap.o p/io_rbuf.o p/io_self.o p/io_shm.o p/io_sparse.o p/io_tcp.o p/io_w32.o p/io_w32dbg.o p/io_winedbg.o p/io_winkd.o p/io_zip.o io.o io_plugin.o io_map.o io_desc.o io_cache.o p_cache.o undo.o ioutils.o io_fd.o /home/runner/work/radare2/radare2/libr/..//shlr/ptrace-wrap/src/ptrace_wrap.o  -L/home/runner/work/radare2/radare2/libr/util -L/home/runner/work/radare2/radare2/libr/socket -L/home/runner/work/radare2/radare2/libr/hash -L/home/runner/work/radare2/radare2/libr/cons -L/home/runner/work/radare2/radare2/libr/crypto -lr_util -lr_socket -lr_hash -lr_cons -lr_crypto   -fPIC /home/runner/work/radare2/radare2/libr/..//shlr/ar/libr_ar.a /home/runner/work/radare2/radare2/libr/../shlr/zip/librz.a /home/runner/work/radare2/radare2/libr/..//shlr/gdb/lib/libgdbr.a /home/runner/work/radare2/radare2/libr/..//shlr/qnx/lib/libqnxr.a /home/runner/work/radare2/radare2/libr/..//shlr/ptrace-wrap/libptrace_wrap.a -fvisibility=hidden    -lutil -lr_cons -lutil /home/runner/work/radare2/radare2/libr/../shlr/ar/libr_ar.a /home/runner/work/radare2/radare2/libr/../shlr/bochs/lib/libbochs.a -lutil /home/runner/work/radare2/radare2/libr/../shlr/gdb/lib/libgdbr.a -lutil /home/runner/work/radare2/radare2/libr/../shlr/qnx/lib/libqnxr.a -lutil -lutil /home/runner/work/radare2/radare2/libr/../shlr/winkd/libr_winkd.a -fvisibility=hidden"
make[4]: Entering directory '/home/runner/work/radare2/radare2/libr/io/p'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/runner/work/radare2/radare2/libr/io/p'
make[3]: Leaving directory '/home/runner/work/radare2/radare2/libr/io'
DIR flag
```

**Comment by XVilka** [comment]
@ret2libc please take a look at tree-sitter library changes.

**Comment by XVilka** [comment]
I can reproduce the problem locally, but it shows `tcc: error referenced dll 'libr_hash.so' not found`. I check the directory of `libr/hash/` and `libr_hash.so` is here, `ldd` and `readelf` confirm the library is fine. Something is shady.

**Comment by trufae** [comment]
sounds to me like another tcc bug

**Comment by trufae** [comment]
@XVilka imho its fine to merge in the current state. the remaining bug is not in our side i think

**Comment by XVilka** [comment]
I [cherry-picked to master](https://github.com/radareorg/radare2/commit/aa7de006e68fee26e3382aec00d73e69b2619510) all changes in radare2 codebase itself. Therefore, three subsystems that are in fact external projects:
- lz4
- jemalloc
- tree-sitter.

We should try to mainline these changes.

**Comment by XVilka** [comment]
All possible changes were mainstreamed, all bugs in TinyCC were fixed. The only remaining issue is in radare2 - something about module dependency or so. @trufae

**Comment by XVilka** [comment]
Interesting, seems some symbols are still broken in the resulting libraries:
```
 Collecting r2pipe from git+https://github.com/radareorg/radare2-r2pipe#egg=r2pipe&subdirectory=python
  Cloning https://github.com/radareorg/radare2-r2pipe to /tmp/pip-build-zu2tk1b7/r2pipe
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zu2tk1b7/r2pipe/python/setup.py", line 3, in <module>
        import r2pipe
      File "/tmp/pip-build-zu2tk1b7/r2pipe/python/r2pipe/__init__.py", line 38, in <module>
        from r2pipe.open_sync import open
      File "/tmp/pip-build-zu2tk1b7/r2pipe/python/r2pipe/open_sync.py", line 14, in <module>
        from r2pipe.open_base import OpenBase
      File "/tmp/pip-build-zu2tk1b7/r2pipe/python/r2pipe/open_base.py", line 22, in <module>
        from .native import RCore
      File "/tmp/pip-build-zu2tk1b7/r2pipe/python/r2pipe/native.py", line 109, in <module>
        class RCore(Structure):  # 1
      File "/tmp/pip-build-zu2tk1b7/r2pipe/python/r2pipe/native.py", line 119, in RCore
        "r_core_cmd_str", "c_void_p, c_char_p", "c_char_p"
      File "/tmp/pip-build-zu2tk1b7/r2pipe/python/r2pipe/native.py", line 104, in register
        method = WrappedRMethod(cname, args, ret)
      File "/tmp/pip-build-zu2tk1b7/r2pipe/python/r2pipe/native.py", line 51, in __init__
        self.method = getattr(r2lib(), cname)
      File "/tmp/pip-build-zu2tk1b7/r2pipe/python/r2pipe/native.py", line 30, in r2lib
        lib = CDLL(lib_name)
      File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: /usr/lib/libr_fs.so: undefined symbol: grub_millisleep
```
cc @eagleoflqj

**Comment by eagleoflqj** [comment]
> Interesting, seems some symbols are still broken in the resulting libraries:
> 
> ```
>  Collecting r2pipe from git+https://github.com/radareorg/radare2-r2pipe#egg=r2pipe&subdirectory=python
>   Cloning https://github.com/radareorg/radare2-r2pipe to /tmp/pip-build-zu2tk1b7/r2pipe
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-zu2tk1b7/r2pipe/python/setup.py", line 3, in <module>
>         import r2pipe
>       File "/tmp/pip-build-zu2tk1b7/r2pipe/python/r2pipe/__init__.py", line 38, in <module>
>         from r2pipe.open_sync import open
>       File "/tmp/pip-build-zu2tk1b7/r2pipe/python/r2pipe/open_sync.py", line 14, in <module>
>         from r2pipe.open_base import OpenBase
>       File "/tmp/pip-build-zu2tk1b7/r2pipe/python/r2pipe/open_base.py", line 22, in <module>
>         from .native import RCore
>       File "/tmp/pip-build-zu2tk1b7/r2pipe/python/r2pipe/native.py", line 109, in <module>
>         class RCore(Structure):  # 1
>       File "/tmp/pip-build-zu2tk1b7/r2pipe/python/r2pipe/native.py", line 119, in RCore
>         "r_core_cmd_str", "c_void_p, c_char_p", "c_char_p"
>       File "/tmp/pip-build-zu2tk1b7/r2pipe/python/r2pipe/native.py", line 104, in register
>         method = WrappedRMethod(cname, args, ret)
>       File "/tmp/pip-build-zu2tk1b7/r2pipe/python/r2pipe/native.py", line 51, in __init__
>         self.method = getattr(r2lib(), cname)
>       File "/tmp/pip-build-zu2tk1b7/r2pipe/python/r2pipe/native.py", line 30, in r2lib
>         lib = CDLL(lib_name)
>       File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
>         self._handle = _dlopen(self._name, mode)
>     OSError: /usr/lib/libr_fs.so: undefined symbol: grub_millisleep
> ```
> 
> cc @eagleoflqj

I don't know what image github is using, but I can't reproduce locally on a docker ubuntu:latest.
```sh
root@ae2e0dac22cf:/radare2# python3 -m pip install --user 'git+https://github.com/radareorg/radare2-r2pipe#egg=r2pipe&subdirectory=python'
Collecting r2pipe
  Cloning https://github.com/radareorg/radare2-r2pipe to /tmp/pip-install-qsrghf_4/r2pipe
  Running command git clone -q https://github.com/radareorg/radare2-r2pipe /tmp/pip-install-qsrghf_4/r2pipe
Building wheels for collected packages: r2pipe
  Building wheel for r2pipe (setup.py) ... done
  Created wheel for r2pipe: filename=r2pipe-1.5.0-py3-none-any.whl size=11128 sha256=722287cff845a6135cbac6a44c81f887d00c1d93d6eaa43406bdfcbd5f91aa4a
  Stored in directory: /tmp/pip-ephem-wheel-cache-12eo3h73/wheels/35/43/4b/ee5955a77c9396e2350de9174ac374666bda8156cf872ab7fe
Successfully built r2pipe
Installing collected packages: r2pipe
Successfully installed r2pipe-1.5.0
```

**Comment by XVilka** [comment]
Seems r2pipe problem was fixed.

**Comment by XVilka** [comment]
But there is still a symbol problem nevertheless:
```
Run r2 -v
  r2 -v
  r2r -v
  cd test
  make
  shell: /bin/bash -e {0}
  env:
    PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/pkgconfig
r2: symbol lookup error: /usr/lib/libr_fs.so: undefined symbol: grub_millisleep
```

**Comment by XVilka** [comment]
1. The produced code is significantly slower but works.
2. There are still some test failures:
```

[XX] db/cmd/cmd_help "? -1"
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '? -1' --
-- stdout
@@ -6,7 +6,7 @@
 segment fffff000:0fff
 string  "\xff\xff\xff\xff\xff\xff\xff\xff"
 fvalue: -1.0
-float:  nanf
-double: nan
+float:  -nanf
+double: -nan
 binary  0b1111111111111111111111111111111111111111111111111111111111111111
 trits   0t11112220022122120101211020120210210211220
```

**Comment by XVilka** [comment]
@trufae @condret you can merge this even now - just keep in mind that the change in jmalloc should be repeated again in case you decide to update jemalloc to a new version.

Another thing - some tests are broken, but I think it's still better than broken compilation.

**Review by XVilka — APPROVED** [review]

**Comment by trufae** [comment]
Appreciate

**Pull request merged**
