### PR TITLE
r2pm: R2PM_CLEAN_GITDIR states (sub)dir to clean

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

This pr changes `R2PM_CLEAN_GITDIR` so that it states the git (sub)dir to clean. I think this is better than #17411 because more r2pm code can be reused.

Supersedes #17411. Reverts #17357. Also removes the trailing `/` in `R2PM_GITDIR`.

This git (sub)dir can't be derived directly from `R2PM_GIT` because many plugins use:

```sh
R2PM_GIT "https://github.com/radareorg/radare2-extras"
```

**Test plan**

Add the following anywhere in the `r2dec` package script:

```sh
R2PM_CLEAN_GITDIR=r2dec-js
```

**Closing issues**

...

### CODE REVIEW

**Comment by trufae** [comment]
Why not just pass the 2nd argument to the git url?

**Comment by kazarmy** [comment]
> Why not just pass the 2nd argument to the git url?

Because if a 2nd argument is passed, it changes where the package is installed, and at least r2dec doesn't like that (i.e. it explicitly tries to find a `r2dec-js` folder).

Now you may argue that r2dec should change from using `r2dec-js` to using `r2dec`, and ideally that should be done, but fixing something that ain't broken doesn't seem very appealing (not to mention it requires juggling 2 prs and also might require cooperation from the package owner).

**Comment by kazarmy** [comment]
requires juggling 2 prs -> requires the simultaneous merging of 2 different prs

**Comment by kazarmy** [comment]
> I think this is better than #17411 because more r2pm code can be reused.

Hmm another way of doing that is to refactor out the gitdir-cleaning code into a separate function and then call it from inside an `if [ "$ACTION" = clean ]` block. Probably more proper than having yet another global var, so closing this.

**Pull request closed without merging**
