### PR TITLE
Compile tree-sitter with std=c99 flag

### LINKED ISSUE #15614: tree-sitter require std=c99
tree-sitter require at least std=c99 to be built without errors.
Not all compilers use the std c99 as default and such special care should be made when using such features.

Actual output:
```
tree-sitter/lib/src/././language.h:67:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (unsigned i = 0; i < section_count; i++) {
     ^
[...]
```

Here is a quick fix:
``` diff
diff --git a/shlr/Makefile b/shlr/Makefile
index 0c10f4379..0946b24fd 100644
--- a/shlr/Makefile
+++ b/shlr/Makefile
@@ -336,7 +336,7 @@ tree-sitter/libtree-sitter.$(EXT_AR): tree-sitter/lib/src/lib.o
        $(RANLIB) $@

 tree-sitter/lib/src/lib.o: tree-sitter-sync
-       $(CC) -c tree-sitter/lib/src/lib.c -o $@ -Itree-sitter/lib/include -Itree-sitter/lib/src $(CFLAGS)
+       $(CC) -std=c99 -c tree-sitter/lib/src/lib.c -o $@ -Itree-sitter/lib/include -Itree-sitter/lib/src $(CFLAGS)
```

### PR DESCRIPTION
**Pull request by ret2libc**
Fixes #15614 and updates tree-sitter to release 0.16.1

### CODE REVIEW

**Comment by XVilka** [comment]
Hopefully, one day C99 will be the default. 20 years old standard!

**Comment by XVilka** [comment]
Wait, it breaks BSD builds:
```
"/bin/sh" clone_3rd_repo.sh tree-sitter "https://github.com/tree-sitter/tree-sitter.git" "master" "9f77afcd1ff050855259f83fcf50056ad842a790"
[tree-sitter] Cloning tree-sitter from git...
clang std=c99 -c tree-sitter/lib/src/lib.c -o tree-sitter/lib/src/lib.o -Itree-sitter/lib/include -Itree-sitter/lib/src  -MD    -fPIC -g -Wall -D__UNIX__=1 -MD
clang: error: no such file or directory: 'std=c99'
gmake[1]: *** [Makefile:339: tree-sitter/lib/src/lib.o] Error 1
gmake[1]: Leaving directory '/home/build/radare2/shlr'
gmake: *** [Makefile:59: all] Error 2
```

**Comment by XVilka** [comment]
```
In file included from radare2-shell-parser/src/parser.c:1:0:

radare2-shell-parser/src/parser.c: In function 'ts_lex':

tree-sitter/lib/include/tree_sitter/parser.h:131:8: warning: unused variable 'eof' [-Wunused-variable]

   bool eof = false;             \

        ^

radare2-shell-parser/src/parser.c:648:3: note: in expansion of macro 'START_LEXER'

   START_LEXER();

   ^~~~~~~~~~~
```

**Comment by ret2libc** [comment]
@XVilka there's not a lot i can do about that right now. I'll try to submit a PR to tree-sitter to resolve those few "issues". But really, it's nothing big so we can just ignore those few things.

**Pull request merged**
