### PR TITLE
Fix UB in the loongarch decoder

### PR DESCRIPTION
**Pull request by trufae**
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

**Copilot**

### CODE REVIEW

**Comment by trufae** [comment]
Hey @junchao-loongson i have found this UB via asan, but attempting to fix the (too much shifting to the left, and also, on a signed variable) causes some troubles. By reading the output of the tests seems like it was not behaving well before, there are some calls to negative addresses and adds with negative numbers..

I don't know much this arch, and i have my head in other stuff, so i would appreciate if you could take a look at this and provide a proper fix.

Here's the failing test.

Screenshot 2023-08-17 at 17 35 42

**Comment by junchao-loongson** [comment]
hello~ I'm not sure I understand what UB means. Can you give me a link to the relevant information
Do you mean that the following code may cause security problems?
```
      ret <<= sizeof (ret) * 8 - len;
      ret >>= sizeof (ret) * 8 - len;
```

**Comment by junchao-loongson** [comment]
okay，i got it, thanks. I'll handle it.

**Comment by junchao98** [comment]
Under normal circumstances, len is always less than 32, because loongarch's instructions are encoded as 32 bit.
we can add a assert()
```
assert(sizeof(ret) * 8 > len);
ret <<= sizeof (ret) * 8 - len;
ret >>= sizeof (ret) * 8 - len;
```

**Comment by junchao-loongson** [comment]
Under normal circumstances, len is always less than 32, because loongarch's instructions are encoded as 32 bit.
we can add a assert()
```
assert(sizeof(ret) * 8 > len);
ret <<= sizeof (ret) * 8 - len;
ret >>= sizeof (ret) * 8 - len;
```
This operation is designed to do symbolic expansion of data of the specified bit length

**Comment by trufae** [comment]
Adding an assert will make r2 to crash. Consider dimming the value or so

**Pull request closed without merging**
