### PR TITLE
Add division overflow macros in r_types ##util

### PR DESCRIPTION
**Pull request by trufae**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by trufae** [comment]
This PR add generic macros to use across the whole r2 codebase. Improving the state of https://github.com/radareorg/radare2/pull/17815

**Comment by wargio** [comment]
having functions on .h files, is not the best. especially if you include the file twice.

**Comment by ret2libc** [comment]
> having functions on .h files, is not the best. especially if you include the file twice.

It is a common way to use functions instead of macros, very useful for small pieces of code. So you still avoid calling functions (which has a cost) + you have the advantages of function type checking, easy of writing, etc.

**Comment by wargio** [comment]
> > having functions on .h files, is not the best. especially if you include the file twice.
> 
> It is a common way to use functions instead of macros, very useful for small pieces of code. So you still avoid calling functions (which has a cost) + you have the advantages of function type checking, easy of writing, etc.

Nono. I'm fully aware of that, is just i do not like those functions to be defined in a header instead of a c file.

The issue I'm referring is `multiple declaration of xxxxx function` which happens when you include the same header file in multiple files even when you have ifndef/define/endif

**Comment by ret2libc** [comment]
> > > having functions on .h files, is not the best. especially if you include the file twice.
> > 
> > 
> > It is a common way to use functions instead of macros, very useful for small pieces of code. So you still avoid calling functions (which has a cost) + you have the advantages of function type checking, easy of writing, etc.
> 
> Nono. I'm fully aware of that, is just i do not like those functions to be defined in a header instead of a c file.

If you want to avoid the overhead of functions calling, etc. you *must* define them in the header AFAIK.

> 
> The issue I'm referring is `multiple declaration of xxxxx function` which happens when you include the same header file in multiple files even when you have ifndef/define/endif

AFAIK if you include a file like this in multiple files you should not get that error/warning, because the function is `static`, so it is redefined (separately) for each file that includes the header.

**Review by XVilka — APPROVED** [review]

**Review by wargio — APPROVED** [review]

**Pull request merged**
