### PR TITLE
Remove R_CORE_AUTOCMPLT_END and fix UAF/crash

### PR DESCRIPTION
**Pull request by trufae**
```
cmd.c: In function 'cmd_autocomplete':
cmd.c:2151:29: warning: iteration 15 invokes undefined behavior [-Waggressive-loop-optimizations]
    if (autocomplete_flags[i].desc) {
        ~~~~~~~~~~~~~~~~~~~~~^~~~~
cmd.c:2150:3: note: within this loop
   for (i = 0; i < R_CORE_AUTOCMPLT_END; i++) {
   ^~~
```
 

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by wargio** [comment]
This is not the correct fix.
The issue there is linked to the fact that it is missing the following flags form that structure:
```
R_CORE_AUTOCMPLT_SEEK
R_CORE_AUTOCMPLT_FCN
```

so to fix this properly, you should add after `{ "$flsp", "shows known flag-spaces hints", R_CORE_AUTOCMPLT_FLSP },`
```c
	{ "$seek", "shows the seek hints", R_CORE_AUTOCMPLT_SEEK },
	{ "$fcn", "shows the functions hints", R_CORE_AUTOCMPLT_FCN },
```

**Review by wargio — CHANGES_REQUESTED** [review]
Wrong fix. see my comment above.

**Comment by trufae** [comment]
Well, the fix is correct, but it's also true that the struct misses those cases. they are now in.

**Review by wargio — CHANGES_REQUESTED** [review]
No. i'm highly against all these changes. your fix was a workaround to fix this issue. the proper fix was just to add those 2 lines that now you have added.

I would prefer to revert back everything and have just those 2 lines added.
There where checks in place for types on purpose.

**Comment by XVilka** [comment]
Agree with @wargio

**Comment by XVilka** [comment]
@trufae can you please update the PR so we can get it merged?

**Comment by trufae** [comment]
i have updated the pr with only the changes you requested. il investigate the other changes

**Review by wargio — APPROVED** [review]

**Pull request merged**
