### PR TITLE
add ? and ! as custom charset for gameboy rom pokemon red and blue

### PR DESCRIPTION
**Pull request by gogo2464**
**Checklist**

- [ ] Closing issues: #issue
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [radare2book](https://github.com/radareorg/radare2book)

**Description**

I added 2 new chars for the gameboy rom pokemon red and blue.

### CODE REVIEW

**Comment by gogo2464** [comment]
Ready to merge.

**Comment by Shadorain** [comment]
why the excessive newlines? do they have a purpose or what?

**Comment by gogo2464** [comment]
I personally find it more easy to read. Do you want I change it?

**Comment by Shadorain** [comment]
Oh gotcha, nah, not up to me. I just didn't know if they were there for a reason or just accidental.

**Comment by trufae** [comment]
@Shadorain you are right. Those unnecessary newlines shouldnt be there.

**Pull request merged**
