### PR TITLE
WIP: LZMA magic

### PR DESCRIPTION
**Pull request by radare**
Ripped (and improved) from binwalk

### CODE REVIEW

**Comment by XVilka** [comment]
Note that not all LZMA headers are 8 bytes of the decompressed size, some legacy implementations (thus compressed files) use 4 bytes...

**Comment by radare** [comment]
feel free to improve pls :)

**Comment by ret2libc** [comment]
What about this? @radare do you still have interest in finishing this or can we close it?

**Comment by radare** [comment]
Let the gsoc students finish/improve it. And yes i have always interest in finishing things

**Comment by XVilka** [comment]
@ret2libc don't close please. I still have no idea how to distinct between 4 bytes-long and 8 bytes-long lengths at the magic level.

**Comment by radare** [comment]
@XVilka do u have some tests?

**Comment by radare** [comment]
checking for this fffff may be the soluton to kill the false positives

```
pmb:r2r pancake$ lzma < /bin/sleep |hexdump -C|head
00000000  5d 00 00 80 00 ff ff ff  ff ff ff ff ff 00 67 be  |].............g.|
00000010  99 af de 39 19 1d 3f 99  5a fa 54 dd 89 41 1a f4  |...9..?.Z.T..A..|
00000020  cf e4 90 a0 14 63 80 01  15 e4 f0 f9 d5 03 72 ec  |.....c........r.|
00000030  96 80 bd 0c e1 0f 10 5f  57 ba 40 3b 5b 84 2a da  |......._W.@;[.*.|
00000040  51 b7 80 46 08 8f 40 ab  da ff 79 df 10 dc a6 fc  |Q..F..@...y.....|
00000050  67 06 94 3b df 09 ac 2e  d5 d3 95 e7 21 49 61 ab  |g..;........!Ia.|
00000060  16 8d f5 62 75 f9 06 82  19 61 2a 4d 93 75 73 d1  |...bu....a*M.us.|
00000070  a9 f0 e3 d2 80 d7 d1 68  f1 01 2c 48 e1 d8 9b a1  |.......h..,H....|
00000080  ae 7a 2b a0 e7 22 97 fb  e0 ae 0b 5d f4 7b 00 b0  |.z+..".....].{..|
00000090  3e 3d d7 3a 8a b8 05 e3  0b c6 6e 14 c7 e9 da 84  |>=.:......n.....|
pmb:r2r pancake$
```

**Comment by XVilka** [comment]
@radare this is `outlen` - it can be "-1" but can be real number, you can't really determine if it's valid or not. There is a weak sign it might be real - highly likely it will be more than 32 and less than 1Gb, should help to filter some of the false positives.

**Comment by radare** [comment]
i know but at least we will catch some true positives this way, and we can start adding test for this

**Pull request merged**
