### PR TITLE
Fix #12700

### LINKED ISSUE #12700: Kill fastcall.h and use Calling convention SDB files
Right now there are 2 places where calling conventions need to be defined:

* https://github.com/radare/radare2/blob/master/libr/syscall/fastcall.h 
and
* https://github.com/radare/radare2/blob/master/libr/anal/d/cc-x86-64.sdb.txt

`fastcall.h` must be killed and code refactored to use the SDB files instead

### PR DESCRIPTION
**Pull request by 08A**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [x] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**
Fix #12700
...

**Test plan**
...

**Closing issues**
...

### CODE REVIEW

**Comment by radare** [comment]
Why all that stuff removed

**Comment by 08A** [comment]
```
Right now there are 2 places where calling conventions need to be defined:

    https://github.com/radare/radare2/blob/master/libr/syscall/fastcall.h
    and
    https://github.com/radare/radare2/blob/master/libr/anal/d/cc-x86-64.sdb.txt

fastcall.h must be killed and code refactored to use the SDB files instead
```

I removed the regs field in the RSyscall struct and all use of fascall.h.

**Comment by 08A** [comment]
Basically the majority of the code base don't use this struct field

**Comment by radare** [comment]
Ok thanks for the explanation

**Comment by radare** [comment]
@xvilka if u merge a pr please fix the commit message because this one is useless

- no description of the fix
- no ##tag
- start in uppercase

**Pull request merged**
