### PR TITLE
WIP: Try to run V tests

### LINKED ISSUE #15657: Run R2R V suite on BSD platforms and GitHub Actions
To test it automagically

Also, can we run them from meson? Without the makefile?

### PR DESCRIPTION
**Pull request by XVilka**
Hmm...
```
make[1]: Leaving directory '/home/runner/work/radare2/radare2/test/src'
./src/r2r: error while loading shared libraries: libr_core.so: cannot open shared object file: No such file or directory
##[error]Process completed with exit code 127.
````

closes #15657

### CODE REVIEW

**Comment by radare** [comment]
Please rebase

**Comment by radare** [comment]
This error is because radare is not installed so it cant link against its libs

**Comment by radare** [comment]
pls rebase

**Comment by XVilka** [comment]
@radare it now runs the tests, but fails with
```
V panic: ls() couldnt open dir "/home/runner/work/radare2/radare2/test/src/../bins/fuzzed"
                                               | 0x7f66c1a03b97 | /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) 
                                               | 0x55b3e6ecddda | ./src/r2r(+0x1dda) 
```

**Comment by radare** [comment]
Missing git clone of the bins?

**Comment by XVilka** [comment]
Finally it runs completely, but many failed tests:
```
 Broken: 883
  Fixed: 10
Success: 10574
 Failed: 752
```

See attached log
[radare2_vlang_ghactions_log.zip](https://github.com/radareorg/radare2/files/4348743/radare2_vlang_ghactions_log.zip)

**Comment by kazarmy** [comment]
You need to run r2r from the `src` directory.

**Comment by kazarmy** [comment]
`cd test/src` first

**Comment by radare** [comment]
Unless you mkae install because r2r follow symlinks. I may fix this to work without symlinks

>

**Comment by XVilka** [comment]
Depends also on https://github.com/radareorg/radare2/issues/16285

**Comment by XVilka** [comment]
V panics as usual:
```
[OK] (time 56) /home/runner/work/radare2/radare2/test/src/../new/db/tools/r2r : Only EXPECT_ERR<<EOF
[OK] (time 57) /home/runner/work/radare2/radare2/test/src/../new/db/tools/r2r : EXPECT<<EOF empty and EXPECT_ERR<<EOF non-empty
V panic: failed to open file "/home/runner/.cache/temp.CZ28l8/output.txt"
[OK] (time 59) /home/runner/work/radare2/radare2/test/src/../new/db/tools/r2r : BROKEN=0 with comment
                                               | 0x7fcd119516db | /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) 
                                               | 0x7fcd1233388f | /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) 
```

**Comment by radare** [comment]
let's go for the C one

**Pull request closed without merging**
