### PR TITLE
Fix #18108

### LINKED ISSUE #18108: Wrong tst opcode interpretation
Hello,

It seems that ARM32's [tst](https://developer.arm.com/documentation/dui0489/i/arm-and-thumb-instructions/tst) opcode is incorrectly interpreted.
The ESIL emulation and the pseudo code are wrong.
The screenshot is from cutter 0.12.0 but I have tested this in radare too.
Ida, Ghidra and QEMU do it differently/correctly.

I know that emulation is partial and imprecise, but you also say
"One of the most common usages of such emulation is to calculate indirect jumps and conditional jumps."
But if even this is not working, it's clearly a bug, or am I missing a thing?

tst

### PR DESCRIPTION
**Pull request by eagleoflqj**
**Checklist**

- [x] Closing issues: #18108
- [x] Mark this if you consider it ready to merge
- [x] I've added tests (optional)
- [ ] I wrote some lines in the [radare2book](https://github.com/radareorg/radare2book)

**Description**

```sh
liumeo@liumeo-imac:~$ r2 -a arm -b 32 -Qc 'wx 0f0010e3
> ao' -
address: 0x0
opcode: tst r0, 0xf
esilcost: 0
disasm: tst r0, 0xf
pseudo: if ((r0 & 0xf) == 0)
mnemonic: tst
description: test
mask: 0000f0ff
prefix: 0
id: 227
bytes: 0f0010e3
ptr: 0x0000000f
refptr: 0
size: 4
sign: false
type: cmp
cycles: 1
reg: r0
esil: 0,15,r0,&,==,$z,zf,:=,31,$s,nf,:=
family: cpu
```

### CODE REVIEW

**Comment by trufae** [comment]
LOL i had this exact patch but went to sleep before doing the pr

**Comment by trufae** [comment]
Please use the test script i wrote for it.

```
$ cat libr/anal/test.r2

e asm.arch=arm
e asm.bits=32
wx 050010e3 0100a003
pd 2
ao 2~esil
aei
ar r0=5
2aes
ar?r0
```

**Comment by trufae** [comment]
some godbolt context in here
Screenshot 2020-12-26 at 11 06 20

**Comment by trufae** [comment]
Please rebase, i fixed the failing test and add the emulation test i pasted above :) thank you!

**Comment by eagleoflqj** [comment]
> Please rebase, i fixed the failing test and add the emulation test i pasted above :) thank you!

Modified the test to let r0=4 since testing 4&5 is to some extent better than 5&5.

**Pull request merged**
