### PR TITLE
Rename anal.in=raw to anal.in=range

### LINKED ISSUE #14927: Rename anal.in=raw -> range
its the only anal.in that honors anal.from/to, so it makes more sense to me

### PR DESCRIPTION
**Pull request by officialcjunior**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

On #14927, it was suggested to rename `anal.in`=raw to `anal.in=range` to honour `anal.in` and `anal.from`. I plan to solve the issue with this Pull Request.

**Test plan**
* The right direction in solving this, if I missed anything.
*  Guidance on `e.search.in` and `e.zoom.in` as it has the same options.

**Closing issues**

Closes #14927

### CODE REVIEW

**Comment by XVilka** [comment]
Please also send a pull request to Radare2 book: https://github.com/radareorg/radare2book/blob/master/src/analysis/code_analysis.md

**Comment by officialcjunior** [comment]
I couldn't see any direct reference of this option of the command, only a brief amount of information about the command and its options.

[Link to the corresponding part](https://github.com/radareorg/radare2book/blob/master/src/analysis/code_analysis.md#analysis-ranges)

Should I add what `e anal.in=range` does over there?

**Comment by XVilka** [comment]
@officialcjunior yes.

**Comment by officialcjunior** [comment]
> Please also send a pull request to Radare2 book: https://github.com/radareorg/radare2book/blob/master/src/analysis/code_analysis.md

Updated the book, @XVilka 

(https://github.com/radareorg/radare2book/pull/258)

**Pull request merged**
