### PR TITLE
Checking format arguments in variadic functions

### PR DESCRIPTION
**Pull request by anisse**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

This PR adds many new warnings, they should be fixed before merging. This could be automated (gcc gives a correct suggestion), but it still needs thorough testing.

**Test plan**

...

**Closing issues**

N/A

### CODE REVIEW

**Comment by ret2libc** [comment]
@anisse I'm pushing to your branch to help a bit with fixing the warnings ;)

**Comment by ret2libc** [comment]
I will take care of all `libr/anal/*` and `libr/asm/*` warnings.

**Review by radare — CHANGES_REQUESTED** [review]
Fix the code scanning findings: https://github.com/radareorg/radare2/pull/17529/files#diff-7ecdc50e604747e997ce6a92b0694504R726

**Review by trufae — APPROVED** [review]
Wow! good findings!!

**Comment by XVilka** [comment]
I wonder if we can just merge the fixes without the warning-enabling commit, then rebase this pull request. It will allow to keep the master green but also will reduce the size of the PR.

**Comment by ret2libc** [comment]
> I wonder if we can just merge the fixes without the warning-enabling commit, then rebase this pull request. It will allow to keep the master green but also will reduce the size of the PR.

Good idea. I will do this these days.

**Comment by anisse** [comment]
I also want to add that the first part of this PR is merge-able in #17461 and doesn't add any warning.

**Comment by XVilka** [comment]
@anisse can you please rebase then?

**Comment by anisse** [comment]
I have rebased the branch, I hope it's OK @ret2libc ; I didn't re-order the commits. If you merge the commits separately, do not hesitate to rebase as well (or ping me).

**Comment by trufae** [comment]
Fix conflicts and rebase again

Thanks!

**Review by trufae — APPROVED** [review]

**Comment by trufae** [comment]
Also fix the PR title "Help wanted: formatting warnings #17529" is not really descriptive. its main issue produced by this bug is 32 bit machines causing segfaults. So its an important fix., not just formatting warnings :) and add a tag ##

**Review by ret2libc — CHANGES_REQUESTED** [review]
Just to avoid merging this as-is, because it would introduce many warnings that would make CodeQL red. I'm probably going to do as suggested by @XVilka and just do a PR with the fixes, without the R_PRINTF_CHECK

**Comment by trufae** [comment]
new alerts:

78 for Wrong type of arguments to formatting function
1 for Too few arguments to formatting function

**Comment by ret2libc** [comment]
> new alerts:
> 
> 78 for Wrong type of arguments to formatting function
> 1 for Too few arguments to formatting function

We are aware. This PR as-is introduces many new warnings, that's why I've submitted another PR that just fixes the formatting without introducing the warnings, so we can solve the warnings few at a time. As you have seen in the other PR, even these "simple" fixes may introduce bugs.

**Comment by XVilka** [comment]
There are conflicts now - please rebase and lets merge another chunk of the changes.

**Comment by trufae** [comment]
Please @anisse can you fix the conflicts and rebase on top of master?

thanks!!

**Comment by anisse** [comment]
Yes, I'll do this soon.

**Comment by anisse** [comment]
I have rebased it, but please do not merge before #17648 ; also the remaining warnings should be fixed before merging.

**Comment by trufae** [comment]
Can you rebase amd fix the conflicts? not sure if @ret2libc could check this out, because that was in conflict with your printf pr

**Comment by XVilka** [comment]
For MSVC seems [SAL annotations](https://docs.microsoft.com/en-us/cpp/code-quality/annotating-function-parameters-and-return-values?view=vs-2019) could help, e.g.:
```c
int MyPrintF(_Printf_format_string_ const wchar_t* format, ...)
{
       va_list args;
       va_start(args, format);
       int ret = vwprintf(format, args);
       va_end(args);
       return ret;
}
```

**Comment by XVilka** [comment]
```
/home/build/radare2/libr/..//libr/anal/p/anal_v850.c:257:68: warning: format specifies type 'unsigned short' but the argument has type 'unsigned int' [-Wformat]
                r_strbuf_appendf (&op->esil, "pc,%s,=,pc,%hu,+=", F5_RN2(word1), F5_DISP(((ut32)word2 << 16) | word1));
                                                         ~~~                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                         %u
/home/build/radare2/libr/..//libr/anal/p/anal_v850.c:39:24: note: expanded from macro 'F5_DISP'
#define F5_DISP(instr) ((((ut32)(instr) & 0xffff) << 31) | (((ut32)(instr) & 0xffff0000) << 1))
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```

**Comment by trufae** [comment]
Fix the LGTM `This pull request introduces 6 alerts and fixes 1 when merging 627986f into 486b7be - view on LGTM.com` please

**Comment by trufae** [comment]
Also please rebase

**Comment by XVilka** [comment]
Warnings can be fixed later - it took very long time to make build green. Lets merge this ASAP.

**Review by wargio — APPROVED** [review]

**Review by XVilka — APPROVED** [review]

**Pull request merged**
