### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by condret**
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

### CODE REVIEW

**Comment by trufae** [comment]
mind to finish it?

**Comment by condret** [comment]
yes, i want to finish, atm i struggle to see why this fails

**Comment by trufae** [comment]
this is an abi breaking change, and i htink its good to finish it before 5.9 ,let me know if i can help you in any way to finish this

**Comment by trufae** [comment]
the failure in r2r could be caused by a bad usage of the threads apis in r2r.c itself or maybe a bug in your changes, but thats a racist issue and its not spotable by checking the logs

**Comment by trufae** [comment]
The tinyasan job seems to timeout

**Pull request merged**
