### PR TITLE
Update quickjs.c

### PR DESCRIPTION
**Pull request by xambroz**
avoid error/varning about the need of C99 compatibility mode when the variable is declared vithin the for cycle definition.

- [x] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

### CODE REVIEW

**Comment by trufae** [comment]
can you push this fix upstream and run make sync?

**Comment by trufae** [comment]
i did the fix upstream here https://github.com/quickjs-ng/quickjs/pull/719

**Comment by trufae** [comment]
overrided by https://github.com/radareorg/radare2/pull/23678

**Comment by xambroz** [comment]
Thank you ... I was looking for the upstrem, to report it there, but I found a wrong one and it was not there so I thought these are local changes in radare2 ( https://github.com/bellard/quickjs/blob/master/quickjs.c )

**Pull request closed without merging**
