### PR TITLE
Separate r_sdb lib for Windows

### PR DESCRIPTION
**Pull request by pelijah**

### CODE REVIEW

**Comment by XVilka** [comment]
1. What is the benefit?
2. You will need to send the changes to the original SDB repo too: https://github.com/radare/sdb

**Comment by pelijah** [comment]
> 
> 
>     1. What is the benefit?

r2 libs on WIndows don't export sdb symbols so we use hack to use them in Cutter (https://github.com/radareorg/cutter/blob/master/prepare_r2.bat#L21). I think it will be better to distribute a separate lib.

> 
>     2. You will need to send the changes to the original SDB repo too: https://github.com/radare/sdb

I want to test it on Travis and get some feedback first.

**Comment by pelijah** [comment]
ping @thestr4ng3r

**Comment by radare** [comment]
please make a pr in sdb to add all those sdb_apis first

**Comment by pelijah** [comment]
@radare Could you update shlr/sdb?

**Comment by XVilka** [comment]
You can do it yourself, see sdb-sync target in shlr/Makefile

**Comment by pelijah** [comment]
Ok, done #15095

**Comment by pelijah** [comment]
I have found a better way: #15098

**Pull request closed without merging**
