### PR TITLE
Remove the --without-r2r configure flag

### PR DESCRIPTION
**Pull request by radare**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by ret2libc** [comment]
I don't use configure/make, but I don't see the problem of keeping the flag. Not everybody probably wants to build r2r-c (e.g. building radare2 for packaging)

**Comment by radare** [comment]
Exactly is what we want to have everywhere because we want every user to be able to write tests and run tests. Imho a 10KB extra executable doesnrt hurt. Yes, having an exrta flag doesnt hurt, but i want to reduce complexity, reduce questions, and reduce problems or different suer environments. Otherwise we will have to teach users to buildl from git to teest a. Thing if they are using a packaged version and so on. Which is a mess. Same env for everyone simplifies the problems a lot

**Comment by ret2libc** [comment]
AFAIU r2r-c is enabled by default, but it can be optionally disabled. So I see only package maintainers using this, so they don't build extra stuff not needed for the distro package.

**Comment by radare** [comment]
Like having an extra small .c file woul dbe aproblem for any distro.

I WANT everyone to be able to write, run and check r2, even distros, debian will patch and change everything like theyalways do, but they wil do that even if we have this flag. I know the default is building it .

Also all the binaries are implemented in libr/main except this one

>

**Pull request merged**
