### PR TITLE
Update sdb to 2faeca6dfe516b3ab5f1fcd3655d878fdcbdad0f

### PR DESCRIPTION
**Pull request by pelijah**
**DO NOT SQUASH**

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

Memleak in `shlr/sdb/src/main.c`  causes build error in case of using mesonbuild with ASAN.

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Review by trufae — APPROVED** [review]

**Review by XVilka — CHANGES_REQUESTED** [review]
Looks like it breaks AppVeyor Windows build. Please try to rebase and/or fix the build issues.

**Comment by pelijah** [comment]
Yep it can't be build on Windows.

**Comment by pelijah** [comment]
Ok I have found the reason https://github.com/radareorg/sdb/pull/227

**Comment by trufae** [comment]
Please update again. also it will be good to store the hash of the commit somewhere, so we can identify which specific commit are we using in our copy inside r2

**Comment by trufae** [comment]
Also, i think we can automate a way to do this in CI, maybe adding a hook or maybe there's a bot. so we can get automatic update PRs

**Comment by XVilka** [comment]
Can you please update to this commit then? https://github.com/radareorg/sdb/commit/2faeca6dfe516b3ab5f1fcd3655d878fdcbdad0f

**Review by XVilka — APPROVED** [review]

**Pull request merged**
