### PR TITLE
Force read permissions on all load maps in ELF ##bin

### PR DESCRIPTION
**Pull request by radare**

### CODE REVIEW

**Comment by ITAYC0HEN** [comment]
are there maps in any file formats that should not have read perms? Otherwise, this can be added to all formats

**Comment by radare** [comment]
yep, this is kind of a "hack", maybe we should have an option in RBinOptions to specify if we want to set 'r' on all maps having write or exec perms set.

**Comment by ITAYC0HEN** [comment]
This could be useful. It will prevent people from get confusing why they don't see what they expect. Merging :)

**Comment by GurTelem** [comment]
Spent 7 hours last week on this, thanks :-)

**Pull request merged**
