### PR TITLE
Move coverage testing to  meson-gcc-newshell-tests

### PR DESCRIPTION
**Pull request by karliss**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

Previously coverage was measured on meson-gcc-tests which isn't run on pull requests. meson-gcc-newshell-tests should do more or less the same code except part of command parsing code.

**Test plan**

Wait for pull request tests to finish. Make sure test coverage for whole project not the diff is ~40% same as when master is being tested.

**Closing issues**

### CODE REVIEW

**Comment by karliss** [comment]
No coverage report. Maybe it doesn't report anything if no C files are modified.

**Comment by karliss** [comment]
It succeeded on first run although with 39.9% coverage running ~26 minutes and on the second run it managed to hit 45 minute timeout.

**Comment by karliss** [comment]
Looks like meson-gcc-tests with coverage testing in the master runs ~40 minutes which is close to the 45 minute time limit. In that case it's a bit weird that it managed to run in 27 minutes the first time.

Are we fine with test run time increase from 20 to 40 minutes for pull requests? Didn't expect coverage measurement to cause such a slowdown. Although windows tests on appveyor also take 45 minutes so it shouldn't increase the longest running test performed on pull requests.

**Comment by karliss** [comment]
Correction 40 minutes in master include fuzz tests which take ~10 minutes. 40-10 ~ 27 minutes makes sense. It shouldn't time out as it did.

**Comment by kazarmy** [comment]
Note that ci.yml sets `-Db_coverage=true` but `b_coverage` isn't checked anywhere in the Meson build code.

**Comment by ret2libc** [comment]
@kazarmy what do you mean? That option should be a built in one.

**Comment by ret2libc** [comment]
So... do we really want the codecov run on every PR? I'm not sure how much things can improve from PR to PR and how much we would look at it. Maybe it is ok to just run this on master, what do you think?

**Comment by kazarmy** [comment]
> @kazarmy what do you mean? That option should be a built in one.

Orly? (ok just found https://mesonbuild.com/Builtin-options.html#base-options ... sure wish it was more transparent though)

**Comment by ret2libc** [comment]
> > @kazarmy what do you mean? That option should be a built in one.
> 
> Orly? (ok just found https://mesonbuild.com/Builtin-options.html#base-options ... sure wish it was more transparent though)

I think all the `b_*` options are built-in.

**Comment by kazarmy** [comment]
Don't think CMake has built-in options to that extent, much less GNU make

**Comment by karliss** [comment]
I think I was able to repeat testsuite getting stuck. Need to investigate more as that shouldn't happen even if we don't want to run coverage on PR.

> So... do we really want the codecov run on every PR? I'm not sure how much things can improve from PR to PR 

Absolute numbers probably won't change PR to PR but code cov also reports the coverage for diff. That can be useful to quickly evaluate if newly added code has matching amount of tests added.

**Comment by karliss** [comment]
I have no more ideas why it times out now. It didn't timeout on the first run. It also doesn't time out in master.

**Comment by karliss** [comment]
This time linux-meson-gcc-tests timed out so it isn't specific to combination of newshell and coverage measurement.

**Comment by karliss** [comment]
One percent difference between this branch and master could be due to fuzzing being run only on master.

**Comment by ret2libc** [comment]
> This time linux-meson-gcc-tests timed out so it isn't specific to combination of newshell and coverage measurement.

This kind of random timeouts are probably due to bugs in r2r. Or at least, they started appearing when we introduced r2r. They seemed to happen mainly in macos though. Just a random thought, maybe it's not that :)

**Comment by trufae** [comment]
There are 2 or 3 tests that take almost all the time of the testsuite to run. its just wrongly written tests or too heavy ones. will be good to show them up in the r2r output (top 10 slowest tests for example and their times). this will help us debug and fix those bottlenecks

**Comment by ret2libc** [comment]
Also master sometimes fail and this is bad :(

**Comment by karliss** [comment]
Looks acceptable?

**Review by ret2libc — APPROVED** [review]

**Pull request merged**
