### PR TITLE
Fix #17322 - Honor bin.baddr from idp to load rebased PDB files ##bin

### LINKED ISSUE #17322: -B parameters disables function name presentation at pd command
When opening a file using the -B option, to fix the base addess, the disassembled code is not presenting the function names.
So for example, when openning and application with the following command:

radare2 App.efi

The disassembly result at a given address is this:

[0x00010650]> s 0x0008f2e4
[0x0008f2e4]> pd 3
            0x0008f2e4      4053           push rbx
            0x0008f2e6      4883ec20       sub rsp, 0x20
            0x0008f2ea      33db           xor ebx, ebx

After loading the .pdb file, the result is this:

[0x0008f2e4]> idp LdiagTextApp.pdb

[0x0008f2e4]> pd 3
            **;-- pdb.FunctionName:**
            0x0008f2e4      4053           push rbx
            0x0008f2e6      4883ec20       sub rsp, 0x20
            0x0008f2ea      33db           xor ebx, ebx

But, when opening the same file, but passing a baseaddress with this command:

radare2 App.efi -B 0x7D89C000 

The result at the same location (considering the new baseaddress) is this:

[0x7d91b2e4]> s 0x7d91b2e4
[0x7d91b2e4]> pd 3
            0x7d91b2e4      4053           push rbx
            0x7d91b2e6      4883ec20       sub rsp, 0x20
            0x7d91b2ea      33db           xor ebx, ebx

After loading the pdb (the function name is no presented):

[0x7d91b2e4]> idp LdiagTextApp.pdb

[0x7d91b2e4]> pd 3
            0x7d91b2e4      4053           push rbx
            0x7d91b2e6      4883ec20       sub rsp, 0x20
            0x7d91b2ea      33db           xor ebx, ebx

### PR DESCRIPTION
**Pull request by trufae**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

From telegram:
```
a> Hi guys.
a> I have a question.
a> When using radare2 with -B to set the correct base address the function names are not presented when I load the pdb
a> Without the -B everything works perfectly
a> 
```
**Test plan**

see tests

**Closing issues**

#17322

### CODE REVIEW

**Comment by trufae** [comment]
@HoundThe i dont fully understand your comment. It is an issue in what i'm changing here or a different issue?

**Comment by HoundThe** [comment]
> @HoundThe i dont fully understand your comment. It is an issue in what i'm changing here or a different issue?

Oh in a nutshell if getting the base address can be moved into the `r_core_pdb_info()` because it's probably being done twice? The function `r_core_pdb_info()` is called from the `cmd_info` or `bin_pdb()`  and each of those two are getting the base address, but maybe they differ?

**Comment by trufae** [comment]
Ah ok, did that change.

**Comment by XVilka** [comment]
please fix conflict

**Comment by XVilka** [comment]
Doesn't build:
```
cbin.c: In function ‘r_core_pdb_info’:
cbin.c:1202:2: error: unknown type name ‘R_PDB’; did you mean ‘R2_SDB’?
  R_PDB pdb = R_EMPTY;
  ^~~~~
  R2_SDB
cbin.c:1204:5: error: request for member ‘cb_printf’ in something not a structure or union
  pdb.cb_printf = r_cons_printf;
     ^
cbin.c:1205:24: warning: passing argument 1 of ‘init_pdb_parser’ from incompatible pointer type [-Wincompatible-pointer-types]
  if (!init_pdb_parser (&pdb, file)) {
                        ^
In file included from /home/runner/work/radare2/radare2/libr/include/r_bin.h:13:0,
                 from /home/runner/work/radare2/radare2/libr/include/r_asm.h:7,
                 from /home/runner/work/radare2/radare2/libr/include/r_egg.h:4,
                 from /home/runner/work/radare2/radare2/libr/include/r_core.h:15,
                 from cbin.c:3:
/home/runner/work/radare2/radare2/libr/include/r_pdb.h:32:12: note: expected ‘RPdb * {aka struct r_pdb_t *}’ but argument is of type ‘int *’
 R_API bool init_pdb_parser(RPdb *pdb, const char *filename);
            ^~~~~~~~~~~~~~~
cbin.c:1208:10: error: request for member ‘pdb_parse’ in something not a structure or union
  if (!pdb.pdb_parse (&pdb)) {
          ^
cbin.c:1210:6: error: request for member ‘finish_pdb_parse’ in something not a structure or union
   pdb.finish_pdb_parse (&pdb);
```

**Comment by XVilka** [comment]
@HoundThe could you please continue this PR? So we can get it merged.

**Comment by trufae** [comment]
Of course. It was green the very first day. And now i have no time and i have no interest or need to use pdb. I will take care when i get some spare time and motivation as usual. Both ingredients are quite low lately as you know

**Comment by trufae** [comment]
@xvilka tests are green now

**Pull request merged**
