### PR TITLE
When setting non-bool config var, set false/true if r_str_is_false()/_is_true()

### PR DESCRIPTION
**Pull request by kazarmy**
For https://github.com/radareorg/radare2/pull/15500#issuecomment-558248872.

### CODE REVIEW

**Comment by XVilka** [comment]
Can you please rebase? Test errors look unrelated:
```
[XX] db/cmd/cmd_open oob consider laddr 32bit  150
$ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -a x86 -b 32 -i /tmp/tmp-16974QZG0xr3aPLCH ../bins/mach0/fatmach0-3true
e bin.laddr = 0x5000
e bin.baddr = -1
oob
iI~laddr[1]
iI~baddr[1]
 0x0
-0x1000
+0x2
EXPECT=<<RUN
0x0
0x2
[XX] db/cmd/cmd_open oob consider laddr 64bit  213
$ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -a x86 -b 64 -i /tmp/tmp-16974Uktel4UV85m8 ../bins/mach0/fatmach0-3true
e bin.laddr = 0x5000
e bin.baddr = -1
oob
iI~laddr[1]
iI~baddr[1]
 0x0
-0x100000000
+0x2
EXPECT=<<RUN
0x0
0x2
[XX] db/cmd/cmd_print print raw lines  109
$ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -i /tmp/tmp-16974UHsLrFmpTqBQ ../bins/other/projects/resetc64
sl 5
prl 1~[0]
e lines.abs=true
prl 1~[0]
 +1
-5
+256
EXPECT=<<EOF
+1
256
```

**Comment by kazarmy** [comment]
Actually they are related

**Comment by kazarmy** [comment]
Currently idk why the cmd_print test is suddenly related

**Comment by ret2libc** [comment]
This seems wrong to me. If i have a var that is an integer, why do I want to see `true`/`false` instead of 1/0?

For example, see `log.level` (but also many others like `dbg.bpsize` and all the others SETICB). If I now do `e log.level=1;e log.level` I see `true`, which does not make any sense in the context of `log.level` (same applies for `dbg.bpsize`, which sould just contain the size of a breakpoint, so "true" and "false" do not make sense there).

I believe this PR should be reverted.

**Comment by ret2libc** [comment]
@radare @kazarmy ^

**Comment by kazarmy** [comment]
The default getter for integer vars probably needs to be changed to something like what `scr.color` has.

**Comment by ret2libc** [comment]
Why?? If you do that for all integer vars, then your change in the first place is not useful, as `1` would be converted in `true` and then, when printed back, converted again into `1`. Why? If the env var is an integer one, I don't see why we should automatically converting into true/false at all.

**Comment by kazarmy** [comment]
Yes but the original change was not for integer vars, it was for non-integer string vars that need to support multiple-valued logic.

**Comment by ret2libc** [comment]
> Yes but the original change was not for integer vars, it was for non-integer string vars that need to support multiple-valued logic.

Ok, so I think this automatic conversion should only be done for non-integer string vars and not for all non-bool vars, right?

**Comment by kazarmy** [comment]
Yes that could work too.

**Pull request merged**
