### PR TITLE
Move Lib already loaded check before dlopen Call

### PR DESCRIPTION
**Pull request by thestr4ng3r**
for https://github.com/radareorg/r2ghidra-dec/issues/38

This prevents constructors, for example doing C++ static initialization, from being executed twice.

### CODE REVIEW

**Comment by radare** [comment]
My concern on this code was mainly to lod the same plugin twice just because its copied in multiple paths or its the same with different name. Not sure if we should use checksums add another check to avoid this to happen

**Comment by thestr4ng3r** [comment]
Checksums break again if you have a slightly different version of the same plugin. One good way would be to add a unique id string per plugin to `RLibStruct` and check that after loading the lib and before registering the plugin. But we still need to make sure not to call any constructors before we haven't checked the duplication. I don't know enough about dynamic loading to say if this is possible on all platforms.

**Comment by radare** [comment]
yes, thats what we must check.. but if c++/objc crap run things when you do dlopen.. not sure how can we handle this in the right way without using RBin instead

**Comment by radare** [comment]
lets merge for now, most people delete all the plugins after every r2 update, as well as most people put them all in the same place. so it shouldnt be a problem

**Comment by thestr4ng3r** [comment]
Yes, this patch only makes the situation better. Actually even after it there is a special case when you have a duplicate plugin and the one that is loaded first triggers the `Module version mismatch /home/florian/bin/prefix/radare2/lib/radare2/core_ghidra.so (3.8.0) vs (4.0.0-git)`, then it still breaks. I have to investigate whether this is fixable somehow.

**Pull request merged**
