### PR TITLE
Add remaining =A0 in regprofiles for calling convention ##anal

### PR DESCRIPTION
**Pull request by trufae**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by trufae** [comment]
ref https://github.com/radareorg/radare2/pull/17733

**Comment by ret2libc** [comment]
Ok, there is a test to fix. Apart from that, could you open a PR with `asan` in the name so the ASAN tests are run and we can actually check whether this fixes most/all of the warnings? Thanks

**Comment by thestr4ng3r** [comment]
asan run: https://github.com/radareorg/radare2/runs/1192578449

**Review by kazarmy — APPROVED** [review]
The spc700 regprofile can be done later i suppose, and it considerably reduces the noise on the asan build.

**Comment by trufae** [comment]
@kazarmy i will submit a separate PR adding the missing profile for spc700. as well as other improvements for this arch which seems to be not much complete. thanks for spotting it.

lgtm to merge this now

**Comment by trufae** [comment]
how's the missing A0 assert issue solved? @ret2libc i mean you closed your PR but i think its complementary not xor

**Pull request merged**
