### PR TITLE
Move CAN table search to /Du command

### PR DESCRIPTION
**Pull request by sylvainpelissier**
**Checklist**

- [ ] Closing issues: #issue
- [x] Mark this if you consider it ready to merge
- [x] I've added tests (optional)
- [ ] I wrote some lines in the [radare2book](https://github.com/radareorg/radare2book)

**Description**
Can table search was previously in /cu but since it is not related to Cryptography I moved it to /Du. Test have been moved.

### CODE REVIEW

**Comment by trufae** [comment]
Uhm, Why /Du if there's no /D. and also why use /D when there are still lowercase letters to pick? personally i would prefer to discuss a better command before moving forward on this change.

Do you have other suggestions? Another option would be to change the meaning of /c or.. juse use /ru (because at the end, we are looking for references to the UDS entries of the CAN table..) even if that's related to data and not code.

What do you think?

**Comment by sylvainpelissier** [comment]
Sorry last time we discuss I thought it was the solution which was the best. Indeed keeping /c is the simplest but I do not have a global view like you.

**Comment by sylvainpelissier** [comment]
After thinking about that, I think the best is to have `/ru` to keep the mnemonic `/c` for Cryptography. If you agree I'll do the change.

**Comment by trufae** [comment]
Sounds good to me!

**Comment by trufae** [comment]
Please solve the conflicts (aka rebase) before changing that command. thanks!

**Comment by trufae** [comment]
ping

**Pull request closed without merging**
