### PR TITLE
Add a parameter to $s and $o

### PR DESCRIPTION
**Pull request by condret**
Just like we already do for $c and $b

### CODE REVIEW

**Comment by condret** [comment]
tests are fixed in this pr https://github.com/radareorg/radare2-regressions/pull/1967

**Comment by radare** [comment]
i think the 20 xx just need to be updated

**Comment by condret** [comment]
what 20 XX? just try with the pr mentioned in the comment: radareorg/radare2-regressions#1967

**Comment by radare** [comment]
dont tell me to try :D its travis job!

**Pull request merged**
