### PR TITLE
Allow disabling non-ascii char truncation from mostly ascii strings (str.truncnonascii) ##strings

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [X] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

This pr allows the disabling of the truncation of non-ascii chars from ascii strings using str.truncnonascii.

Also, this pr removes the minstrlen check from r_bin_reset_strings() since it has no business checking it.

**Test plan**

GitHubCI and AppVeyor are green.

**Closing issues**

...

### CODE REVIEW

**Comment by ret2libc** [comment]
I'm not sure I understand the purpose... If you are looking for ascii-strings, why non-ascii chars should be included. Would that mean you are actually looking for some other type of string?

**Comment by kazarmy** [comment]
Sometimes there are (mostly) ascii strings that have a non-ascii char or 2 somewhere in the middle, for example currency symbols:

"The price of the cupboard is €10,20."

or have emoji:

"Hi there! 🥳 Going to the beach? 🏖️"

**Comment by ret2libc** [comment]
Isn't there probably some issues with the type detection of strings? I'm not sure adding yet another var really solves the issue that the string detection may be broken.

**Comment by XVilka** [comment]
But these are just Unicode UTF-8 strings.

**Comment by kazarmy** [comment]
The string detection code is currently built for cases like #14499. The reason for the var is that it is impossible to implement string detection code that can satisfy all possible use cases.

**Comment by kazarmy** [comment]
But perhaps detecting the entire string is not particularly needed for my purposes, so I'm closing this.

**Pull request closed without merging**
