### PR TITLE
Replace eprintf by R_LOG_ calls inside GDB module

### LINKED ISSUE #21238: Proposal: remove libgdbr_t.server_debug flag and replace eprintf by R_LOG_ inside GDB module
## Description

In order to debug issue https://github.com/radareorg/radare2/issues/8992 in GDB client I need some debug information to be logged. After searching in the repo for a way to enable debug logging I have found issue https://github.com/radareorg/radare2/issues/10324 and decided to replace `eprintf` calls inside GDB module by `R_LOG_...` calls to be able enabling and disabling logs without app recompiling. I have opened draft PR with this change https://github.com/radareorg/radare2/pull/21237. But after making the change I have found that some debug statements are conditioned by `libgdbr_t.server_debug` flag introduced by https://github.com/radareorg/radare2/pull/7931 and they cannot be enabled in GDB client mode.

This issue is to discuss whether it is appropriate to remove `libgdbr_t.server_debug` flag and `=g!` command taking into account that:
1. Debugging protocol can be useful from both client and server sides. For example I need this log to understand whether radare2 works correctly with GDB server inside QEMU.
2. `R_LOG_...` statements can be turned on and off using `log.level` variable and separate command to enable logs seems unnecessary after introducing new logging facility.

I am ready to implement this change if it is approved.

### PR DESCRIPTION
**Pull request by vsbogd**
- [x] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

Fixes #21238.

In order to debug issue #8992 in GDB client I needed some debug information to be logged. After searching in repo for a way to enable debug logging I have found issue #10324 and decided to replace `eprintf` inside GDB module by `R_LOG_` calls to be able enabling and disabling logs without app recompiling.

### CODE REVIEW

**Comment by trufae** [comment]
The changes look good to me. Is there anything left to remove the WIP?

**Comment by vsbogd** [comment]
@trufae, thanks for the fast response. Nothing is left PR can be merged.
Should I do something to pass ABI compatibility check or it is just a warning for a person who merges PR?

**Comment by trufae** [comment]
Can you fix the PR to not break the ABI?

```
Functions changes summary: 0 Removed, 1 Changed, 0 Added function
Variables changes summary: 0 Removed, 0 Changed, 0 Added variable

1 function with some indirect sub-type change:

  [C] 'function int gdbr_server_serve(libgdbr_t*, gdbr_server_cmd_cb, void*)' has some indirect sub-type changes:
    parameter 2 of type 'typedef gdbr_server_cmd_cb' has sub-type changes:
      underlying type 'int (libgdbr_t*, void*, const char*, char*, typedef size_t)*' changed:
        in pointed to type 'function type int (libgdbr_t*, void*, const char*, char*, typedef size_t)':
          parameter 1 of type 'libgdbr_t*' has sub-type changes:
            in pointed to type 'typedef libgdbr_t':
              underlying type 'struct libgdbr_t' changed:
                type size hasn't changed
                1 data member deletion:
                  'bool server_debug', at offset 1[6](https://github.com/radareorg/radare2/actions/runs/3867218013/jobs/6592861584#step:6:7)16 (in bits)
                1 data member change:
                  'bool get_baddr' offset changed from 1624 to 1616 (in bits) (by -[8](https://github.com/radareorg/radare2/actions/runs/3867218013/jobs/6592861584#step:6:9) bits)
```

**Comment by vsbogd** [comment]
I can leave the field `server_debug` inside the structure, but it doesn't make sense because it is not used anymore. How should such change in ABI be handled? I didn't find information about it in [DEVELOPERS.md](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md).

**Comment by trufae** [comment]
See doc/abi.md, maybe it should referenced from DEVELOPERS.

Yes, during abi-stable seassons [x.y.0-x.y.8] we can't break the abi, this sometimes implies leaving unused fields or functions with wrong signatures or even globals. Those are needed in order to keep the abi rule. when 5.8.9 will arrive, we will take care of all the `git grep R2_590` (for example) lines to break all the abi/api things at once.

im going to update the developers document with this text now. Thanks for noticing

**Comment by trufae** [comment]
Merged! Feel free to add the r2_590 hints from now on

**Pull request merged**
