### PR TITLE
Move the console flushing decision to the console context

### PR DESCRIPTION
**Pull request by thymol0**
When a server is started as a background task, the console will remain silent until the server stops. This is undesirable because the intent of running the server in the background is to be able to keep working in radare while the server is running.

**Checklist**

- [x] Closing issues: #19118
- [x] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [radare2book](https://github.com/radareorg/radare2book)

### CODE REVIEW

**Comment by trufae** [comment]
The reason for that is because the command nesting gets increased by the task running a command that doesn't ends.

Because this counter gets decremented when the command is executed. So this fix doesn't seems correct to me, despite working as expected for this use case. but could be wrong in other situations. Actually, the webserver behaves incorrectly after this change. even if started in foreground.

Sorry for the late response, ive been sick for 2 days unable to move from bed 🤒

**Comment by thymol0** [comment]
Sorry to hear that. I hope for a quick recovery.

**Comment by thymol0** [comment]
This doesn't decrement the nesting counter, we just ingore it. Can you expand on the web server's misbehaviour?

**Comment by trufae** [comment]
I tried your patch and the webserver was working except the /cmd that returns empty results or partial

**Comment by thymol0** [comment]
Yes, this patch is incorrect, I need to find a better solution.

**Comment by trufae** [comment]
As an approach to find the root cause would be to find the offending commit. This was working at some point

**Comment by trufae** [comment]
Any update?

**Comment by thymol0** [comment]
I have been busy with other things. sorry.
Probably this portion has to be re-implemented
https://github.com/radareorg/radare2/blob/adbb29f9c2ee6679bc966e674227233f15b9866d/libr/core/cmd.c#L5520-L5533
The nesting counter should move from core struct to the console context struct, the `noflush` flag too should move to the context struct. The console should consult with the active context when it wants to flush. Since the output stored in the console buffer is contained inside the context which is unique for each task; the decision to flush the buffer should also be container inside the context.

**Comment by trufae** [comment]
That makes sense, would be a good try to move this into the conscontext struct. Do you have some time this week to test it out?

**Comment by thymol0** [comment]
I will try to implement this today.

**Comment by thymol0** [comment]
Ok. The patch is more correct now.

**Comment by trufae** [comment]
That fix looks good, but its surfacing another problem that i hope to fix soon. then i'll merge when confirmed :)

thanks!

**Pull request merged**
