### PR TITLE
Fix native debug not working with files that were opened as RW

### LINKED ISSUE #15650: Can't debug files that were opened in write-mode
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Any
| File format of the file you reverse (mandatory)      | Any
| Architecture/bits of the file (mandatory)            | Any
| r2 -v full output, **not truncated** (mandatory)     | recent from git

### Expected behavior

There shouldn't be a problem to debug file that is opened in write mode. Even if the file was opened in write mode and modified, running `ood` should success in debugging the file

### Actual behavior

Debugging files that are currently opened in write mode is not possible. Probably r2 kept the fd open and blocks the execution.

```
$ r2 -w /tmp/readln 
Module version mismatch /home/beet/.local/share/radare2/plugins/core_pdd.so (3.7.0) vs (4.1.0-git)
 -- Quantum dissasemble: it's there as long as you don't observe it
[0x000010d0]> doo
Could not execvp: Text file busy
Could not execvp: Text file busy
ptrace (PT_ATTACH): No such process
r_core_file_reopen: Cannot reopen file: dbg:///tmp/readln  with perms 0x7, attempting to open read-only.
[0x00000000]> 

```

### Steps to reproduce the behavior 
- Open file in write mode `r2 -w <file>`
- Try to re-open in deubg mode using `ood`
- Fail

### PR DESCRIPTION
**Pull request by yossizap**
The FD was kept open and ptrace was prevented from opening it with the error "Could not execvp: Text file busy".

closes #15650

### CODE REVIEW

**Comment by yossizap** [comment]
Fails on db/archos/linux-x64/dbg_oo but I am really not sure what is the purpose of those tests. Went back as far as 7e4157bc2 and I can't get them to pass locally. This doesn't seem related to my changes.

**Comment by ITAYC0HEN** [comment]
shouldn't it be restored to Write mode while the debugger was finished? I think yes (though very risky because of the instability of many things that might modify user's data

**Comment by yossizap** [comment]
>though very risky because of the instability of many things that might modify user's data

That was my thought, would prefer having the user run `oo+`.

**Comment by ITAYC0HEN** [comment]
if so, Let them know then. don't expect them to guess what has changed

**Comment by yossizap** [comment]
Rebased and added @ITAYC0HEN's request. Hopefully the test will pass now.

**Comment by ITAYC0HEN** [comment]
Still failing. Painful :(

**Comment by radare** [comment]
@ITAYC0HEN if its green and works for you please merge

**Comment by williamcorney** [comment]
I am having the issue described in this post in 2023.  I don't know if the issue was never fixed or has resurfaced again ?

I am working around the problem by renaming the app without a space and then functions as expected.

**Pull request merged**
