### PR TITLE
Radare2 decompiler

### PR DESCRIPTION
**Pull request by gogo2464**
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

### CODE REVIEW

**Comment by condret** [comment]
can you make this a core plugin?

**Comment by gogo2464** [comment]
Did I do something bad?

**Comment by gogo2464** [comment]
@trufae I was going to listen to @condret

**Comment by trufae** [comment]
@gogo2464 this pr makes no sense, it's not even building and as condret and me told u several times in the chat before doing this PR, the r2 decompiler should be implemented in a separate repository because it's will take ages until it could be considered usable and there's no need to mess the main tree with wip and broken code

**Comment by gogo2464** [comment]
ok

**Pull request closed without merging**
