### PR TITLE
Fix prompt autocompletion when in graph mode

### PR DESCRIPTION
**Pull request by GustavoLCR**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

Got broken with https://github.com/radareorg/radare2/commit/6b6f88efd32c9bf8433c9a28106977f7906cae4c

**Test plan**

Manual test

### CODE REVIEW

**Comment by trufae** [comment]
i dont think this should be done in here. whevtever you enter in visual mode (or panels or interactive graph mode). this variable should be checked, and forbid entering if the screen is not interactive. otherwise it should be set somewhere else

**Comment by GustavoLCR** [comment]
`r_core_visual_graph()` should probably just return with and error if `scr.interactive` is `false`, but for some reason it manually sets `scr.interactive` to false here:
https://github.com/radareorg/radare2/blob/71cd29a44abbd9924bfe604be432b4086a29d91a/libr/core/agraph.c#L4169
Do you have any idea why?

**Comment by trufae** [comment]
No idea without trying it out. Did you checked what happens by removing the line?

**Comment by GustavoLCR** [comment]
> No idea without trying it out. Did you checked what happens by removing the line?

@trufae didn't seem to break anything, so I removed it and made it check for `scr.interactive` at the start of the function

**Comment by trufae** [comment]
Cool. Looks good to me. Hope its not breaking somewhere else but we will catch soon or late. For now lgtm

**Review by trufae — APPROVED** [review]

**Review by XVilka — APPROVED** [review]

**Pull request merged**
