### PR TITLE
Add test for RList

### PR DESCRIPTION
**Pull request by x0urc3**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](../DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](../DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](../../radare2book) with the relevant information (if needed)

**Detailed description**
 

Move legacy test code to unit test
* append and prepend
* clone
* reverse
* set and get

Found at:
https://github.com/radareorg/radare2/blob/2b74ff5cda8f7f9a1e0cae0abd84a78997d556e4/libr/util/list.c#L618-L623

### CODE REVIEW

**Comment by radare** [comment]
why draft?

**Comment by x0urc3** [comment]
More on its way. Didn't manage to complete  in one go

**Comment by x0urc3** [comment]
Should I remove the legacy test code from list.c?

https://github.com/radareorg/radare2/blob/2b74ff5cda8f7f9a1e0cae0abd84a78997d556e4/libr/util/list.c#L618-L726

**Comment by radare** [comment]
yes please

**Pull request merged**
