### PR TITLE
Try V suite on FreeBSD and OpenBSD

### PR DESCRIPTION
**Pull request by XVilka**

### CODE REVIEW

**Comment by XVilka** [comment]
Depends on https://github.com/vlang/v/issues/3500 to be fixed.

**Comment by XVilka** [comment]
Blocked also by https://github.com/vlang/v/issues/3530

**Comment by radare** [comment]
openbsd fix here https://github.com/vlang/v/pull/3709

**Comment by XVilka** [comment]
Ok, everything is ready to run actual tests then. Merging.

**Comment by radare** [comment]
Awesome!!

**Comment by radare** [comment]
What about netbsd

**Comment by XVilka** [comment]
Not yet supported by SourceHut (WIP though)

**Pull request merged**
