### PR TITLE
Fix #16109 - Add R_SYS_ARCH for s390x ##ports

### LINKED ISSUE #16109: s390x endian assert issues
r_asm_set_big_endian, see https://api.travis-ci.com/v3/job/293201366/log.txt

Screenshot 2020-03-03 at 00 01 50

### PR DESCRIPTION
**Pull request by radare**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

should fix the problems in travis-s390x related to setting the endianness because there's no such arch if it's not in the .h.

**Test plan**
wait for travis

**Closing issues**

#16109

### CODE REVIEW

**Comment by XVilka** [comment]
Looks like it break it even more: https://travis-ci.com/github/radareorg/radare2/jobs/316566860

**Comment by radare** [comment]
wtf where's the s390x task now??

**Comment by radare** [comment]
also notice we have 0 tests for s390x, and from the tests i did capstone is broken as hell for this arch. but at least it may pass more tests  in travis when enabled

**Comment by radare** [comment]
@ret2libc bring back my travis tests for non-x86

**Comment by radare** [comment]
rebased and pushed, lets see if your travis magic works

**Comment by radare** [comment]
its fun because there are more than 1000 XXX but the tasks ends in green :D

**Comment by radare** [comment]
https://api.travis-ci.com/v3/job/316859474/log.txt

**Comment by radare** [comment]
maybe sysz was a good name after all. asm.cpu=s390x should be the difference maybe, but capstone is broken as hell for Z... so not sure how to proceeed here. feedback? ideas?

**Comment by ret2libc** [comment]
I agree to just change the name, but keep all the files as they are

**Comment by radare** [comment]
what do u mean?

**Comment by ret2libc** [comment]
> maybe sysz was a good name after all. asm.cpu=s390x should be the difference maybe

I meant this.

**Comment by XVilka** [comment]
Can you drop the rename part then?

**Comment by radare** [comment]
ok to merge now @XVilka @ret2libc ?

**Comment by radare** [comment]
the > 1000 XX are unrelated to what im fixing here

**Comment by ret2libc** [comment]
What XX?

**Comment by radare** [comment]
See the travis log. Its green but its full of errors

**Pull request merged**
