### PR TITLE
Fix missing grep glitch in r2pm

### PR DESCRIPTION
**Pull request by trufae**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by XVilka** [comment]
It's recommended to use `$(cmd)` syntax btw instead of backticks.

**Comment by wargio** [comment]
ah, yeah. can you move that cmd to a line above and use a variable inside the if?

**Comment by trufae** [comment]
no, both solutions would look uglier. i just pushed a cleaner fix

**Comment by wargio** [comment]
TBH i do not like the `|| { ... }` syntax

**Comment by trufae** [comment]
I do not like using $() or adding extra variables, and yes || and {} is posix, standard and completely portable

**Pull request merged**
