### PR TITLE
Try to fix spurious errors in AppVeyor

### PR DESCRIPTION
**Pull request by ret2libc**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

This tries to fix some errors we see often enough in AppVeyor (e.g. https://ci.appveyor.com/project/radareorg/radare2/builds/31977704). See https://help.appveyor.com/discussions/problems/1272-fatal-reference-is-not-a-tree-sha-on-git-checkout .

**Test plan**

Well.. we have to try it for a bit.

### CODE REVIEW

**Comment by ret2libc** [comment]
@XVilka https://ci.appveyor.com/project/radareorg/radare2/builds/31981212 can you restart those? Why were they canceled?

**Comment by XVilka** [comment]
@ret2libc canceled those because it will not affect the CI at all. The change is fine, lets merge it.

**Comment by kazarmy** [comment]
Will this result in more AppVeyor builds on master? Do we need to enable [rolling builds](https://www.appveyor.com/docs/build-configuration/#rolling-builds)?

**Comment by kazarmy** [comment]
more AppVeyor builds -> more lengthy AppVeyor builds

**Comment by ret2libc** [comment]
> Will this result in more AppVeyor builds on master? 

How would this change affect the number of builds?

> Do we need to enable [rolling builds](https://www.appveyor.com/docs/build-configuration/#rolling-builds)?

I don't know... that could be an idea, though one cool feature about having tests on each commit is that you can see when something breaks.

**Comment by kazarmy** [comment]
> How would this change affect the number of builds?

Sorry I meant more lengthy AppVeyor builds, since [the referenced error](https://help.appveyor.com/discussions/problems/1272-fatal-reference-is-not-a-tree-sha-on-git-checkout) aborts the build almost immediately after it starts.

> ... though one cool feature about having tests on each commit is that you can see when something breaks.

True, though waiting a few hours for AppVeyor to return results is not for the impatient.

**Pull request merged**
