### PR TITLE
WIP: Fix Post-indexed memory access for ARM 

### LINKED ISSUE #15295: wrong ESIL parsing of ldr/str with post-indexed offset
# wrong ESIL parsing of ldr/str with post-indexed offset

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Arch Linux x86_64
| File format of the file you reverse (mandatory)      | ELF32
| Architecture/bits of the file (mandatory)            | Arm
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.0.0-git 23617 @ linux-x86-64 git.3.9.0-221-gb7aa0c579 commit: b7aa0c57923d49bd60487dc168e87ae92ff4e33f build: 2019-10-17__03:50:27

### Expected behavior
According to ARM standard, post-indexed offset:

> op{cond}{B}{T} Rd, [Rn], FlexOffset

The offset is applied to the value in Rn **after** the data transfer takes place. That means for

> str r0, [r6], 0x8

r0 is written into [r6], then r6 increases by 8.

### Actual behavior
it is observed that this instruction **str** is processed the same as pre-indexed offset with trailing exclaimation mark

>op{cond}{B} Rd, [Rn, FlexOffset]!

, which, in the same example above, increases r6 by 8 before writing to r0. 

On the other hand **ldr** doesn't use the offset at all and always adds 0 to the Rn

### Steps to reproduce the behavior 
[test.o.zip](https://github.com/radareorg/radare2/files/3738379/test.o.zip)

`r2 test.o`

ESIL is wrong:
`af;pdf;e asm.esil=true;pdf;`

Actual execution results of str:
`aei;aeim 0x100000 0xf0000;aeip;`
`aer r0=0xfbfbfbfb; aer r6=0x100000; aes;`
`px 16 @ 0x100000;`

The expected behavior is to write 0xfbfbfbfb at 0x100000. But it is written into 0x100008 instead.

Actual execution results of ldr:
`s entry0+8;aei;aeim 0x100000 0xf0000;aeip;`
`w fbfbfbfb@0x100000; aer r0=0; aer r6=0x100000; aes;`
`aer r6`

r6 is supposed to be 0x100008, but is still 0x100000.

### PR DESCRIPTION
**Pull request by qwuau06**
fixed #15295 str part for ARM32. Post-indexed store fixed.

### CODE REVIEW

**Comment by radare** [comment]
Screenshot 2019-10-17 at 18 14 47

**Comment by qwuau06** [comment]
> Screenshot 2019-10-17 at 18 14 47

isn't the expected result of `str r2, [r3], 5` supposed to be storing value of r2 into [r3] and increase r3 by 5 _afterwards_?
[http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0552a/BABJGHFJ.html](url)

**Comment by qwuau06** [comment]
https://github.com/radareorg/radare2-regressions/pull/1989 
r2r test case pr, targeting the same problem. it should now pass the test.

**Comment by radare** [comment]
please rebase when master gets green

**Comment by thestr4ng3r** [comment]
rebased

**Comment by thestr4ng3r** [comment]
@qwuau06 Is the behavior correct now?

**Comment by qwuau06** [comment]
> @qwuau06 Is the behavior correct now?

Screenshot_2019-10-20_16-28-18
I think it is now.

**Comment by qwuau06** [comment]
> please rebase when master gets green

just rebased

**Comment by qwuau06** [comment]
> @qwuau06 Is the behavior correct now?

Only str is correct now. Haven't touched ldr yet. it seems the code for ldr is a bit unorganized.

**Comment by radare** [comment]
let's merge the str part, open a new pr for the ldr. Thanks!

**Pull request merged**
