### PR TITLE
Fix json generate bug in parse dwarf

### PR DESCRIPTION
**Pull request by EggUncle**
invalid json:
➜  tmp rabin2 -d -j radare2_elf
{"dwarf":CL radare2.c:88 0x00000ca8
CL radare2.c:94 0x00000ce9
"CC radare2.c:94 "@0xce9
CL types.h:5603 0x0000393b
..........
"CC types.h:5603 "@0x393b
CL radare2.c:48 0x00000ac2
"CC radare2.c:48 "@0xac2
}%         

valid json:
{
    "dwarf": [
        [
            {
                "name": "CC",
                "file": "radare2.c",
                "line_num": 64,
                "addr": 2939
            },
            {
                "name": "CL",
                "file": "radare2.c",
                "line_num": 64,
                "line": "",
                "addr": 2939
            }
        ],
        [
            {
                "name": "CC",
                "file": "types.h",
                "line_num": 5603,
                "addr": 14433
            },
            {
                "name": "CL",
                "file": "types.h",
                "line_num": 5603,
                "line": "",
                "addr": 14433
            }
        ],
        ..........
        [
            {
                "name": "CC",
                "file": "radare2.c",
                "line_num": 48,
                "addr": 2754
            },
            {
                "name": "CL",
                "file": "radare2.c",
                "line_num": 48,
                "line": "",
                "addr": 2754
            }
        ]
    ]
}

### CODE REVIEW

**Comment by radare** [comment]
i can merge for now but thjis needs to be rewritten to use the pj api

**Comment by EggUncle** [comment]
> i can merge for now but thjis needs to be rewritten to use the pj api

Wait a while , I tried to rewritten it by the pj api , and it work well , now I try to a new commit.

**Comment by radare** [comment]
please resolve the conflict and rebase to master, is this pr still needed affter merging the other?

**Comment by EggUncle** [comment]
I need close this pr, because it’s rewrite with pj api.

**Pull request closed without merging**
