### PR TITLE
Centos tree sitter gnu99

### PR DESCRIPTION
**Pull request by ret2libc**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

If possible, we should use `-std=gnu99` on compilers that support it. This should not be relevant for all modern compilers, as they can easily compile tree-sitter and radare2-shell-parser code, but on old compilers (e.g. CentOS 6 / RHEL6) if we don't pass that flag it won't work because of some unnamed structs/unions used in the source files.

This PR checks for support of `-std=gnu99` and use that flag.
 
**Test plan**

CI should be green, CentOS 6 build is still red because of https://github.com/radareorg/radare2/issues/16766

### CODE REVIEW

**Comment by ret2libc** [comment]
> This pull request **introduces 1 alert** when merging [d4266ee](https://github.com/radareorg/radare2/commit/d4266ee6ccfbfc1bec38dafd6221b5a056bcf5e1) into [aeeb266](https://github.com/radareorg/radare2/commit/aeeb2663979f08cd852bac86185e87df793c75b7) - [view on LGTM.com](https://lgtm.com/projects/g/radareorg/radare2/rev/pr-07aa12f599a08eacabf2e90e848a773a49aff21a)
> 
> **new alerts:**
> 
>     * 1 for Local variable hides global variable

This is completely unrelated to my PR :/

**Comment by radare** [comment]
Cmon, we all fix things unrelated to our prs every day

**Comment by ret2libc** [comment]
> Cmon, we all fix things unrelated to our prs every day
> […](#)
> On 4 May 2020, at 09:52, Riccardo Schirone ***@***.***> wrote: ﻿ This pull request introduces 1 alert when merging [d4266ee](https://github.com/radareorg/radare2/commit/d4266ee6ccfbfc1bec38dafd6221b5a056bcf5e1) into [aeeb266](https://github.com/radareorg/radare2/commit/aeeb2663979f08cd852bac86185e87df793c75b7) - view on LGTM.com new alerts: * 1 for Local variable hides global variable This is completely unrelated to my PR :/ — You are receiving this because your review was requested. Reply to this email directly, view it on GitHub, or unsubscribe.

That's why others PRs are hard to review ;) because they have a lot of completely unrelated changes :) will do another PR since you care.

**Comment by ret2libc** [comment]
Well, actually it turns out it may be related to this PR because of the error in acr. It seems that code marked by LGTM is compiled only when HAVE_LIBUV is not defined, so I think it may be related to the error I saw in acr: "HAVE_LIBUV_VERSION_1_0_0' not defined"

**Comment by ret2libc** [comment]
I think i need to wait for new acr before re-update this PR @radare

**Comment by ret2libc** [comment]
@radare I think this is ready. centos CI is still red because, as said in the first comment, it still requires https://github.com/radareorg/radare2/issues/16766 but i'd like to wait for a proper tree-sitter release before updating tree-sitter code. If they won't do a new release before 4.5.0, i'm going to update the tree-sitter code anyway.

**Pull request merged**
