### PR TITLE
r2pm: Add new command that installs package without updating git

### PR DESCRIPTION
**Pull request by zamaudio**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)

Previously, r2pm seems to switch branches to master and git pull, causing havoc for CI trying to test changes.
With this change in radare2, the following pull request in radare2-extras enables a working GitHub CI:
https://github.com/radareorg/radare2-extras/pull/265
(However the WIP change needs to be dropped so it does not use my own radare2 repo for each clone, once the r2 PR is merged).

The proof can be seen here:
https://github.com/zamaudio/radare2-extras/runs/1106054548

### CODE REVIEW

**Comment by trufae** [comment]
Why

**Comment by trufae** [comment]
This is breaking version compatibility tags support

**Comment by zamaudio** [comment]
OK, I will try force-pushing a new patch that adds a new flag `r2pm -ti <pkgname>` for test-install, and not to interfere with install target.

**Comment by zamaudio** [comment]
Latest r2 PR works here: https://github.com/zamaudio/radare2-extras/runs/1107386303

**Comment by trufae** [comment]
If its just for testing i think its better to use an env var or just change the code for testing

**Pull request closed without merging**
