### PR TITLE
Fix wording, whitespaces and other minor stuff ##doc

### PR DESCRIPTION
**Pull request by ratijas**
**Checklist**

- [x] Closing issues: #18082
- [x] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [x] I wrote some lines in the [radare2book](https://github.com/radareorg/radare2book)

**Description**

Request to rebase (replace my older commit into the mainline tree) with this new one. Fixes memory leaks, commit message and more.

---

* cconfig.c: fix whitespaces.

* cmd.c(help_msg_y):
  - elaborate on `yy` syntax;
  - replace "srcoff" with "origin".

* cmd.c(cmd_autocomplete):
  - refactor help into function: render autocomplete types with generic
    help subsystem;
  - "Types" heading now follow the "Usage" style by not being prefixed
    by a pipe character.

* cmd_anal.c: fix whitespaces & help text.

* cmd_info.c: fix help text capitalization.

* cmd_help.c: update global help text about visual mode -- it was
  outdated and overloaded.

* cmd_print.c:
  - fix `pf` cmd help;
  - TODO: what pz? is doing here?

* cons.c:
  - refactor & better document r_cons_cmd_help();
  - fix whitespaces.

* visual & panels modes:
  - as of commit 46187fe4e14dc465dc6ac03fcc56a362f0b8e335, '!' no longer
    launches the r2048 game. The game itself it broken anyway, even when
    running from the Help menu in panels mode;
  - transitioning from panels to visual is not 'entering' but actually
    swapping/replacing visual panels with just panels, thus...
  - reword 'enter into the' to 'swap into' or even just 'enter', e.g.:
    "enter into the visual panels mode" -> "enter visual panels mode";
  - remove the "(dwm style)" words from a fortune tip, because I have no
    idea what it is, and it does not appear to be a valid command in any
    of the r2 modes;
  - tweak help text for various visual modes.

* panels.c(__update_help):
  - shorten code and titles;
  - add comment to clarify that it is not a copy-paste error.

* visual.c:
  - r_core_visual_append_help(): first steps merging with function
    r_cons_cmd_help from cons.c;
  - use consistent colors for headers;
  - shuffle if-else on input commands to match alphabetical order.

* vmenus.c:
  - rename stuff, shuffle around static consts to reflect an actual
    ordering when viewing as a help text;
  - fix inline help rendering;
  - improve help page content & rendering;
  - remove unneeded break;
  - fix whitespaces;

### CODE REVIEW

**Comment by trufae** [comment]
Resolve conflicts please

**Comment by ratijas** [comment]
OK, so it's not going to be rebased in history.  In such case, I'm going to branch off the current master, revert the [WIP] commit, and cherrypick this one while resolving merge conflicts.  Is that alright?

**Comment by ratijas** [comment]
Done and done.

**Comment by ratijas** [comment]
damn, the commit message is gone though.  Is that the secret power of GitHub web-flow merging technique?

**Comment by trufae** [comment]
No, i just removed it, commits should be easy to read and concise. Should be fine with 2-5 lines after the commit message but no more

**Comment by ratijas** [comment]
I guess it's a problem of bundling too many stuff into one chunk.  I'll be splitting next time.

**Comment by trufae** [comment]
Or just dont be that much verbose describing every change is not always necessary. See orher PRs/commits how it’s the style. I mean its not a strict rule, just somewhat practical for reviewing changes later

**Comment by trufae** [comment]
Thank you!

**Pull request merged**
