### PR TITLE
Fix the static build by dynamically resolving libutil symbols ##build

### PR DESCRIPTION
**Pull request by radare**
Debian/Ubuntu doesn't seems to provide libutil.a so symbols are missing and libr.a is not purely static
We should provide a fallback with just fork imho, but at least this will keep it working

 

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by radare** [comment]
This should fix the clusterfuzz build problems, but we should have a CI task to check for static builds

**Comment by radare** [comment]
i remember the time when ptrace and libdl were not provided in libc.a  .. this whole things sucks

**Comment by ret2libc** [comment]
How do you build static build? Is it enough to do `./sys/static.sh`? If so, I can add commits to your PR to add CI tests for static build.

**Comment by radare** [comment]
Yep its just running this script

**Comment by XVilka** [comment]
```
../../libr/libr.a(run.o): In function `redirect_socket_to_pty':
/home/runner/work/radare2/radare2/libr/socket/run.c:755: undefined reference to `login_tty'
collect2: error: ld returned 1 exit status
make[2]: *** [rasm2] Error 1
make[1]: *** [all] Error 1
../rules.mk:69: recipe for target 'rasm2' failed
make[2]: Leaving directory '/home/runner/work/radare2/radare2/binr/rasm2'
make: *** [all] Error 2
Makefile:14: recipe for target 'all' failed
make[1]: Leaving directory '/home/runner/work/radare2/radare2/binr'
Makefile:56: recipe for target 'all' failed
```

**Comment by ret2libc** [comment]
@radare I have added some commits to add the GH action that runs static build. It should only be executed on pull requests that have the 'static' string in the branch name and on At 00:00 on every 7th day-of-week with a cron job. As you can see, it is still failing. Feel free to improve the PR now :)

**Comment by XVilka** [comment]
```
	ln -fs "/home/runner/work/radare2/radare2/pkgcfg/$FILE" "/usr/lib/pkgconfig/$FILE" ; done
ln: failed to create symbolic link '/usr/lib/pkgconfig/r_anal.pc': Permission denied
ln: failed to create symbolic link '/usr/lib/pkgconfig/r_asm.pc': Permission denied
ln: failed to create symbolic link '/usr/lib/pkgconfig/r_bin.pc': Permission denied
ln: failed to create symbolic link '/usr/lib/pkgconfig/r_bp.pc': Permission denied
ln: failed to create symbolic link '/usr/lib/pkgconfig/r_config.pc': Permission denied
ln: failed to create symbolic link '/usr/lib/pkgconfig/r_cons.pc': Permission denied
ln: failed to create symbolic link '/usr/lib/pkgconfig/r_core.pc': Permission denied
ln: failed to create symbolic link '/usr/lib/pkgconfig/r_crypto.pc': Permission denied
ln: failed to create symbolic link '/usr/lib/pkgconfig/r_debug.pc': Permission denied
ln: failed to create symbolic link '/usr/lib/pkgconfig/r_egg.pc': Permission denied
ln: failed to create symbolic link '/usr/lib/pkgconfig/r_flag.pc': Permission denied
ln: failed to create symbolic link '/usr/lib/pkgconfig/r_fs.pc': Permission denied
ln: failed to create symbolic link '/usr/lib/pkgconfig/r_hash.pc': Permission denied
ln: failed to create symbolic link '/usr/lib/pkgconfig/r_io.pc': Permission denied
ln: failed to create symbolic link '/usr/lib/pkgconfig/r_lang.pc': Permission denied
ln: failed to create symbolic link '/usr/lib/pkgconfig/r_magic.pc': Permission denied
ln: failed to create symbolic link '/usr/lib/pkgconfig/r_parse.pc': Permission denied
ln: failed to create symbolic link '/usr/lib/pkgconfig/r_reg.pc': Permission denied
ln: failed to create symbolic link '/usr/lib/pkgconfig/r_search.pc': Permission denied
ln: failed to create symbolic link '/usr/lib/pkgconfig/r_socket.pc': Permission denied
ln: failed to create symbolic link '/usr/lib/pkgconfig/r_syscall.pc': Permission denied
ln: failed to create symbolic link '/usr/lib/pkgconfig/r_util.pc': Permission denied
make: *** [install-pkgconfig-symlink] Error 1
Makefile:256: recipe for target 'install-pkgconfig-symlink' failed
```

**Pull request merged**
