### PR TITLE
Implement pdu

### PR DESCRIPTION
**Pull request by Lazula**
**Checklist**

- [X] Closing issues: #18739
- [X] Mark this if you consider it ready to merge
- [X] I've added tests (optional)

**Description**

Initial implementation of `pdu` commands. All of the proposed commands have been implemented except for `pdue` and they all have tests.

`r_core_print_disasm()` has been modified to add condition type and pointer arguments. Internally, each condition type can be cast from void* and placed in their own special variable. To add a new condition type, add a new entry to the condition type enumeration in r_core.h and handle it in both cmd_pdu() and r_core_print_disasm()

### CODE REVIEW

**Comment by Lazula** [comment]
If it's preferred I could just modify `r_core_print_disasm()` with the 2 condition arguments and change the loop and retry conditions.

**Comment by trufae** [comment]
Ideally we shouldnt be having more copies of the same disasm function, so maybe better to reuse a single implementation and pass a struct with custom options instead of adding more arguments

**Comment by Lazula** [comment]
For now I've just added 2 arguments to `r_core_print_disasm()`, adding an option structure is out of scope here. Will need help with `pdue` but I think everything else is covered now.

**Comment by Lazula** [comment]
Will merge it once tests finish - the ones that failed were due to an unused variable and I've commented out pdue stuff to be added later

**Pull request merged**
