### PR TITLE
Refactor signature matching ##signatures

### PR DESCRIPTION
**Pull request by swoops**
**Checklist**

- [ ] Closing issues: #issue
- [x] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [radare2book](https://github.com/radareorg/radare2book)

**Description**

Mostly refactors code. This also makes reporting of found signatures a bit more verbose (showing specific types found). 

A very minor bug was fixed. Before two different search contexts were used. This meant the match count for byte signatures was unique, while graph, refs, offset, etc all shared a second match count. Now all signatures share the same match count. 

Before you would get flags like:
```
0x00400536 37 sign.bytes.sym.print_0
0x00400440 41 sign.graph.sym.print_0
0x00400420 6 sign.graph.sym.print_1
0x00400410 6 sign.graph.sym.print_2
0x0040055b 32 sign.graph.sym.print_3
0x00400536 37 sign.graph.sym.print_4
```

Now you get:
```
0x00400536 37 sign.bytes.sym.print_0
0x00400440 41 sign.graph.sym.print_1
0x00400420 6 sign.graph.sym.print_2
0x00400410 6 sign.graph.sym.print_3
0x0040055b 32 sign.graph.sym.print_4
0x00400536 37 sign.graph.sym.print_5
```

I could easily make it so that none of the signature types share a count, if that is preferred (just use `ctxSearchCB[graph_count, offset_count, bytes_count...]` instead of `ctxSearchCB.count`). 

This fix resulted in a minor change to to one of the test files. There are still 3 broken tests, in `test/db/cmd/cmd_zignature`. All are powerpc tests. I will make a issue for this tomorrow, if there isn't one. I suspect `PowerPC r_sign_fcn_bytes bounds check` test is correct and the new powerpc analysis is masking out a relative branch when it shouldn't. I also think `PowerPC function with jumpback` test is wrong and the new ppc analysis does better. But I don't know powerpc well enough to say for sure.

### CODE REVIEW

**Comment by trufae** [comment]
The tests that fail arepeobably with capstone4. Rimraf shlr/capstone to repro

Any reason why results are not sorted by offset?

**Review by trufae — APPROVED** [review]

**Comment by chinggg** [comment]
The refactor is great though it cannot improve the zignature search during `aaa` 👍

**Comment by trufae** [comment]
@chinggg any reproducer/test to guide on this?

**Comment by swoops** [comment]
I think @chinggg is referring to a rizin issue about multiple signatures matching a single function.

This refactor is just the first step tworard dealing with signature collisions. Next pull I send will get even closer but it might take a bit. I am quick to embarrass myself with `static` functions, I am slower to embarrass myself in front of all `r_sign` namespace.

**Pull request merged**
