### PR TITLE
Fixed out-of-bound write in libbf.c

### PR DESCRIPTION
**Pull request by 3393304070**
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

### CODE REVIEW

**Comment by trufae** [comment]
We are updating quickjs right now is this bug also in the official repo?

**Comment by 3393304070** [comment]
> We are updating quickjs right now is this bug also in the official repo?

Yes I just confirmed that the same vulnerability exists in the same function in libbf.c of bellard/quickjs

**Comment by trufae** [comment]
Can you submit the same patch upstream? this way we will pick it back when @satk0 finishes updating the sync. Thank you! i'll ping @oleavr too

**Comment by 3393304070** [comment]
> Can you submit the same patch upstream? this way we will pick it back when @satk0 finishes updating the sync. Thank you! i'll ping @oleavr too

No problem, already done. Would you please close the relevant [issue](https://github.com/radareorg/radare2/issues/23317) too? Thank you!

**Pull request merged**
