### PR TITLE
arm64 branch assemble patch

### PR DESCRIPTION
**Pull request by Tigre000**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

#16158

The problem was that the n variable was an int type, and the absence of and operator of the t variable and h variable.

Debugging variable values in the original code
```
n: 40501400005FCC
addr: 1000057E8

n: F9
m: 01
h: 00
t: 00
k: 17
data: F9010017


n: 100005004
addr: 1000057E8

n: 07
m: FE
h: 3FF
t: 03
k: 17
data: 7FFFF17
```
Debugging variable values in the modify code
```
n: 100005FCC
addr: 1000057E8

n: F9
m: 01
h: 00
t: 00
k: 14
data: F9010014


n: 100005004
addr: 1000057E8

n: 07
m: FE
h: FF
t: 03
k: 17
data: 7FEFF17
```
Here are ways to solve the problem.

Declare the n variable in line 460 as the ut64 type and delete (n > 0x7ffffff) in the if statement in line 463.
To add and operater when declaring variables in line 472, 473.

https://github.com/radareorg/radare2/blob/master/libr/asm/arch/arm/armass64.c#L458
```
static ut32 branch(ArmOp *op, ut64 addr, int k) {
	ut32 data = UT32_MAX;
	ut64 n = 0;
	if (op->operands[0].type & ARM_CONSTANT) {
		n = op->operands[0].immediate;
		if (!(n & 0x3)) {
			if (n >= addr) {
				n -= addr;
			} else {
				n -= addr;
				n = n & 0xfffffff;
				k |= 3;
			}
			n = n >> 2;
			int t = (n & 0xff000000) >> 24;
			int h = (n & 0xff0000) >> 16;
			int m = (n & 0xff00) >> 8;
			n &= 0xff;
			data = k;
			data |= n << 24;
			data |= m << 16;
			data |= h << 8;
			data |= t;
		}
	} else {
		n = op->operands[0].reg;
		if (n < 0 || n > 31) {
			return -1;
		}
		n = n << 5;
		int h = n >> 8;
		n &= 0xff;
		data = k;
		data |= n << 24;
		data |= h << 16;
	}
	return data;
}
```

before

```
rasm2 -a arm -b 64 -o 0x1000057e8 "b 0x100005fcc"
f9010017

rasm2 -a arm -b 64 -o 0x1000057e8 "b 0x100005004"
07ffff17
```

after

```
rasm2 -a arm -b 64 -o 0x1000057e8 "b 0x100005fcc"
f9010014

rasm2 -a arm -b 64 -o 0x1000057e8 "b 0x100005004"
07feff17
```

This resolves the assembly error in branch on arm64

### CODE REVIEW

**Comment by XVilka** [comment]
Please fix this:
image

**Comment by Tigre000** [comment]
arm register range is 0~30.
But original code implemented range 0~31.

**Comment by radare** [comment]
can you add some tests?

**Comment by radare** [comment]
ill merge when the test is added. thanks!!

**Comment by Tigre000** [comment]
https://github.com/radareorg/radare2/blob/master/test/new/db/asm/arm_64
Do I add the tests here?

And this is how it's done?
`rasm2 -a arm -b 64 -o 0x1000057e8 "b 0x100005fcc"` -> `a "b 0x100005fcc" f9010014 [0x1000057e8 ]`

**Comment by Tigre000** [comment]
radare2 is a really good reverse engineering framework.
But there was some discomfort in the asm.
These are this full requests that I posted right now, and the examples below.

```
rasm2 -a x86 -b 64 -o 0x0040075c -d 8905ee082000
mov dword [rip + 0x2008ee], eax

rasm2 -a x86 -b 64 -o 0x0040075c "mov dword [0x00601050], eax"
40890550106000

rasm2 -a x86 -b 64 -o 0x0040075c -d 40890550106000
mov dword [rip + 0x601050], eax

rasm2 -a x86 -b 64 -o 0x0040075c "mov dword [rip + 0x2008ee], eax"
408988ee082000

rasm2 -a x86 -b 64 -o 0x0040075c -d 408988ee082000
mov dword [rax + 0x2008ee], ecx
```

I want to modify asm in the mid to long-term.
Therefore, it is likely to post issues and Pull requests periodically.
It's a little uncomfortable, but will it be okay?

**Comment by radare** [comment]
yes, you can open PRs directly instead of having to open issues all the time. just submit the PR directly and add tests so things dont break over time.

**Comment by radare** [comment]
ideally you may add assembly tests, not cmd ones. also instead of using !rasm2 you can use pa and pad to print assembly and disassembly, passing the instruction as argument

**Comment by Tigre000** [comment]
I added and modified some tests.

**Comment by radare** [comment]
All your tests are failing

30647544-C299-4D75-84CB-E576125A045B

**Comment by Tigre000** [comment]
I checked and I think I failed because of the square brackets on the offset.
Now the tests for that part is successful.

**Comment by radare** [comment]
thanks!

**Pull request merged**
