### PR TITLE
Libr/pe: Add basic RISC-V architecture knowledge

### PR DESCRIPTION
**Pull request by kallisti5**
**Checklist**

- [x] Closing issues: #18189 
- [x] Mark this if you consider it ready to merge

**Description**

  Add basic knowledge of RISC-V PE binaries (most commonly, EFI applications)

### CODE REVIEW

**Comment by kallisti5** [comment]
```
[0x00010148]> i
fd       3
file     /home/kallisti5/Code/haiku/generated.riscv64/objects/haiku/riscv64/release/system/boot/efi/haiku_loader.efi
size     0x5d65f
humansz  373.6K
mode     r-x
format   pe64
iorw     false
block    0x100
type     EXEC (Executable file)
arch     riscv
baddr    0x10000
binsz    382559
bintype  pe
bits     64
canary   false
retguard false
class    PE32+
cmp.csum 0x00068060
compiled Wed Dec 31 18:00:00 1969
crypto   false
endian   little
havecode true
hdr.csum 0x00000000
laddr    0x0
lang     c
linenum  true
lsyms    false
machine  RISC-V 64-bit
nx       false
os       efi
overlay  true
cc       ms
pic      false
relocs   false
signed   false
sanitiz  false
static   true
stripped true
subsys   EFI Application
va       true
```

**Comment by trufae** [comment]
Great! Can you submit the test file in the testbins repository and a test for it? The patch looks good!

**Comment by kallisti5** [comment]
@trufae added here:
https://github.com/radareorg/radare2-testbins/pull/58

They're MIT licensed, and are "self contained"... so a good test candidate.

As we grow the sanity of our EFI bootloaders, I can keep adding / updating them.

**Comment by kallisti5** [comment]
Added pe tests checking the machine type for EFI riscv64 and amd64/x86_64

```
$ r2r -o json db/formats/pe
Running from /home/kallisti5/Code/radare2/test
Loaded 450 tests.
Skipping json tests because jq is not available.
[XX] /home/kallisti5/Code/radare2/test/db/formats/pe/pe64 pe64 cc
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'e anal.cc' bins/pe/tls64.exe
-- stdout
@@ -1 +1 @@
-ms
+


-- stderr
WARNING: No calling convention defined for this file, analysis may be inaccurate.

[XX] /home/kallisti5/Code/radare2/test/db/formats/pe/imports_tinyW7 PE: resolve reloc name by ordinal from sdb
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'ir
ii
' bins/pe/imports_tinyW7.exe
-- stdout
@@ -2,7 +2,7 @@
 
 vaddr      paddr      type   name
 ---------------------------------
-0x8000011c 0x00000248 SET_32 kernel32_FindAtomW
+0x8000011c 0x00000248 SET_32 kernel32_Ordinal_284
 0x800004f4 0x00000234 SET_32 msvcrt_Ordinal_1268
 
 
@@ -10,6 +10,6 @@
 [Imports]
 nth  vaddr      bind type lib      name
 ---------------------------------------
-284  0x00000000 NONE FUNC kernel32 FindAtomW
+284  0x00401048 NONE FUNC kernel32 Ordinal_284
 1268 0x00401034 NONE FUNC msvcrt   Ordinal_1268
 


-- stderr
WARNING: No calling convention defined for this file, analysis may be inaccurate.

[XX] /home/kallisti5/Code/radare2/test/db/formats/pe/import_names dll import function names bug for ws2_32.dll
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc ii~&WS2_32,52 bins/pe/Lab05-01.dll
-- stdout
@@ -1 +0,0 @@
-52  0x100163cc NONE FUNC WS2_32.dll   gethostbyname


-- stderr
WARNING: No calling convention defined for this file, analysis may be inaccurate.

[450/450]                 444 OK         3 BR        3 XX        0 FX
```

**Pull request merged**
