### PR TITLE
Improve the anal reflines to support true/false lines if needed ##disasm

### PR DESCRIPTION
**Pull request by radare**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by thestr4ng3r** [comment]
Description of this pr would be nice.

**Comment by ret2libc** [comment]
Before approving, actually I would like to see a test case where this was needed, just to better understand what it does and whether it breaks something else.

**Comment by XVilka** [comment]
It breaks OpenBSD:
```
[XX] db/tools/rabin2 rabin2 -c
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '!rabin2 -c ${R2_FILE}' bins/java/test.class
-- stdout
--- .a	Mon Apr 20 09:11:45 2020
+++ .b	Mon Apr 20 09:11:45 2020
@@ -1,9 +0,0 @@
-0x00000000 [0x000008f9 - 0x00000b99]    672 class 0 test :: groovy/lang/Script
-0x000008f9 method 0      <init>
-0x0000092e method 1      <init>
-0x0000096e method 2      main
-0x000009ae method 3      run
-0x00000aba method 4      $getStaticMetaClass
-0x00000afb method 5      $createCallSiteArray_1
-0x00000b6a method 6      $createCallSiteArray
-0x00000b99 method 7      $getCallSiteArray


-- stderr
[X] r_bin_java_code_attr_new: Error unable to parse remainder of classfile after Method's Code Attribute: 1.
Segmentation fault (core dumped) 
```

**Comment by thestr4ng3r** [comment]
OpenBSD failure is unrealted, I resubmitted and it works here: https://builds.sr.ht/~thestr4ng3r/job/191345
But we should make an issue for this and test with valgrind.

**Comment by thestr4ng3r** [comment]
Issue: #16659

**Pull request merged**
