### PR TITLE
Fix type matching with loaded PDB ##anal

### PR DESCRIPTION
**Pull request by GustavoLCR**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

This fixes getting a flag in the wrong flagspace

Use r_flag_get_by_spaces() instead of manually comparing the flagspace name

**Test plan**

Tests pass

### CODE REVIEW

**Comment by ret2libc** [comment]
> This PR contains A LOT of changes in different places not just in PDB, like improving the HTTP apis, so it will be good if next time we refactor/squash the commits accordingly. and have multiple separate commits with grouped changes

BTW, this is not an easy thing to do and it is something that should be done by those who submit PRs. It is, in some cases, a lot of work to do and something that, for some people (especially if not very familiar with git) can become annoying and frustrating, when it involves rebases, fixes due to comments in PRs, etc.

Do we really want to enforce that? I am not sure personally. Anyway, we have never logically split commits, because usually we just do squash+merge.

**Comment by trufae** [comment]
If the PR gets big enough and the changes can be easily grouped i think
it's worth doing it, adjusting the commit message to explain all the
changes in 1 line and add the ## tag should be the minimum requirement, and
this is task of the one merging the PR.

I understand requesting this to the contributors can be a pain, and this
won't apply to all the PRs, but it makes reading git log much easier that
way.

**Comment by ret2libc** [comment]
> If the PR gets big enough and the changes can be easily grouped i think it's worth doing it, adjusting the commit message to explain all the changes in 1 line and add the ## tag should be the minimum requirement, and this is task of the one merging the PR. I understand requesting this to the contributors can be a pain, and this won't apply to all the PRs, but it makes reading git log much easier that way.

Using a good 1-line message and adding the ##tag can be done by the one merging the PR. Splitting the commits, no, as it is too much work usually. It would require a lot of extra work, because you need to carefully rebasing, re-ordering commits, fixup, etc. IMO it shall either be done by the one who writes the PR or not done at all. In the Linux Kernel, at least, they require people who submit changes to carefully arranging the commits.

That said, IMHO we are not at the point of requesting this kind of dedication from contributors, as it would make contributing much harder and painful.

**Comment by trufae** [comment]
👍

**Pull request merged**
