### PR TITLE
Regcomp

### LINKED ISSUE #16549: RRegex.comp() leaks if called after .new()
calling r_regex_comp after r_regex_new is leaking because its initializing it twice, the leak should be fixed, so maybe worth to open an issue

see https://github.com/radareorg/radare2/commit/fdb75d3bf9a3d09f3c95ca0bed0bfb5eaab02684

and  https://github.com/radareorg/radare2/issues/15888

### PR DESCRIPTION
**Pull request by Explainaur**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

Calling `r_regex_comp` after `r_regex_new` is leaking because its initializing `preg->re_g` twice.
Added check before alloc memorys for `re_guts`.

**Closing issues**

closes #16549

### CODE REVIEW

**Comment by ret2libc** [comment]
Hi! Thanks for your contribution.

I think `RRegex` API needs a bit of polishing. In particular, it seems `r_regex_comp` is actually an init method, so it should not be called on a RegEx that has already been created with `r_regex_new`. I don't think we should try to check and fix wrong usage of the regex API in this way. Being a init method, the `preg` pointer could point to uninitialized memory and it is the duty of `r_regex_comp` to initialize the fields of that structure.

BTW, if you are willing to, I believe it would help a lot to add some unit tests for the RegEx API. You can have a look at how that's done for files like `test/unit/test_list.c`, etc.

**Comment by Explainaur** [comment]
Hi! Thank you for your suggestions.
I'd like to add some unit tests for the RegEx API.
Should I close this pull request or continue improve the RegEx API?

**Comment by ret2libc** [comment]
You can keep this PR open and just keep adding commits to your branch.
Since `r_regex_comp` seems to be a init method, I'd say that the additional check you put is not necessary, as that is the result of a wrong API use. If one wants to use `r_regex_new` + `r_regex_comp` he should call himself a `r_regex_fini` before doing the `_comp` call.

**Comment by ret2libc** [comment]
Hi @Explainaur , is everything still ok with this PR? Do you need help with anything? If so, don't hesitate to ask.

**Comment by Explainaur** [comment]
Hi, Thanks for your help very much. I'm so sorry that I am busy preparing for final exams recently.
I'll get to work as soon as possible. I'll read the code for unit tests.

**Comment by ret2libc** [comment]
Ok, don't worry. Just wanted to be sure you knew how to proceed. Take your time ;)

**Comment by XVilka** [comment]
Moving to the next release.

**Comment by Explainaur** [comment]
HI, I think maybe I need more time to read more source code of radare2. Thank you for your help ;)
I hope I can make contribution in the near future.

**Comment by trufae** [comment]
You are welcome!

**Pull request closed without merging**
