### PR TITLE
rahash2 -B behavior

### PR DESCRIPTION
**Pull request by jukuisma**
- [x] Mark this if you consider it ready to merge
- [x] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

Fixes: https://github.com/radareorg/radare2/issues/23371

### CODE REVIEW

**Comment by trufae** [comment]
Why in draft?

**Comment by jukuisma** [comment]
> Why in draft?

Because I didn't have time to thoroughly test the changes yesterday. Granted, the changes seem kind of trivial and the tests pass. Also, I did leave one open question, but it doesn't seem to be showing to anyone else than me:
image
I'm more familiar with gitlab instead of github :sweat_smile:

**Comment by trufae** [comment]
iirc passing null as the buffer is used to initialize the selected hashing plugin. i would keep it commented, because it will be easier to spot later if anything else fails, but iimho if tests pass is the way to go. and i would like to refactor the hash api during the 6.0 transition so this commented line may help us find that. also, adding more tests will help us identify other issues when refactoring

**Comment by jukuisma** [comment]
> iirc passing null as the buffer is used to initialize the selected hashing plugin. i would keep it commented, because it will be easier to spot later if anything else fails, but iimho if tests pass is the way to go. and i would like to refactor the hash api during the 6.0 transition so this commented line may help us find that. also, adding more tests will help us identify other issues when refactoring

I can add that line commented out and some more test cases later tonight. Maybe around 17:00 UTC.

**Comment by trufae** [comment]
the world can wait ;) feel free to add more tests in case you find them useful/related to the issue. thank you!

**Comment by jukuisma** [comment]
Added the removed line back, but left it commented out to fix this bug. Didn't add any more test cases. Rahash2 doesn't seem to support calculating checksums of empty files and while we could copy paste similar new test cases for other algorithms, it seems a bit redundant.

Ready to merge on my behalf.

**Pull request merged**
