### PR TITLE
Handle COND_AL and COND_NV in analysis ##anal

### PR DESCRIPTION
**Pull request by lowlyw**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

if a RAnalOp is properly filled out, in some archs, there can be ALWAYS or NEVER conditionals.
anal should take this into consideration and treat them as either a NOP (never) or as a non conditional (ALWAYS).

...

**Test plan**

i'm adding support for another arch that supports this and will pr this soon

...

**Closing issues**
n/a

### CODE REVIEW

**Comment by lowlyw** [comment]
holy cow... how the hell did this break so many tests?

**Comment by XVilka** [comment]
Most of these tests look autogenerated, so it makes sense, e.g. signatures/FLIRT ones.

**Comment by kazarmy** [comment]
I think this suggests that `op->cond` doesn't always have a valid value. Also,
https://github.com/radareorg/radare2/blob/fb1190d248b09849fd29c9c5854bb32919d83929/libr/include/r_anal.h#L493
Maybe check `op->type` first  before `op->cond`?

**Comment by lowlyw** [comment]
@kazarmy that shouldn't matter tbh, it's only clearing the cond bit if it is already set, i can change it to be more clear, but in theory it doesn't matter.

**Comment by kazarmy** [comment]
It matters because
https://github.com/radareorg/radare2/blob/5f0be49fd16fadb8c6338d0807f3de65c5fb1e0e/libr/include/r_anal.h#L500
combines really well with, e.g.:
https://github.com/radareorg/radare2/blob/5f0be49fd16fadb8c6338d0807f3de65c5fb1e0e/libr/core/canal.c#L982

Unfortunately another reason is that even for `op->type & R_ANAL_OP_TYPE_COND`, `op->cond` may not be set or not set properly. For example

bb_je

there's a `je` at the end of the basic block at 0x3960 and it's clearly neither COND_AL nor COND_NV.

**Comment by radare** [comment]
Any chance to check this @lowlyw ?

**Comment by trufae** [comment]
ping

**Comment by trufae** [comment]
@lowlyw  any time for this?

**Comment by trufae** [comment]
can you rebase this PR on top of master? we are now using capstone5 and many tests has changed. will be good what are the current results

**Comment by trufae** [comment]
@aemmitt-ns @crowell what are the plans for this PR? can we close it? i think this was also affecting the esilsolver, so if it can help to simplify some future logics we may think on handling those conditional instruction

**Comment by trufae** [comment]
Closing, timeout

**Pull request closed without merging**
