### PR TITLE
add NES ROM mirroring

### LINKED ISSUE #15122: NES bank mirroring not working
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86-64
| File format of the file you reverse (mandatory)      | NES ROM
| Architecture/bits of the file (mandatory)            | 6052 16bit
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.0.0-git 22866 @ linux-x86-64 git.3.9.0-52-gaa6e232a3 commit: aa6e232a3f6508632b2b6aad36204b52eaba1af7 build: 2019-09-26__09:27:19

### Expected behavior
ROM uses mapper 0 (https://wiki.nesdev.com/w/index.php/NROM), thus having its code located at 0x8000-0xBFFF, with a mirrored version at 0xC000-0xFFFF

### Actual behavior
Primary code at 0x8000 is present, but the mirrored version is not there. This breaks a lot of jumps that target addresses in the mirrored region, thus making control flow analysis hard. But I think r2 somehow knows that it should have something at 0xC000, as this region is filled with zero-bytes instead of 0xFF like the surroundings.

### Steps to reproduce the behavior 
The binary causing this issue is this year's FlareOn "snake" challenge (not sure if sharing it is appreciated while the competition is still ongoing)

### PR DESCRIPTION
**Pull request by Masrepus**
This fixes #15122

### CODE REVIEW

**Comment by radare** [comment]
Please use tabs to indent instead of spaces

**Comment by radare** [comment]
ill fix the red test before merging. the pr looks good, thanks!

**Comment by Masrepus** [comment]
Ah alright, will change it to tabs

**Comment by Masrepus** [comment]
Somehow the reformat script does not make the nes_specs.h look like it should, but unfortunately I don't know why

**Pull request merged**
