### PR TITLE
Fix issues in the indent-example file :facepalm:

### PR DESCRIPTION
**Pull request by trufae**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

example files should be correct. also i think doc/ needs A LOT of cleanup

* [ ] char * vs char*
* [ ] enum
* [ ] R_API
* [ ] R_IPI
* [ ] R_OWN
* [ ] ... (please add more stuff you miss from this file)

**Test plan**

just read and chk, also i think we are missing a bunch of syntax things like multiline ternary operator expressions, enums, R_API, R_IPI, relative includes, etc.. feel free to suggest more changes or commit in here

**Closing issues**

I prefer to read a .c file than a long md explaining how should i write a C file, ther'es no issue for that, but i think this example must be extended a lot

### CODE REVIEW

**Comment by trufae** [comment]
lol? is master red? im only touching a file in doc/ and its failing to build?

**Comment by trufae** [comment]
To pack ints together

**Comment by trufae** [comment]
Why merged?? The issue had several open questions to discussion

**Comment by ret2libc** [comment]
Because you put no `draft`, no `wip`, you got one approval from xvilka and you didn't say "no it's wip" and you got another approval from me. So it got merged. The changes look right.

**Comment by trufae** [comment]
also the :facepalm: shouldnt go into the commit history.. but anyway, i guess it's hard for a bot to determine that without the draft/wip tag, my fault

**Comment by ret2libc** [comment]
> also the facepalm shouldnt go into the commit history.. but anyway, i guess it's hard for a bot to determine that without the draft/wip tag, my fault

I am not a bot and indeed the facepalm did not go in the commit history, as you can see in https://github.com/radareorg/radare2/commit/bf88eaeba4db92c86b14f30f9f278efd0797ffdc .

**Pull request merged**
