### PR TITLE
Fix storing RRegisterType in 'item' variable of RRegItem 

### PR DESCRIPTION
**Pull request by x0urc3**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [X] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

Variable 'arena' is being used to store RRegisterType which is wrong. Right now this does not break anything. However 'arena' variable should be used to track old register value i.e. Issue #15962 

https://github.com/radareorg/radare2/blob/7a314accc323c84b6420c48f10ee8743a6a37063/libr/include/r_reg.h#L89-L100

### CODE REVIEW

**Comment by radare** [comment]
can you add a test?

**Comment by XVilka** [comment]
Worth merging in 4.3.0 if green.

**Comment by XVilka** [comment]
Broke xmm tests:
```
[XX] db/archos/linux-x64/dbg_drm drm xmm registers - explicit packing all regs  620

$ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -d -i /tmp/tmp-17110WrzqDtDlcA2k ../bins/elf/allxmm

16ds

drm

drmq

drmd

drmw

drmb

-xmm0 = 0x408ccccd40533333400ccccd3f8ccccd

-xmm1 = 0x410ccccd40f6666640d3333340b00000

-xmm2 = 0x40533333401333333fa666663e99999a

-xmm3 = 0x4059999a4019999a3fb333333ecccccd

-xmm4 = 0x40600000402000003fc000003f000000

-xmm5 = 0x40666666402666663fcccccd3f19999a

-xmm6 = 0x406ccccd402ccccd3fd9999a3f333333

-xmm7 = 0x410666664104cccd410333334101999a

-xmm8 = 0x411666664114cccd411333334111999a

-xmm9 = 0x412666664124cccd412333334121999a

-xmm10 = 0x413666664134cccd413333334131999a

-xmm11 = 0x414666664144cccd414333334141999a

-xmm12 = 0x415666664154cccd415333334151999a

-xmm13 = 0x416666664164cccd416333334161999a

-xmm14 = 0x417666664174cccd417333334171999a

-xmm15 = 0x41833333418266664181999a4180cccd

-xmm0  = 0x400ccccd3f8ccccd 0x408ccccd40533333

-xmm1  = 0x40d3333340b00000 0x410ccccd40f66666

-xmm2  = 0x3fa666663e99999a 0x4053333340133333

-xmm3  = 0x3fb333333ecccccd 0x4059999a4019999a

-xmm4  = 0x3fc000003f000000 0x4060000040200000

-xmm5  = 0x3fcccccd3f19999a 0x4066666640266666

-xmm6  = 0x3fd9999a3f333333 0x406ccccd402ccccd

-xmm7  = 0x410333334101999a 0x410666664104cccd

-xmm8  = 0x411333334111999a 0x411666664114cccd

-xmm9  = 0x412333334121999a 0x412666664124cccd

-xmm10 = 0x413333334131999a 0x413666664134cccd

-xmm11 = 0x414333334141999a 0x414666664144cccd

-xmm12 = 0x415333334151999a 0x415666664154cccd

-xmm13 = 0x416333334161999a 0x416666664164cccd

-xmm14 = 0x417333334171999a 0x417666664174cccd

-xmm15 = 0x4181999a4180cccd 0x4183333341826666

-xmm0  = 0x3f8ccccd 0x400ccccd 0x40533333 0x408ccccd

-xmm1  = 0x40b00000 0x40d33333 0x40f66666 0x410ccccd

-xmm2  = 0x3e99999a 0x3fa66666 0x40133333 0x40533333

-xmm3  = 0x3ecccccd 0x3fb33333 0x4019999a 0x4059999a

-xmm4  = 0x3f000000 0x3fc00000 0x40200000 0x40600000

-xmm5  = 0x3f19999a 0x3fcccccd 0x40266666 0x40666666

-xmm6  = 0x3f333333 0x3fd9999a 0x402ccccd 0x406ccccd

-xmm7  = 0x4101999a 0x41033333 0x4104cccd 0x41066666

-xmm8  = 0x4111999a 0x41133333 0x4114cccd 0x41166666

-xmm9  = 0x4121999a 0x41233333 0x4124cccd 0x41266666

-xmm10 = 0x4131999a 0x41333333 0x4134cccd 0x41366666

-xmm11 = 0x4141999a 0x41433333 0x4144cccd 0x41466666

-xmm12 = 0x4151999a 0x41533333 0x4154cccd 0x41566666

-xmm13 = 0x4161999a 0x41633333 0x4164cccd 0x41666666

-xmm14 = 0x4171999a 0x41733333 0x4174cccd 0x41766666

-xmm15 = 0x4180cccd 0x4181999a 0x41826666 0x41833333

-xmm0  = 0xcccd 0x3f8c 0xcccd 0x400c 0x3333 0x4053 0xcccd 0x408c

-xmm1  = 0x0000 0x40b0 0x3333 0x40d3 0x6666 0x40f6 0xcccd 0x410c

-xmm2  = 0x999a 0x3e99 0x6666 0x3fa6 0x3333 0x4013 0x3333 0x4053

-xmm3  = 0xcccd 0x3ecc 0x3333 0x3fb3 0x999a 0x4019 0x999a 0x4059

-xmm4  = 0x0000 0x3f00 0x0000 0x3fc0 0x0000 0x4020 0x0000 0x4060

-xmm5  = 0x999a 0x3f19 0xcccd 0x3fcc 0x6666 0x4026 0x6666 0x4066

-xmm6  = 0x3333 0x3f33 0x999a 0x3fd9 0xcccd 0x402c 0xcccd 0x406c

-xmm7  = 0x999a 0x4101 0x3333 0x4103 0xcccd 0x4104 0x6666 0x4106

-xmm8  = 0x999a 0x4111 0x3333 0x4113 0xcccd 0x4114 0x6666 0x4116

-xmm9  = 0x999a 0x4121 0x3333 0x4123 0xcccd 0x4124 0x6666 0x4126

-xmm10 = 0x999a 0x4131 0x3333 0x4133 0xcccd 0x4134 0x6666 0x4136

-xmm11 = 0x999a 0x4141 0x3333 0x4143 0xcccd 0x4144 0x6666 0x4146

-xmm12 = 0x999a 0x4151 0x3333 0x4153 0xcccd 0x4154 0x6666 0x4156

-xmm13 = 0x999a 0x4161 0x3333 0x4163 0xcccd 0x4164 0x6666 0x4166

-xmm14 = 0x999a 0x4171 0x3333 0x4173 0xcccd 0x4174 0x6666 0x4176

-xmm15 = 0xcccd 0x4180 0x999a 0x4181 0x6666 0x4182 0x3333 0x4183

-xmm0  = 0xcd 0xcc 0x8c 0x3f 0xcd 0xcc 0x0c 0x40 0x33 0x33 0x53 0x40 0xcd 0xcc 0x8c 0x40

-xmm1  = 0x00 0x00 0xb0 0x40 0x33 0x33 0xd3 0x40 0x66 0x66 0xf6 0x40 0xcd 0xcc 0x0c 0x41

-xmm2  = 0x9a 0x99 0x99 0x3e 0x66 0x66 0xa6 0x3f 0x33 0x33 0x13 0x40 0x33 0x33 0x53 0x40

-xmm3  = 0xcd 0xcc 0xcc 0x3e 0x33 0x33 0xb3 0x3f 0x9a 0x99 0x19 0x40 0x9a 0x99 0x59 0x40

-xmm4  = 0x00 0x00 0x00 0x3f 0x00 0x00 0xc0 0x3f 0x00 0x00 0x20 0x40 0x00 0x00 0x60 0x40

-xmm5  = 0x9a 0x99 0x19 0x3f 0xcd 0xcc 0xcc 0x3f 0x66 0x66 0x26 0x40 0x66 0x66 0x66 0x40

-xmm6  = 0x33 0x33 0x33 0x3f 0x9a 0x99 0xd9 0x3f 0xcd 0xcc 0x2c 0x40 0xcd 0xcc 0x6c 0x40

-xmm7  = 0x9a 0x99 0x01 0x41 0x33 0x33 0x03 0x41 0xcd 0xcc 0x04 0x41 0x66 0x66 0x06 0x41

-xmm8  = 0x9a 0x99 0x11 0x41 0x33 0x33 0x13 0x41 0xcd 0xcc 0x14 0x41 0x66 0x66 0x16 0x41

-xmm9  = 0x9a 0x99 0x21 0x41 0x33 0x33 0x23 0x41 0xcd 0xcc 0x24 0x41 0x66 0x66 0x26 0x41

-xmm10 = 0x9a 0x99 0x31 0x41 0x33 0x33 0x33 0x41 0xcd 0xcc 0x34 0x41 0x66 0x66 0x36 0x41

-xmm11 = 0x9a 0x99 0x41 0x41 0x33 0x33 0x43 0x41 0xcd 0xcc 0x44 0x41 0x66 0x66 0x46 0x41

-xmm12 = 0x9a 0x99 0x51 0x41 0x33 0x33 0x53 0x41 0xcd 0xcc 0x54 0x41 0x66 0x66 0x56 0x41

-xmm13 = 0x9a 0x99 0x61 0x41 0x33 0x33 0x63 0x41 0xcd 0xcc 0x64 0x41 0x66 0x66 0x66 0x41

-xmm14 = 0x9a 0x99 0x71 0x41 0x33 0x33 0x73 0x41 0xcd 0xcc 0x74 0x41 0x66 0x66 0x76 0x41

-xmm15 = 0xcd 0xcc 0x80 0x41 0x9a 0x99 0x81 0x41 0x66 0x66 0x82 0x41 0x33 0x33 0x83 0x41

EXPECT=''

[XX] db/archos/linux-x64/dbg_drm drm set xmm registers  630
```

**Comment by x0urc3** [comment]
- Found few places where xmm registers are defined as FPU type
- The one that specifically broke drm test with commit  f13d98c is here
https://github.com/radareorg/radare2/blob/d88a76d2dfd04602de136f9628326384a5611cf4/libr/debug/p/native/linux/reg/linux-x64.h#L156-L162
- Still figuring where is the problem

**Comment by XVilka** [comment]
Please rebase.

**Comment by radare** [comment]
still red

**Comment by x0urc3** [comment]
Yes. Linux ptrace combine both FPU and XMM in a single struct. Still figuring how to split and place them into different arena

**Comment by x0urc3** [comment]
I am closing this PR and trying again. Will split fix into smaller PR

**Pull request closed without merging**
