### PR TITLE
Add internal help for axtj ##core

### PR DESCRIPTION
**Pull request by officialcjunior**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

Add internal usage help for the `axtj` command.

**Test plan**

- [ ] See if there's anything to be added.

**Closing issues**

None

### CODE REVIEW

**Comment by karliss** [comment]
There is also `axtg`, `axtq` and `axt*`. Maybe be it should be separate list.

**Comment by officialcjunior** [comment]
Okay.
What should the help return for `axtg` and `axt*` ?

**Comment by trufae** [comment]
the * suffix is for spitting r2 commands to set flags on those xrefs

The `axtg` will print r2 commands to generate a graph using the agn/age commands
Also, can you add the help for `axt?` ? right now it shows nothing.

@ret2libc how's the recursive help magic in the newshell? any feedback on this? i dont know the results of the poll you did

**Comment by officialcjunior** [comment]
```
[0x080483e0]> axt?
Usage: ax[gjq*]  find data/code references
| axtj [addr]  find data/code references to this address and print in json format
| axtg [addr]  display commands to generate graphs according to the xrefs
| axtq [addr]  find and list the data/code references in quiet mode
| axt* [addr]  set flags on the corresponding xrefs
| axt?         Show this help
```
Alright?
Should it display `[addr]` as a command line argument, like most of them in `ax?` or just the sentences?

---

And about 
> Also, can you add the help for `axt?` ? right now it shows nothing.

Does this meets what you're talking about?

---
And one last thing:
Right now, to me, it looks like the code for `axtj`is on a [weird position](https://github.com/radareorg/radare2/blob/master/libr/core/cmd_anal.c#L7434). Can I move that under the code of `axt*` and the function call to this help message after that? That is, before the `else` which takes care of `axt`?

**Comment by officialcjunior** [comment]
> can you also add a help for `axt?`

I'm sorry, I don't understand. What do you mean by 'help'?
I have posted a draft of what comes under `axt?`above.

**Comment by trufae** [comment]
axt? shows nothing, you must ad the '?' handdler under axt and add another array of help strings for it.

Screenshot 2020-07-19 at 13 07 55

also the openbsd test is failing because the PR is not rebase

**Comment by officialcjunior** [comment]
I screwed up this PR. I think, It's better to close this?

**Comment by karliss** [comment]
@officialcjunior Assuming that by breaking you meant pushing the wrong thing into branch you didn't have to close the PR. You could have fixed it by force pushing fixed branch on top of the one that is used for this PR.

**Pull request closed without merging**
