### PR TITLE
Try to test with PowerPC and SystemZ

### PR DESCRIPTION
**Pull request by XVilka**
Lets see if it works (though [ARM64 didn't](https://github.com/radareorg/radare2/pull/15393)).

For more information see [Build your open source projects on IBM Power and IBM Z CPU architecture](https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z) blog post from Travis CI.

### CODE REVIEW

**Comment by XVilka** [comment]
Same problem as with ARM64... They lied about the support - none of the announced work.

**Comment by XVilka** [comment]
Ok, now it works, we need to disable docker for these builds.

**Comment by XVilka** [comment]
See https://github.com/radareorg/radare2/issues/15468

**Comment by radare** [comment]
uhm, this means that we can have a shell in a systemz arch? so we can ipmlement the nativve debugger  for it for example :?

**Comment by radare** [comment]
Screenshot 2019-11-18 at 01 43 57

**Comment by XVilka** [comment]
Strangely, it doesn't include these multi-arch builds in `allowed_failures`...

**Pull request merged**
