### PR TITLE
Move #!v out of core (it's now available via r2pm) ##lang

### PR DESCRIPTION
**Pull request by trufae**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

V is evolving and some compiler changes made this plugin not to work on the latest version of Git. I have submitted some fixes in V to make this plugin easier to use as well as created a separate V module to provide better apis to interact with r2 as well as improve the support for global const variables, shared libraries and plugin initialiazers.

This PR is wip because there are still more things to be addressed in r2, V and v-r2 to get this fully working in a clean way. This PR is left here to keep up for future updates on the support for V in r2

**Test plan**

There are no tests for any of the lang plugins, may be worth adding some

```go
$ cat pipe-inr2.v
pub fn entry(core &R2) {
	hello_world := core.cmd('?e hello world')
	eprintln('hello_world $hello_world')
}

$ r2 -i pipe-inr2.v -
```

**Closing issues**

none

**Known issues**

* [ ] module statement should be stripped from the .v file
* [ ] import statements must be prepended
* [ ] Vinit is called with the constructor attribute, it's worth calling it directly via `C._vinit()`

### CODE REVIEW

**Comment by XVilka** [comment]
I am not a big fan of V but since this shipped in r2, shouldn't this become the part of 4.5?

**Comment by ret2libc** [comment]
Or.... Shall we remove V? 🤪

**Comment by XVilka** [comment]
@trufae why extras? We have a separate repository for "lang" plugins: https://github.com/radareorg/radare2-rlang

**Comment by trufae** [comment]
Sorry i didnt took enough coffee. yes i moved it to r2-rlang repo, see thec ommits, i just mistype this thing here (brewing more coffee now)

**Pull request merged**
