### PR TITLE
Fix the type used for the fini callback in r_arch_plugin_t ##arch

### PR DESCRIPTION
**Pull request by jmaselbas**
The fini callback has a type (RArchPluginFiniCallback) use that.

### CODE REVIEW

**Comment by trufae** [comment]
Good catch! Unfortunately this breaks the abidiff ci test. So we should wait for 5.9 to merge this. Despite i think both init a d finive the sane signature and shouldnt be breaking anything, so maybe thats a bug that shoukd be reported to libabigail/abidiff. I will check this and report them back :)

thanks!

**Comment by jmaselbas** [comment]
Yes, they both share the same signature so it is just a name, types are compatible. But it better to keep them separated if they need to be different in the future. This can easy wait for the 5.9 release

**Comment by trufae** [comment]
Seems like this is properly handled with abidiff from git.. must chk with abidiff2.2, which is the last release. but ubuntu-latest... ships an ancient version (2.0) and i have to see how this can be updated in github and try again. but your change doesnt breaks the abi :)

**Comment by trufae** [comment]
I can confirm it's fixed in abidiff 2.2 :) it's just coz ubuntu22.02 is too old

**Pull request merged**
