### PR TITLE
Dalvik fix

### PR DESCRIPTION
**Pull request by aemmitt-ns**
**Checklist**

- [ ] Closing issues: #issue
- [x] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [radare2book](https://github.com/radareorg/radare2book)

**Description**

These changes simply fix the conditionals for dalvik analysis by just using the inequality operators (<,>,<=,...) instead of flag bits. The previous expressions were wrong, and the new ones are clearer anyway. With these changes we can now correctly ESIL emulate all static dalvik code.

### CODE REVIEW

**Comment by aemmitt-ns** [comment]
checks are passing and I think this is all ready to go

**Comment by trufae** [comment]
Yeah sorry im having a migraine day. The patch lgtm. But its on the plan to remove all the >,<,>=.. operators from esil. Flags should be enough. So i would suggest adding a test to confirm the currwnt correct behaviour doesnt breaks when switching to the flag bits thing

**Comment by aemmitt-ns** [comment]
Oh ok. Personally i think we should keep the inequalities, or at least `<` from which we could derive the others easily. If we want ESIL to be easy to write in the console it would be a bad choice to remove. Its too difficult to write the correct expressions quickly with the flag ops, $c and $b are especially confusing. But i think keeping one is a good compromise.

**Comment by trufae** [comment]
I implemented esil macros to support such meta instructions, they should be reimplemented, i also prefer them more readable. But internally the real opcodes should be he minimum as possible

**Pull request merged**
