### PR TITLE
WIP: Use Bionic for Travis

### PR DESCRIPTION
**Pull request by XVilka**
To kill that pre-C99 GCC

### CODE REVIEW

**Comment by radare** [comment]
all the debuggers look broken

**Comment by XVilka** [comment]
Stupid Travis. Lets try Bionic then.

**Comment by XVilka** [comment]
Asked a question here: https://travis-ci.community/t/travis-and-ptrace/5953

**Comment by XVilka** [comment]
Seems these are the answer:
- https://docs.docker.com/engine/security/seccomp/
- https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities

**Comment by radare** [comment]
please rebase. r2 builds on bionic, so it shuold be green

**Comment by radare** [comment]
rebase or close

**Pull request closed without merging**
