### PR TITLE
Windows r2r: Actually display emojis (on consoles that support them)

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

This pr fixes Windows r2r so that it actually tries to display its emojis.

Seen on Windows Terminal 0.11.1251.0:
Windows_Terminal_emoji

Seen on alacritty 0.5.0-dev (7901b45):
Alacritty_emoji

There appears to be full support from Windows Terminal, and partial support from alacritty and mintty (3.1.0), though this could be due to my lack of knowledge regarding font setup for them. Support for Conhost is somewhere ["in the future"](https://github.com/microsoft/terminal/issues/190#issuecomment-562731321) apparently.

**Test plan**

Do `r2r -i` with failing `cmd` tests. The emojis should be displayed like on Linux.

**Closing issues**

...

### CODE REVIEW

**Comment by radare** [comment]
Shouldnt this be implemented in RCons instead?

**Comment by kazarmy** [comment]
r2r doesn't have a dependency on RCons ... i don't think it needs to

**Comment by kazarmy** [comment]
The fixes to RCons so that it becomes a responsible Windows citizen with regard to the active code page, should be in an entirely different pr imho

**Comment by radare** [comment]
Well.. r2r is full of code thst shuold be moved outside into libr.

Pxe command should work in windows too

**Pull request merged**
