### PR TITLE
Install jq to AppVeyor

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by XVilka** [comment]
@thestr4ng3r seems stuck forever if `jq` is installed.

**Comment by thestr4ng3r** [comment]
Yeah this should be fixed. However I don't think we should run json tests on windows. It should be enough to have them on one job, which should be the fastest one.

**Comment by radare** [comment]
Agree

**Comment by radare** [comment]
Screenshot 2020-04-14 at 00 59 47

**Comment by radare** [comment]
can we merge ths? pls rebase for maximum greenness

**Comment by thestr4ng3r** [comment]
Or just close, as said I don't think we should test json on windows.

**Comment by XVilka** [comment]
Yes, too slow anyway.

**Pull request closed without merging**
