### PR TITLE
Reintroduce bugs to get new contributors

### PR DESCRIPTION
**Pull request by radare**
We have been losing some contributors lately and after careful evaluation of the situation, the core team have determined that the main reason for this is the lack of bugs in our codebase.

This PR aims to reintroduce some old bugs, as well as some freshly new ones in order to promote the arrival of more contributors.

The radare team will be taken more drastic measures over time to ensure the developers and vulnerability finders feel motivated again with the project.

Sincerely,
 The Radare Core Team

### CODE REVIEW

**Comment by kazarmy** [comment]
s390x_XX

Still red. I don't know why we still support s390x  ∗grumble∗  ∗grumble∗

**Comment by JonPizza** [comment]
Why not just delete the whole code base?

**Comment by radare** [comment]
Now the PR is green and ready to merge

**Comment by chrepl** [comment]
Hello r2 Team 👨‍💻

I hope, I can contribute some suggestions and my point of view, why I was leaving r2 not as a contributor but as a user. Mainly I extend the core of r2 years ago at my own, but because of r2 core doesn't fixed old bugs but added new features that doesn't really needed I go step back to my old toolchains and never looked back.

Maybe I get wrong, I'm not really up-to-date anymore with the r2 project but this is my suggestions, opinions, feelings and point of view please correct me if I'm wrong, but don't blame me.

I think r2 have a missing main scopes for the community, a philosophical or functionalities not be primarily aimed. From the readme,`r2 is a rewrite from scratch of radare in order to provide a set of libraries and tools to work with binary files.` this scope or feature sets are heavy to maintain.

What I got see is the core is blowing with features that are nice to be had for analyzing, inspecting and debugging and everything between them for any kind of binaries, but the end of the day it's not really necessarily needed, i.e like creating QR codes, mounting Volumes or inspecting Protobuf files and so one. This is all nice and a great work and huge energy and motivation behind them but this requires also the scope of more than one specific target group of users.

Maintaining a project or toolchains with all these features for more than one group of communities, makes the core team aim more sections of behaviors of the huge core that it is easy to get out of the  primary scope or even worse, these get outdated and more buggy.
The main focus, energy, motivation, and priority getting lost.

Fixing old bugs, working on new necessary feature sets or aim to scope the main behaviors of the core functionalities like anal, dis, asm should be the primary scope.

My suggestion would be, create a clarify meaning of what is r2 to be aimed, what is the priority focus, whats differ from other projects and important what it's not to be.

Second, split or move step by step, these features that are not necessarily by the core, maintained out of the core scope and only aimed at a specific group of users, for all these create an own group with projects that extend the r2 project.

These projects have clarified scopes, vision and focus to extend the r2 core with functionalities.
i.e Inspecting proto binaries for community groups that are mainly working with Protobuf not needed to include it inside the core. It can be maintained outside for a specific group, so the core can be more focused on what matters.

Here are some example names, that I adopt from other open-source projects github.com/radareorg-incubator or github.com/radareorg-sig (adopted by Kubernetes-SIG / Special Interests Group).

I hope this clarifies my point of view and my reasons for choosing why I went to step back.

Feel free to comment or correct me and last but not least thanks for your huge great work 😊

Greetings

**Comment by oxcabe** [comment]
.

**Pull request closed without merging**
