### PR TITLE
Fix UB cases related to bit shifting of 32-bit values

### PR DESCRIPTION
**Pull request by pelijah**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by XVilka** [comment]
Note that some of this code is imported from binutils. So we should think on how to fix them mainstream or save the patch in the tree somehow, like capstone patches

**Comment by radare** [comment]
yep. ths code must be fixed upstream first, otherwise we will reintrorduce the bug when merging back

**Comment by radare** [comment]
why draft? can we merge?

**Comment by radare** [comment]
ping

**Comment by pelijah** [comment]
Maybe my PR is useless. Maybe it breaks some code. It is just the result of monkey work.

**Comment by pelijah** [comment]
зщтп

**Pull request closed without merging**
