### PR TITLE
Move dyldcache symbols to symbols_vec ##bin

### PR DESCRIPTION
**Pull request by mrmacete**
- [x] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

Now it's faster and we don't loose local symbols along the road 😅

### CODE REVIEW

**Comment by trufae** [comment]
Looks great! Do you mind squashing the last 3 commits otherwise ill squash them all when merging

**Comment by mrmacete** [comment]
squashing right now

**Comment by trufae** [comment]
Oh probably i didnt explained well. I wanted to have the redacted commit and the vector one as separate because gh only allows to squash all or none. Anyway merging! That's a good change!

**Comment by mrmacete** [comment]
oops sorry 😓

**Pull request merged**
