### PR TITLE
Remove Custom Analysis for Java

### PR DESCRIPTION
**Pull request by thestr4ng3r**

### CODE REVIEW

**Comment by XVilka** [comment]
The only failing test is not exactly a failure:
```
 va       false
   ;-- entry1:
-  ;-- method.TestVariableSwitchUp.TestMultipleVariable:
-/ (fcn) sym.TestVariableSwitchUp.TestMultipleVariable 37
+  ;-- sym.TestVariableSwitchUp.TestMultipleVariable:
+/ (fcn) method.TestVariableSwitchUp.TestMultipleVariable 37
 | 0x000002fd      1064           bipush 100
```

Could you physically remove the unused code then?

**Comment by thestr4ng3r** [comment]
Yeah the new behavior is actually even better.

**Comment by radare** [comment]
with this i assume the core_jjava plugin is no longer usable?

**Comment by thestr4ng3r** [comment]
It should still work more or less except `r_cmd_java_handle_list_code_references()`. But is it even useful?

**Pull request merged**
