### PR TITLE
Use r_core_cmd_str_pipe when using `.` in a panel

### PR DESCRIPTION
**Pull request by trufae**
* Captures the output of the r2pipe interpreter's `print`

 

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

Running r2pipe scripts in visual panels results in no output captured because the `print` statements of the language are printed directly to fd=2, in order to capture them this patch checks if the command is starting with a dot and uses the cmdstr_pipe() function instead.

Known issues:

* I tried to handle #! but it doesnt works. 

```
$ cat test.py
import r2pipe

r2 = r2pipe.open()
print(r2.cmd("?e hehehehe"))
$
```

**Test plan**

run r2 panels mode like this: `r2 -cv /bin/ls`

press `e` to edit the command to run in the current panel and type `. test.py`

without this patch there's no output captured.

IMAGE 2020-11-28 01:30:46

**Closing issues**

None but reported in the chat by dreg

### CODE REVIEW

**Comment by David-Reguera-Garcia-Dreg** [comment]
dont works with args, ex: . /root/r2-syscall-printer/r2-syscall-printer.py /32 /extra

**Comment by trufae** [comment]
Yes thats expected behaviour because the dot command includes a script. Spaces are treated as spaces in the file name itself.

**Comment by trufae** [comment]
It works now but seems like i broke something else. Must check before merging. Can you test?

**Comment by David-Reguera-Garcia-Dreg** [comment]
The behaviour its annoying: 

pannel_bug_partial

I try also creating r2-script with some prints and I have the same problem, I dont know why. 

This script shows nothing in pannel:
```
#!/usr/bin/env python3
import r2pipe

r2 = r2pipe.open()
print("one")
print("\ntwo\n")
```

In console it works:
```
:> #!pipe python3 /root/r2-syscall-printer/r2-syscall-printer.py /32 /extra
one

two

:>
```

**Comment by trufae** [comment]
git pull and try with this example 👍 
```
$ cat ../lang/py.py
import r2pipe
import sys

a = str(sys.argv)
r2 = r2pipe.open()
print("echo")
r2.cmd("?e hello world %s"%(a))
```

**Comment by trufae** [comment]
In short: 

if yuo use `print` that will be printed to stdout. and rlang cant handle that well because of buffering and other reasons. so in order to print stuff handlable by r2 you need to use rcons, and the way to use rcons from r2pipe is via `?e` to echo things

**Comment by David-Reguera-Garcia-Dreg** [comment]
This dont works:

```
#!/usr/bin/env python3
import r2pipe
import sys

a = str(sys.argv)
r2 = r2pipe.open()
print("echo")
r2.cmd("?e hello world %s"%(a))
print("\nteeest\n")
r2.cmd("?e wooop")
```

**Pull request merged**
