### PR TITLE
Extend ESIL VM's stack size from 32 to 256.

### PR DESCRIPTION
**Pull request by FXTi**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

For bigger stack usage. ESIL command translated from P-codes can use 40~60 elements on stack.

### CODE REVIEW

**Comment by trufae** [comment]
What about 128? 256 seems excessive to me

**Review by XVilka — APPROVED** [review]
Looks good to me. I hope it will not affect the analysis of big files with ESIL involved.

**Comment by trufae** [comment]
May affect r2wars? @sanguinawer

**Comment by FXTi** [comment]
From current evaluation, 128 seems enough. But I recommand 256 just in case.

**Comment by XVilka** [comment]
r2wars are over, time to merge?

**Review by trufae — APPROVED** [review]
Yes

**Pull request merged**
