### PR TITLE
Determine Gameboy hardware registers in disassembly

### PR DESCRIPTION
**Pull request by manuelprinz**
Determining the register strings seems to be working, but I get segfaults afterwards. I'll call it a night and have another go tomorrow. Feedback welcome!

Closes: #7728

### CODE REVIEW

**Comment by Maijin** [comment]
@manuelprinz if you want to help for gameboy support check also this issue out - https://github.com/radareorg/radare2/issues/8088

**Comment by manuelprinz** [comment]
> if you want to help for gameboy support check also this issue out - #8088

Saw that already, thanks! I've somewhat mixed feelings about that, but I'll comment over there.

I'm currently trying to make improvements where I can, but I've not used C in a decade and my time is somewhat limited. I hope I can master the learning curve. Any pointers are appreciated. (Pun intended. :wink: )

**Comment by manuelprinz** [comment]
Problem found, will work on a fix tomorrow.

**Comment by manuelprinz** [comment]
Took a bit longer, sorry! The fix is not great, as the current way to build the plug-in was very confusing. I'm thinking about refactoring that. Is there any documentation on the directory structure I should be aware of?

**Comment by radare** [comment]
Drop the questions here thwres no documentation on that. But ill happily answer them. Do u have telegram maybe its easier to chat there

**Comment by manuelprinz** [comment]
> Drop the questions here thwres no documentation on that. But ill happily answer them.

Thanks! I'll dive into it a bit more first.

> Do u have telegram maybe its easier to chat there

Not yet.

**Comment by radare** [comment]
About refactoring. Yes, we always aim to refactor everything all the time to improve the code quality and be more consistent

**Comment by manuelprinz** [comment]
Should I extend the tests to cover all supported mnemonics?

**Comment by radare** [comment]
that would be neat

**Comment by manuelprinz** [comment]
> that would be neat

Done.

**Comment by manuelprinz** [comment]
Sorry, missed a problem due to issues with the test suite. Rebased on `master`.

**Pull request merged**
