### PR TITLE
Fix #3929 - Enable LTO in sys/static.sh ##build

### LINKED ISSUE #3929: Enable LTO builds
```
export CFLAGS=-flto
export LDFLAGS=-flto
```

For `sdb` this reduces the size of the final static binary in a half (60KB instead of 120KB). For r2 it produces an error, maybe because of the amount of symbols and a bug in the link-time-optimization gcc wrapper.

### PR DESCRIPTION
**Pull request by trufae**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by ret2libc** [comment]
Open a new PR with branc named something like `static-abcdef` so the static CI will run.

**Comment by ret2libc** [comment]
Btw, I think you should list the issue this is going to close in the template... I'm not sure GH is smart enough to close the issue if mentioned only in the commit msg (but if it is, ignore what i said )

**Comment by trufae** [comment]
argh forgot about the branch name, you are right, about github autoclosing issues. we've been doing "Fix #issuenumber - commit description" for years and github handle it properly all the time, see git log fmi. so yeah ill redo inh a different branch name.

**Comment by trufae** [comment]
moved to https://github.com/radareorg/radare2/pull/17141

**Pull request closed without merging**
