### PR TITLE
Throw error when python>3.11 in preconfigure.bat ##build

### PR DESCRIPTION
**Pull request by satk0**
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

### CODE REVIEW

**Comment by trufae** [comment]
I would like to understand better the problematic with python 3.12 before blindmerging this change

**Comment by trufae** [comment]
`pip install setuptools` should fix that

**Comment by satk0** [comment]
Dont merge it, batch is awful, it still is not working, will tell u when

**Comment by satk0** [comment]
Ok, now it's finally working

**Pull request merged**
