### PR TITLE
Fix UB in r_core_anal_type_match

### PR DESCRIPTION
**Pull request by trufae**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Review by ret2libc — COMMENTED** [review]
I'm not sure how there could be UB here, as both `dt` and `et` are initialized in `anal_emul_init` if `core->anal->esil` is not NULL. And if we reach this point in this function it already means `core->anal->esil` is not NULL.

**Comment by trufae** [comment]
some context: 
```
   ^~~~~~~~~~~~~~
anal_tp.c: In function 'r_core_anal_type_match':
anal_tp.c:477:3: warning: 'et' may be used uninitialized in this function [-Wmaybe-uninitialized]
   anal_emul_restore (core, hc, dt, et);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
anal_tp.c:477:3: warning: 'dt' may be used uninitialized in this function [-Wmaybe-uninitialized]
cannotated_code.c: In function 'r_core_annotated_code_print_json':
cannotated_code.c:80:4: warning: 'type_str' may be used uninitialized in this function [-Wmaybe-uninitialized]
    pj_ks (pj, "syntax_highlight", type_str);
```

**Comment by ret2libc** [comment]
As explained in https://github.com/radareorg/radare2/pull/17834#pullrequestreview-515915142, I think this is yet another false positive. So, I'm ok with the change, but I'm not ok with all the claimed "Fix UB" where there is no UB at all.

**Comment by trufae** [comment]
i dont think it's such a big issue to just initialize few vars to avoid those warnings. but its true that the only caller is ensuring this esil &&fcn nonnull. so it looks like a fals positive to me. maybe a compiler bug, i will add compiler version info in the build logs

**Review by wargio — APPROVED** [review]

**Comment by wargio** [comment]
I'm always OK with initializing the vars.

**Comment by ret2libc** [comment]
> i dont think it's such a big issue to just initialize few vars to avoid those warnings. but its true that the only caller is ensuring this esil &&fcn nonnull. so it looks like a fals positive to me. maybe a compiler bug, i will add compiler version info in the build logs

As said, I'm ok with the change, but there is no "UB in r_core_anal_type_match".

**Pull request merged**
