### PR TITLE
Add r_core_esil_{load/unload}_arch ##core

### PR DESCRIPTION
**Pull request by condret**
- [ ] Mark this if you consider it ready to merge
- [ ] I've added tests (optional)
- [ ] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)

**Description**

### CODE REVIEW

**Comment by trufae** [comment]
uhm i dont get the point of those apis, can u explain?

**Comment by condret** [comment]
the point is to painlessly load/unload customops from current arch session/plugin into core esil. These wrappers solely exist, because the arch won't let you do this for any instance of esil that lives outside of arch. This design is not final, and would likely change as soon as thing in arch get better. but until then i want 2 functions that are easy to use, so i can unload and load customops when asm.arch/bits/cpu/etc change.

Maybe these functions should also load register profiles

**Comment by trufae** [comment]
Go for it. We have time for more refactorings

**Comment by trufae** [comment]
Was wondering if this was needed to be public

**Comment by condret** [comment]
It propably doesn't need to be part of the public api. however for now i keep it public so that i can call it from #!c during the esil refactoring

**Pull request merged**
