### PR TITLE
Fix #15734 - Automatically download PDB file if pdb.autoload=1

### LINKED ISSUE #15734: Windows PDB server not available anymore. Any other option?
I am trying to debug Win32 program but the PDB server from Microsoft is not available anymore.
What other option do I have to get Windows symbols. The first PDB that radare2 is complaining is ntdll.pdb.

Be dependent on MS was always a headache.

### PR DESCRIPTION
**Pull request by GustavoLCR**
Fix #15734

### CODE REVIEW

**Comment by ITAYC0HEN** [comment]
our king of windows things ♥

**Comment by XVilka** [comment]
@GustavoLCR could you please rebase on top of the latest green commit - https://github.com/radareorg/radare2/commit/0db3d9a0fc0ed20dcf496f77705ca839331ce068

So we can be sure your PR doesn't break anything (it shouldn't, but just in case) before merging.

**Comment by GustavoLCR** [comment]
> @GustavoLCR could you please rebase on top of the latest green commit - [0db3d9a](https://github.com/radareorg/radare2/commit/0db3d9a0fc0ed20dcf496f77705ca839331ce068)
> 
> So we can be sure your PR doesn't break anything (it shouldn't, but just in case) before merging.

@XVilka Seems like CI always use latest master, travis is still red even after rebasing

**Comment by XVilka** [comment]
@GustavoLCR thanks, that's really sad then. Anyway, checked the PR - it looks fine, lets merge it.

**Comment by radare** [comment]
Reverting my r2r update should be enough to get it green again but i dont see why my change should produce those errors

**Comment by XVilka** [comment]
I didn't revert because I wasn't sure. It looks like might be a capstone problem again.

**Pull request merged**
