### PR TITLE
Add initial sparc regression tests (#15602)

### PR DESCRIPTION
**Pull request by AdamVanScyoc**
#15563
Basic Sparc regressions tests.

Note: relates to [https://github.com/radareorg/radare2/issues/15602#issue-534934335](url) as I took two Sparc binaries from there.

Inspired by regressions tests found in anal/x86_32

### CODE REVIEW

**Comment by AdamVanScyoc** [comment]
I can submit a pull request to the radare test binaries repo with the 2 sparc binaries I used added as well

**Comment by Maijin** [comment]
That's great start! Yes please do upload the binaries

**Comment by Maijin** [comment]
You can check also the assembly/disassembly tests https://github.com/radareorg/radare2/tree/master/test/new/db/asm

**Comment by AdamVanScyoc** [comment]
> You can check also the assembly/disassembly tests https://github.com/radareorg/radare2/tree/master/test/new/db/asm

I am having trouble getting radare2 to assemble sparc instrutcions. Is the sparc assembler definitely 100% implemented?

`r2 -
e asm.arch=sparc
e asm.bits=32
pa "mov 0, fp"
`
Doesn't work.

**Comment by Maijin** [comment]
assembler is not implemented but disassembly is :) (See `rasm2 -L`)

**Comment by XVilka** [comment]
Can you please do a clean rebase instead?

**Comment by AdamVanScyoc** [comment]
> Can you please do a clean rebase instead?

Did I do it right?

(still working on asm tests)

**Comment by XVilka** [comment]
Yes, thank you!

**Comment by radare** [comment]
why is this still a draft? cant we merge it?

**Comment by AdamVanScyoc** [comment]
> 
> 
> why is this still a draft? cant we merge it?

More than welcome to merge. I intend on adding more asm tests. School is keeping me very busy, sorry for delay.

**Comment by radare** [comment]
Drop the draft option and ill merge you can submit more tests in a separate pr

**Pull request merged**
