### PR TITLE
Fix #17776 - Command parsing issue related to wrongly quoted comments

### LINKED ISSUE #17776: Command parsing doesn't correctly ignore text after hashtag
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | N/A
| Architecture/bits of the file (mandatory)            | N/A
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.6.0-git 25157 @ linux-x86-64 git.4.4.0-805-g6c89716d4
commit: 6c89716d44cc6198d9ac1dcc632d4e1b71e6b714 build: 2020-10-10__22:51:30

### Expected behavior

Print help text

### Actual behavior

Activates visual mode

### Steps to reproduce the behavior 
- Open any binary
- Enter the command `?#;v"`

_Note that any command can take the place of `?`_

### Additional Logs, screenshots, source-code,  configuration dump, ...

This is also the cause of some projects not loading. Projects contain `Cs` commands, followed by a comment and the string as plain text. If any part of the string matches the regex `/;.+\"/gi`, then it will try to execute the text after the `;` as a command.

### PR DESCRIPTION
**Pull request by trufae**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by XVilka** [comment]
It breaks many things:
```
[XX] db/formats/smd smd strings
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '. scripts/smd_strings.r2
e bin.str.filter=U
izz
' malloc://256k
-- stdout
@@ -76,23 +76,22 @@
 78  0x0000811d 0x0000811d 27  28           ascii CODIGO DA AGENCIA INCORRETO
 79  0x00008139 0x00008139 35  36           ascii DATA DO CARTAO DE CREDITO INCORRETA
 80  0x0000818c 0x0000818c 52  53           ascii 001002003005010011004020021022030031999040041042043N
-87  0x0000a9bf 0x0000a9bf 12  13           ascii IJKLMNOPQRST
-123 0x0000dfff 0x0000dfff 43  44           ascii >?@ABCDEFGHIJKLMNOPQQRSTULKJIHGFEDCBA@?>VWX
-126 0x0000e2ba 0x0000e2ba 11  12           ascii CDEFGHIJKL*
-127 0x0000e2ce 0x0000e2ce 11  12           ascii MNOPQORSPT*
-132 0x0000e44d 0x0000e44d 21  22           ascii AB,CDEFGHIJKLMNOPQRST
-133 0x0000e463 0x0000e463 14  15           ascii QUVWXWYZ[\]^_R
-141 0x0000e723 0x0000e723 12  13           ascii #QRSTUVWRXYZ
-143 0x0000e8b8 0x0000e8b8 15  16           ascii 6789:;<=>?@ABCD
-152 0x0000ef10 0x0000ef10 12  13           ascii >?@>ABCDEF@G
-153 0x0000ef1e 0x0000ef1e 12  13           ascii HIJKLJMNOPQR
-154 0x0000ef2c 0x0000ef2c 12  13           ascii STUVWUXYZ[\]
-170 0x000166ae 0x000166ae 16  17           ascii SUSU355355S53553
-171 0x00016947 0x00016947 13  14           ascii 5S5S3UU355U53
-172 0x00016963 0x00016963 10  11           ascii U3UU5SS3S3
-200 0x00017d0e 0x00017d0e 14  15           ascii DEAQDEATDEATDE
-243 0x000194cc 0x000194cc 14  15           ascii DEAQDEATDEATDE
-283 0x0001acde 0x0001acde 14  15           ascii DEAQDEATDEATDE
-325 0x0001c542 0x0001c542 14  15           ascii DEAQDEATDEATDE
-369 0x0001d8aa 0x0001d8aa 12  13           ascii DDEQTDDEUUUU
-394 0x0002036c 0x0002036c 63  64           ascii 3331333333333333DDDADDDADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDADDDADDD
+85  0x0000a9bf 0x0000a9bf 12  13           ascii IJKLMNOPQRST
+121 0x0000dfff 0x0000dfff 43  44           ascii >?@ABCDEFGHIJKLMNOPQQRSTULKJIHGFEDCBA@?>VWX
+124 0x0000e2ba 0x0000e2ba 11  12           ascii CDEFGHIJKL*
+125 0x0000e2ce 0x0000e2ce 11  12           ascii MNOPQORSPT*
+130 0x0000e44d 0x0000e44d 21  22           ascii AB,CDEFGHIJKLMNOPQRST
+131 0x0000e463 0x0000e463 14  15           ascii QUVWXWYZ[\]^_R
+138 0x0000e8b8 0x0000e8b8 15  16           ascii 6789:;<=>?@ABCD
+144 0x0000ef10 0x0000ef10 12  13           ascii >?@>ABCDEF@G
+145 0x0000ef1e 0x0000ef1e 12  13           ascii HIJKLJMNOPQR
+146 0x0000ef2c 0x0000ef2c 12  13           ascii STUVWUXYZ[\]
+162 0x000166ae 0x000166ae 16  17           ascii SUSU355355S53553
+163 0x00016947 0x00016947 13  14           ascii 5S5S3UU355U53
+164 0x00016963 0x00016963 10  11           ascii U3UU5SS3S3
+192 0x00017d0e 0x00017d0e 14  15           ascii DEAQDEATDEATDE
+235 0x000194cc 0x000194cc 14  15           ascii DEAQDEATDEATDE
+275 0x0001acde 0x0001acde 14  15           ascii DEAQDEATDEATDE
+317 0x0001c542 0x0001c542 14  15           ascii DEAQDEATDEATDE
+361 0x0001d8aa 0x0001d8aa 12  13           ascii DDEQTDDEUUUU
+386 0x0002036c 0x0002036c 63  64           ascii 3331333333333333DDDADDDADDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDADDDADDD

[XX] db/cmd/write quoted comments bug
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '"w hello # world"
ps
' malloc://1024
-- stdout
@@ -1 +1 @@
-hello # world
+

[XX] db/cmd/feat_input hash+space in quoted string
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'agn "Process form A# B# in cloud"
agg
' -
-- stdout
@@ -1,3 +1,3 @@
-.-------------------------------.
-|  Process form A# B# in cloud  |
-`-------------------------------'
+.--------------------.
+|  Process form A    |
+`--------------------'

[XX] db/cmd/feat_input w foo#bar
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '"w foo#bar"
psz
' malloc://1024
-- stdout
@@ -1 +1 @@
-foo#bar
+

[XX] db/cmd/cmd_interpret $foo=#!pipe
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '#!pipe echo hello
$foo=#!pipe echo hello
$foo
?e --
"$foo=#!pipe echo hello"
$foo
?e --
$-*
e cfg.newshell=true
$foo=\#!pipe echo hello
$foo
?e --
$-*
' -
-- stdout
@@ -1,6 +1,5 @@
 hello
 --
-hello
 --
 hello
 --


-- stderr
Missing " in ($foo=).
```

**Comment by XVilka** [comment]
```
[XX] db/cmd/cmds quotes multicommands 2
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'e asm.arch=x86
e asm.bits=32
p8 1;"wa nop;nop";pi 3
' malloc://128
-- stdout
@@ -1,4 +1 @@
 00
-nop
-nop
-add byte [eax], al

[XX] db/cmd/cmd_avr avrD msvc namespaces
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'e anal.cpp.abi=msvc;"avrD .?AVClassInInnerNamespace@InnerNamespace@OuterNamespace@@"' --
-- stdout
@@ -1 +0,0 @@
-OuterNamespace::InnerNamespace::ClassInInnerNamespace

[XX] db/cmd/cmd_avr avrD msvc simple
R2_NOPLUGINS=1 radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'e anal.cpp.abi=msvc;"avrD .?AVClassName@@"' --
-- stdout
@@ -1 +0,0 @@
-ClassName
```

**Comment by trufae** [comment]
I did a couple of tries, but i dont think this issue can't be solved in the old parser, basically because it requires so much context, Because the meaning of `#` is not the same inside a shell command, at the begining of the command, in the middle, in a command with multiple semicolon, etc. i tried to do some workarounds for common cases but anything i can do here is just a hack. i will do more tries to get this working, but maybe this test should run only in newshell mode.

**Comment by XVilka** [comment]
I suggest then to close this and focus on the new parser instead.

**Comment by trufae** [comment]
Probably not worth messing with this hack, the parsing issue is not that problematic and it works well with a proper command parser

**Pull request closed without merging**
