### PR TITLE
Initial impl. get trycatch from x64 PE SEH

### PR DESCRIPTION
**Pull request by GustavoLCR**

### CODE REVIEW

**Comment by XVilka** [comment]
Can you please add an example of output and/or tests?

**Comment by GustavoLCR** [comment]
Added tests in https://github.com/radareorg/radare2-regressions/pull/1970

### Heres an example from the binary on my R2R pull:
image

### And the code:
image

**Comment by radare** [comment]
Is this integrated with iw command like i did for dex?

**Comment by GustavoLCR** [comment]
Yes, iw uses this.

Em sex, 4 de out de 2019 04:22, radare <notifications@github.com> escreveu:

> Is this integrated with iw command like i did for dex?
>

**Comment by radare** [comment]
Awesome

**Pull request merged**
