### PR TITLE
WIP: Fix entrypoint on ELF when its pointing to null ##bin

### PR DESCRIPTION
**Pull request by radare**

### CODE REVIEW

**Comment by radare** [comment]
This fixed loading the 0pack

**Comment by XVilka** [comment]
@radare what you decided with this one?

**Comment by radare** [comment]
Its not about deciding. The pr is not good yet

**Comment by radare** [comment]
@ret2libc feedback/code for this?

**Comment by ITAYC0HEN** [comment]
CC @ret2libc

**Comment by ret2libc** [comment]
I would love to see a binary with the issue before working on a fix

**Comment by radare** [comment]
This issue fixes https://github.com/radareorg/radare2/issues/14293 and the bin is there

**Comment by radare** [comment]
@ret2libc https://github.com/Luis-Hebendanz/0pack/releases/download/v1.0/0pack its a 17MB binary  :(( i wish we had a smaller reproducer

**Comment by XVilka** [comment]
@radare we can create a sparse binaries format for the tests - see https://github.com/radareorg/radare2/issues/16184

**Comment by radare** [comment]
Isnt that supported by git? Whats the problem you sre trying to solve? Loading huge files with gaps as sparsed files? Not sure how that will improve this test but we can use gzip:// in here i guess

**Comment by XVilka** [comment]
@radare not quite. I suggest to create a binary instead of series `wx .... @`, `wx ... @`, and so on. Quite often these many huge files can be reduced to just a few pieces, e.g. header and a few blocks in the selected locations.

**Comment by radare** [comment]
Gzip or ihe. Works fine for those cases

**Comment by XVilka** [comment]
Not sure what "ihe" is. GZip will not create sparse files, it can just compress them.

**Comment by ret2libc** [comment]
@radare I think the binary you put in elf/0pack is not the right one, as that has not entry_point==0 in the file header.

**Comment by radare** [comment]
The Good one is 17MB.. though the 7MB version used the same trick..

**Comment by Luis-Hebendanz** [comment]
I re-uploaded the 7Mb 0Pack binary because I forgot to patch the loader path so that it works under non NixOS systems. Now it works I verified it :-)

**Comment by radare** [comment]
Cc @ret2libc

**Comment by ret2libc** [comment]
I will try to give this another try before 4.5.0, thought it requires a bit of refactoring here and there in elf code, which was assuming in general 0 was a "bad value".

**Comment by radare** [comment]
yeah, 0 is not that bad

**Comment by radare** [comment]
pls fix conflicts

**Comment by ret2libc** [comment]
No need, I still need to fix many things here. No time right now.

**Comment by ret2libc** [comment]
Closing as this needs anyway a lot of re-work because many things changed in elf and the current state was not working nonetheless. There is also already an issue https://github.com/radareorg/radare2/issues/14293 for this.

**Pull request closed without merging**
