### PR TITLE
Use higher value for the default esil stack address ##esil

### PR DESCRIPTION
**Pull request by radare**
* We need a better solution to avoid overlaps
* But this is solving problems on big so/o files

### CODE REVIEW

**Comment by condret** [comment]
new anti-r2: change va in an elf file, so that r2 users cannot aeim

**Comment by radare** [comment]
@ret2libc feedback on this?

**Comment by ret2libc** [comment]
I'm not the best person for ESIL stuff, sorry. I don't know anything about it and i don't use it

**Comment by radare** [comment]
well thats just a matter of adding an api in IO to give us a address to place the stack. because we need to not overlap a ything that is already mapped. so assuming ahigher address by default is fine, but this can be also wrong

**Comment by radare** [comment]
Cc @condret related to r_io_map_location()

**Comment by radare** [comment]
cc @condret this PR requires the r_io_map_location() api to be fixed properly

**Comment by radare** [comment]
this is probably easier to fix now that tests are in the same repo, but we need an api in IO to ask for a region to be allocated at a specific range that is not overlapping any map

**Comment by radare** [comment]
@thestr4ng3r c0mments or ideas for this issue?

**Comment by thestr4ng3r** [comment]
I think the stack addr can easily depend on a lot of things in practice (arch, bits <- this especially, the kernel, aslr, ...) so by default we may want to have `esil.stack.addr` to be set to 0 or UT64_MAX to indicate that it should be created automatically and implement some magic that finds a good addr given all the arch, os, etc. properties. In theory this could also be a callback in an anal plugin to override the builtin magic with custom magic.

**Comment by radare** [comment]
The only missing piece to get this done is to have the function that given a size and a minaddr returns a valid memory range that is not covered by any io map. Anyone?

**Comment by radare** [comment]
ive fixed this with -e esil.stack.addr=-1

**Pull request closed without merging**
