### PR TITLE
Add missing ELF DT entries ##bin

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)

**Detailed description**

Add missing ELF dynamic tag entries to be parsed.

### CODE REVIEW

**Comment by trufae** [comment]
i think it's fine to initialize them even if we are not using them, but this should be displayed with `iH`

**Comment by trufae** [comment]
Please fix the tests, new output is better

**Comment by ret2libc** [comment]
> i think it's fine to initialize them even if we are not using them, but this should be displayed with `iH`

@XVilka yes, either you print or use them somehow or don't store the value at all (just handle them in the switch).

**Comment by trufae** [comment]
add ##bin

**Comment by ret2libc** [comment]
@XVilka ping . please just remove the additional unused variables and let's get rid of the common missing dynamic tags.

**Comment by trufae** [comment]
ping

**Comment by ret2libc** [comment]
@XVilka Sorry, I messed up somehow with your branch while trying to push this forward. Please have a look and let's merge this so we can remove those warnings that are common and I can go ahead with https://github.com/radareorg/radare2/pull/17195 . 

I have just kept the warnings for some uncommon MIPS dt entries which would be cool in the future to properly support though.

**Pull request merged**
